In [2]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
!python srul_colab_project.py \
    --dataset fashionmnist \
    --latent-dim 16 \
    --ae-epochs 8 \
    --prior-epochs 15 \
    --baseline-epochs 10 \
    --sigma-enc 0.20 \
    --out-dir "/content/drive/MyDrive/SRUL_results"

Device: cuda
Output directory: /content/drive/MyDrive/SRUL_results

Stage 1: spherical autoencoder
[AE] 001/8 total=0.0835 recon=0.0808 cons=0.0022 lat=0.0322
[AE] 002/8 total=0.0512 recon=0.0444 cons=0.0071 lat=0.0643
[AE] 003/8 total=0.0435 recon=0.0350 cons=0.0092 lat=0.0771
[AE] 004/8 total=0.0385 recon=0.0283 cons=0.0117 lat=0.0863
[AE] 005/8 total=0.0367 recon=0.0260 cons=0.0125 lat=0.0875
[AE] 006/8 total=0.0359 recon=0.0250 cons=0.0128 lat=0.0883
[AE] 007/8 total=0.0352 recon=0.0243 cons=0.0131 lat=0.0878
[AE] 008/8 total=0.0348 recon=0.0237 cons=0.0133 lat=0.0886

Stage 2: SRUL geodesic prior
[SRUL PRIOR] 001/15 loss=1.8231 omega=1.5729 weight=0.7729
[SRUL PRIOR] 002/15 loss=1.8005 omega=1.5709 weight=0.7731
[SRUL PRIOR] 003/15 loss=1.7917 omega=1.5688 weight=0.7730
[SRUL PRIOR] 004/15 loss=1.7958 omega=1.5698 weight=0.7735
[SRUL PRIOR] 005/15 loss=1.7974 omega=1.5734 weight=0.7719
[SRUL PRIOR] 006/15 loss=1.7947 omega=1.5704 weight=0.7725
[SRUL PRIOR] 007/15 loss=1.8041 omega=1.5731 weight=0.7751
[SRUL PRIOR] 008/15 loss=1.7878 omega=1.5686 weight=0.7743
[SRUL PRIOR] 009/15 loss=1.8066 omega=1.5740 weight=0.7744
[SRUL PRIOR] 010/15 loss=1.7924 omega=1.5725 weight=0.7720
[SRUL PRIOR] 011/15 loss=1.7822 omega=1.5674 weight=0.7727
[SRUL PRIOR] 012/15 loss=1.7926 omega=1.5720 weight=0.7726
[SRUL PRIOR] 013/15 loss=1.7902 omega=1.5710 weight=0.7722
[SRUL PRIOR] 014/15 loss=1.7849 omega=1.5693 weight=0.7727
[SRUL PRIOR] 015/15 loss=1.7743 omega=1.5729 weight=0.7696

Stage 3: Euclidean chord prior baseline
[EUCLIDEAN PRIOR] 001/10 loss=0.1143 chord_norm=0.8084
[EUCLIDEAN PRIOR] 002/10 loss=0.1015 chord_norm=0.8091
[EUCLIDEAN PRIOR] 003/10 loss=0.0961 chord_norm=0.8097
[EUCLIDEAN PRIOR] 004/10 loss=0.0950 chord_norm=0.8085
[EUCLIDEAN PRIOR] 005/10 loss=0.0940 chord_norm=0.8091
[EUCLIDEAN PRIOR] 006/10 loss=0.0932 chord_norm=0.8087
[EUCLIDEAN PRIOR] 007/10 loss=0.0926 chord_norm=0.8095
[EUCLIDEAN PRIOR] 008/10 loss=0.0923 chord_norm=0.8096
[EUCLIDEAN PRIOR] 009/10 loss=0.0922 chord_norm=0.8082
[EUCLIDEAN PRIOR] 010/10 loss=0.0917 chord_norm=0.8099

Saving visualizations and metrics
sigma=0.020, recon_mse=0.023377
sigma=0.050, recon_mse=0.024003
sigma=0.100, recon_mse=0.026224
sigma=0.200, recon_mse=0.035912
sigma=0.350, recon_mse=0.081994
sigma=0.500, recon_mse=0.158973
Done. Check output directory for images and metrics.

In [3]:
!python /content/srul_cifar_next_experiment.py \
  --out-dir /content/drive/MyDrive/SRUL_CIFAR10/pilot \
  --methods gaussian_fm chord rfm srul latent_ddpm \
  --train-samples 20000 --test-samples 10000 \
  --ae-epochs 20 --prior-epochs 30 \
  --latent-dim 128 --base-channels 64 \
  --prior-width 512 --prior-depth 4 --time-dim 128 \
  --batch-size 256 --num-workers 2 \
  --metric-samples 5000 --pr-samples 2000 \
  --recon-metric-samples 2000 \
  --sample-steps 50 --diffusion-steps 1000 \
  --sigma-enc 0.20 --seed 0 \
  --checkpoint-every 5 --amp --resume

================================================================================
SRUL CIFAR-10 experiment
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/pilot/seed_0
Methods: ['gaussian_fm', 'chord', 'rfm', 'srul', 'latent_ddpm']
================================================================================
100% 170M/170M [27:56<00:00, 102kB/s]
[AE] 001/20 loss=0.6109 clean=0.3035 noisy=0.3040 lat=0.0671
[AE] 002/20 loss=0.4612 clean=0.2295 noisy=0.2306 lat=0.0209
[AE] 003/20 loss=0.4167 clean=0.2070 noisy=0.2085 lat=0.0234
[AE] 004/20 loss=0.3708 clean=0.1837 noisy=0.1858 lat=0.0255
[AE] 005/20 loss=0.3485 clean=0.1724 noisy=0.1750 lat=0.0223
[AE] 006/20 loss=0.3294 clean=0.1626 noisy=0.1656 lat=0.0227
[AE] 007/20 loss=0.3181 clean=0.1567 noisy=0.1602 lat=0.0231
[AE] 008/20 loss=0.3084 clean=0.1517 noisy=0.1556 lat=0.0212
[AE] 009/20 loss=0.3030 clean=0.1489 noisy=0.1529 lat=0.0235
[AE] 010/20 loss=0.2917 clean=0.1432 noisy=0.1476 lat=0.0200
[AE] 011/20 loss=0.2860 clean=0.1402 noisy=0.1448 lat=0.0200
[AE] 012/20 loss=0.2798 clean=0.1369 noisy=0.1418 lat=0.0213
[AE] 013/20 loss=0.2757 clean=0.1347 noisy=0.1398 lat=0.0241
[AE] 014/20 loss=0.2674 clean=0.1304 noisy=0.1359 lat=0.0227
[AE] 015/20 loss=0.2650 clean=0.1290 noisy=0.1348 lat=0.0238
[AE] 016/20 loss=0.2589 clean=0.1259 noisy=0.1319 lat=0.0217
[AE] 017/20 loss=0.2556 clean=0.1241 noisy=0.1304 lat=0.0227
[AE] 018/20 loss=0.2507 clean=0.1215 noisy=0.1281 lat=0.0223
[AE] 019/20 loss=0.2484 clean=0.1202 noisy=0.1270 lat=0.0222
[AE] 020/20 loss=0.2454 clean=0.1187 noisy=0.1256 lat=0.0228

--------------------------------------------------------------------------------
Training prior: gaussian_fm
[gaussian_fm] 001/30 loss=0.83824 path_norm=5.7385
[gaussian_fm] 002/30 loss=0.55689 path_norm=5.7471
[gaussian_fm] 003/30 loss=0.36832 path_norm=5.7522
[gaussian_fm] 004/30 loss=0.25725 path_norm=5.7419
[gaussian_fm] 005/30 loss=0.21114 path_norm=5.7087
[gaussian_fm] 006/30 loss=0.18671 path_norm=5.7760
[gaussian_fm] 007/30 loss=0.17582 path_norm=5.7417
[gaussian_fm] 008/30 loss=0.17206 path_norm=5.7156
[gaussian_fm] 009/30 loss=0.16472 path_norm=5.6860
[gaussian_fm] 010/30 loss=0.16115 path_norm=5.7386
[gaussian_fm] 011/30 loss=0.15338 path_norm=5.7547
[gaussian_fm] 012/30 loss=0.15255 path_norm=5.7465
[gaussian_fm] 013/30 loss=0.14802 path_norm=5.7196
[gaussian_fm] 014/30 loss=0.14580 path_norm=5.7306
[gaussian_fm] 015/30 loss=0.14092 path_norm=5.7316
[gaussian_fm] 016/30 loss=0.14000 path_norm=5.7453
[gaussian_fm] 017/30 loss=0.13823 path_norm=5.7839
[gaussian_fm] 018/30 loss=0.13373 path_norm=5.7827
[gaussian_fm] 019/30 loss=0.13416 path_norm=5.7431
[gaussian_fm] 020/30 loss=0.13083 path_norm=5.7799
[gaussian_fm] 021/30 loss=0.13041 path_norm=5.7585
[gaussian_fm] 022/30 loss=0.12762 path_norm=5.7761
[gaussian_fm] 023/30 loss=0.12796 path_norm=5.7507
[gaussian_fm] 024/30 loss=0.12496 path_norm=5.7863
[gaussian_fm] 025/30 loss=0.12898 path_norm=5.7142
[gaussian_fm] 026/30 loss=0.12491 path_norm=5.7764
[gaussian_fm] 027/30 loss=0.12678 path_norm=5.7374
[gaussian_fm] 028/30 loss=0.12420 path_norm=5.7359
[gaussian_fm] 029/30 loss=0.12660 path_norm=5.7353
[gaussian_fm] 030/30 loss=0.12423 path_norm=5.7663

--------------------------------------------------------------------------------
Training prior: chord
[chord] 001/30 loss=0.01323 path_norm=0.8121
[chord] 002/30 loss=0.01175 path_norm=0.8106
[chord] 003/30 loss=0.01133 path_norm=0.8104
[chord] 004/30 loss=0.01104 path_norm=0.8111
[chord] 005/30 loss=0.01081 path_norm=0.8116
[chord] 006/30 loss=0.01066 path_norm=0.8110
[chord] 007/30 loss=0.01054 path_norm=0.8105
[chord] 008/30 loss=0.01041 path_norm=0.8113
[chord] 009/30 loss=0.01033 path_norm=0.8116
[chord] 010/30 loss=0.01027 path_norm=0.8109
[chord] 011/30 loss=0.01024 path_norm=0.8114
[chord] 012/30 loss=0.01020 path_norm=0.8105
[chord] 013/30 loss=0.01014 path_norm=0.8109
[chord] 014/30 loss=0.01010 path_norm=0.8102
[chord] 015/30 loss=0.01009 path_norm=0.8113
[chord] 016/30 loss=0.01006 path_norm=0.8114
[chord] 017/30 loss=0.01004 path_norm=0.8107
[chord] 018/30 loss=0.01002 path_norm=0.8101
[chord] 019/30 loss=0.01000 path_norm=0.8118
[chord] 020/30 loss=0.01000 path_norm=0.8119
[chord] 021/30 loss=0.00997 path_norm=0.8113
[chord] 022/30 loss=0.00996 path_norm=0.8116
[chord] 023/30 loss=0.00995 path_norm=0.8117
[chord] 024/30 loss=0.00994 path_norm=0.8107
[chord] 025/30 loss=0.00993 path_norm=0.8112
[chord] 026/30 loss=0.00993 path_norm=0.8130
[chord] 027/30 loss=0.00988 path_norm=0.8112
[chord] 028/30 loss=0.00989 path_norm=0.8109
[chord] 029/30 loss=0.00989 path_norm=0.8115
[chord] 030/30 loss=0.00987 path_norm=0.8117

--------------------------------------------------------------------------------
Training prior: rfm
[rfm] 001/30 loss=0.01744 path_norm=1.0000
[rfm] 002/30 loss=0.01653 path_norm=1.0000
[rfm] 003/30 loss=0.01618 path_norm=1.0000
[rfm] 004/30 loss=0.01591 path_norm=1.0000
[rfm] 005/30 loss=0.01572 path_norm=1.0000
[rfm] 006/30 loss=0.01563 path_norm=1.0000
[rfm] 007/30 loss=0.01556 path_norm=1.0000
[rfm] 008/30 loss=0.01552 path_norm=1.0000
[rfm] 009/30 loss=0.01548 path_norm=1.0000
[rfm] 010/30 loss=0.01545 path_norm=1.0000
[rfm] 011/30 loss=0.01543 path_norm=1.0000
[rfm] 012/30 loss=0.01538 path_norm=1.0000
[rfm] 013/30 loss=0.01538 path_norm=1.0000
[rfm] 014/30 loss=0.01535 path_norm=1.0000
[rfm] 015/30 loss=0.01528 path_norm=1.0000
[rfm] 016/30 loss=0.01532 path_norm=1.0000
[rfm] 017/30 loss=0.01529 path_norm=1.0000
[rfm] 018/30 loss=0.01528 path_norm=1.0000
[rfm] 019/30 loss=0.01528 path_norm=1.0000
[rfm] 020/30 loss=0.01527 path_norm=1.0000
[rfm] 021/30 loss=0.01527 path_norm=1.0000
[rfm] 022/30 loss=0.01523 path_norm=1.0000
[rfm] 023/30 loss=0.01525 path_norm=1.0000
[rfm] 024/30 loss=0.01524 path_norm=1.0000
[rfm] 025/30 loss=0.01519 path_norm=1.0000
[rfm] 026/30 loss=0.01521 path_norm=1.0000
[rfm] 027/30 loss=0.01517 path_norm=1.0000
[rfm] 028/30 loss=0.01519 path_norm=1.0000
[rfm] 029/30 loss=0.01517 path_norm=1.0000
[rfm] 030/30 loss=0.01515 path_norm=1.0000

--------------------------------------------------------------------------------
Training prior: srul
[srul] 001/30 loss=0.01340 path_norm=1.0000
[srul] 002/30 loss=0.01271 path_norm=1.0000
[srul] 003/30 loss=0.01248 path_norm=1.0000
[srul] 004/30 loss=0.01228 path_norm=1.0000
[srul] 005/30 loss=0.01216 path_norm=1.0000
[srul] 006/30 loss=0.01204 path_norm=1.0000
[srul] 007/30 loss=0.01203 path_norm=1.0000
[srul] 008/30 loss=0.01188 path_norm=1.0000
[srul] 009/30 loss=0.01194 path_norm=1.0000
[srul] 010/30 loss=0.01188 path_norm=1.0000
[srul] 011/30 loss=0.01183 path_norm=1.0000
[srul] 012/30 loss=0.01185 path_norm=1.0000
[srul] 013/30 loss=0.01187 path_norm=1.0000
[srul] 014/30 loss=0.01182 path_norm=1.0000
[srul] 015/30 loss=0.01181 path_norm=1.0000
[srul] 016/30 loss=0.01183 path_norm=1.0000
[srul] 017/30 loss=0.01176 path_norm=1.0000
[srul] 018/30 loss=0.01168 path_norm=1.0000
[srul] 019/30 loss=0.01181 path_norm=1.0000
[srul] 020/30 loss=0.01176 path_norm=1.0000
[srul] 021/30 loss=0.01173 path_norm=1.0000
[srul] 022/30 loss=0.01177 path_norm=1.0000
[srul] 023/30 loss=0.01175 path_norm=1.0000
[srul] 024/30 loss=0.01175 path_norm=1.0000
[srul] 025/30 loss=0.01175 path_norm=1.0000
[srul] 026/30 loss=0.01171 path_norm=1.0000
[srul] 027/30 loss=0.01174 path_norm=1.0000
[srul] 028/30 loss=0.01172 path_norm=1.0000
[srul] 029/30 loss=0.01172 path_norm=1.0000
[srul] 030/30 loss=0.01174 path_norm=1.0000

--------------------------------------------------------------------------------
Training prior: latent_ddpm
[latent_ddpm] 001/30 loss=0.01160 path_norm=7.3420
[latent_ddpm] 002/30 loss=0.01205 path_norm=7.3346
[latent_ddpm] 003/30 loss=0.01189 path_norm=7.3265
[latent_ddpm] 004/30 loss=0.01181 path_norm=7.3307
[latent_ddpm] 005/30 loss=0.01177 path_norm=7.3399
[latent_ddpm] 006/30 loss=0.01170 path_norm=7.3188
[latent_ddpm] 007/30 loss=0.01170 path_norm=7.3306
[latent_ddpm] 008/30 loss=0.01175 path_norm=7.3674
[latent_ddpm] 009/30 loss=0.01165 path_norm=7.3149
[latent_ddpm] 010/30 loss=0.01169 path_norm=7.3664
[latent_ddpm] 011/30 loss=0.01166 path_norm=7.3406
[latent_ddpm] 012/30 loss=0.01165 path_norm=7.3475
[latent_ddpm] 013/30 loss=0.01165 path_norm=7.3450
[latent_ddpm] 014/30 loss=0.01159 path_norm=7.3007
[latent_ddpm] 015/30 loss=0.01159 path_norm=7.3260
[latent_ddpm] 016/30 loss=0.01160 path_norm=7.3257
[latent_ddpm] 017/30 loss=0.01162 path_norm=7.3555
[latent_ddpm] 018/30 loss=0.01158 path_norm=7.3522
[latent_ddpm] 019/30 loss=0.01154 path_norm=7.3145
[latent_ddpm] 020/30 loss=0.01161 path_norm=7.3329
[latent_ddpm] 021/30 loss=0.01162 path_norm=7.3752
[latent_ddpm] 022/30 loss=0.01158 path_norm=7.3596
[latent_ddpm] 023/30 loss=0.01158 path_norm=7.3264
[latent_ddpm] 024/30 loss=0.01162 path_norm=7.3883
[latent_ddpm] 025/30 loss=0.01157 path_norm=7.3279
[latent_ddpm] 026/30 loss=0.01157 path_norm=7.3366
[latent_ddpm] 027/30 loss=0.01157 path_norm=7.3553
[latent_ddpm] 028/30 loss=0.01156 path_norm=7.3155
[latent_ddpm] 029/30 loss=0.01149 path_norm=7.3044
[latent_ddpm] 030/30 loss=0.01152 path_norm=7.3080
Extracting real ResNet-18 features for feature precision/recall...
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100% 44.7M/44.7M [00:00<00:00, 276MB/s]

--------------------------------------------------------------------------------
Sampling and evaluating: gaussian_fm
Computing FID/KID...
Traceback (most recent call last):
  File "/content/srul_cifar_next_experiment.py", line 1880, in <module>
    main()
  File "/content/srul_cifar_next_experiment.py", line 1876, in main
    run_experiment(config)
  File "/content/srul_cifar_next_experiment.py", line 1818, in run_experiment
    compute_fid_kid(
  File "/content/srul_cifar_next_experiment.py", line 1202, in compute_fid_kid
    raise RuntimeError(
RuntimeError: torchmetrics image dependencies are unavailable. In Colab run: pip install 'torchmetrics[image]' torch-fidelity

In [1]:
!pip install -q "torchmetrics[image]" torch-fidelity

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 42.6 MB/s eta 0:00:00

In [5]:
from torchmetrics.image.fid import FrechetInceptionDistance
from torchmetrics.image.kid import KernelInceptionDistance

print("FID/KID dependencies are ready.")

FID/KID dependencies are ready.

In [6]:
!python /content/srul_cifar_next_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_CIFAR10/pilot" \
    --methods gaussian_fm chord rfm srul latent_ddpm \
    --train-samples 20000 \
    --test-samples 10000 \
    --ae-epochs 20 \
    --prior-epochs 30 \
    --latent-dim 128 \
    --base-channels 64 \
    --prior-width 512 \
    --prior-depth 4 \
    --time-dim 128 \
    --batch-size 256 \
    --num-workers 2 \
    --metric-samples 5000 \
    --pr-samples 2000 \
    --recon-metric-samples 2000 \
    --sample-steps 50 \
    --diffusion-steps 1000 \
    --sigma-enc 0.20 \
    --seed 0 \
    --checkpoint-every 5 \
    --amp \
    --resume

================================================================================
SRUL CIFAR-10 experiment
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/pilot/seed_0
Methods: ['gaussian_fm', 'chord', 'rfm', 'srul', 'latent_ddpm']
================================================================================
[AE] resumed from epoch 20

--------------------------------------------------------------------------------
Training prior: gaussian_fm
[gaussian_fm] resumed from epoch 30

--------------------------------------------------------------------------------
Training prior: chord
[chord] resumed from epoch 30

--------------------------------------------------------------------------------
Training prior: rfm
[rfm] resumed from epoch 30

--------------------------------------------------------------------------------
Training prior: srul
[srul] resumed from epoch 30

--------------------------------------------------------------------------------
Training prior: latent_ddpm
[latent_ddpm] resumed from epoch 30
Extracting real ResNet-18 features for feature precision/recall...

--------------------------------------------------------------------------------
Sampling and evaluating: gaussian_fm
Computing FID/KID...
Downloading: "https://github.com/toshas/torch-fidelity/releases/download/v0.2.0/weights-inception-2015-12-05-6726825d.pth" to /root/.cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth
100% 91.2M/91.2M [00:00<00:00, 104MB/s]
/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Computing ResNet feature precision/recall...
{
  "method": "gaussian_fm",
  "seed": 0,
  "final_mean_norm": 1.0442423820495605,
  "final_std_norm": 0.11784430593252182,
  "mean_abs_final_norm_error": 0.09441660344600677,
  "min_mean_path_norm": 1.0431050062179565,
  "mean_abs_path_norm_error": 4.894783010669783,
  "mean_raw_radial_fraction": 0.9316970694065094,
  "final_projection_for_decoder": true,
  "fid": 157.24595642089844,
  "kid_mean": 0.15764208137989044,
  "kid_std": 0.0017725307261571288,
  "metric_samples": 5000.0,
  "feature_precision": 0.867,
  "feature_recall": 0.0,
  "pr_samples": 2000.0,
  "pr_nearest_k": 5.0
}

--------------------------------------------------------------------------------
Sampling and evaluating: chord
Computing FID/KID...
Computing ResNet feature precision/recall...
{
  "method": "chord",
  "seed": 0,
  "final_mean_norm": 0.9799857139587402,
  "final_std_norm": 0.04866379499435425,
  "mean_abs_final_norm_error": 0.04202798753976822,
  "min_mean_path_norm": 0.7195263504981995,
  "mean_abs_path_norm_error": 0.17919831533058017,
  "mean_raw_radial_fraction": 0.4760581136867404,
  "final_projection_for_decoder": true,
  "fid": 156.0867156982422,
  "kid_mean": 0.15233945846557617,
  "kid_std": 0.0019256878877058625,
  "metric_samples": 5000.0,
  "feature_precision": 0.8895,
  "feature_recall": 0.0,
  "pr_samples": 2000.0,
  "pr_nearest_k": 5.0
}

--------------------------------------------------------------------------------
Sampling and evaluating: rfm
Computing FID/KID...
Computing ResNet feature precision/recall...
{
  "method": "rfm",
  "seed": 0,
  "final_mean_norm": 1.0,
  "final_std_norm": 2.2015610667835972e-08,
  "mean_abs_final_norm_error": 5.9604645663569045e-09,
  "min_mean_path_norm": 1.0,
  "mean_abs_path_norm_error": 0.0,
  "mean_raw_radial_fraction": 0.08203410310670733,
  "final_projection_for_decoder": false,
  "fid": 151.93246459960938,
  "kid_mean": 0.15036383271217346,
  "kid_std": 0.001031372812576592,
  "metric_samples": 5000.0,
  "feature_precision": 0.877,
  "feature_recall": 0.0,
  "pr_samples": 2000.0,
  "pr_nearest_k": 5.0
}

--------------------------------------------------------------------------------
Sampling and evaluating: srul
Computing FID/KID...
Computing ResNet feature precision/recall...
{
  "method": "srul",
  "seed": 0,
  "final_mean_norm": 1.0,
  "final_std_norm": 2.0563499347758807e-08,
  "mean_abs_final_norm_error": 5.4001807470172025e-09,
  "min_mean_path_norm": 1.0,
  "mean_abs_path_norm_error": 0.0,
  "mean_raw_radial_fraction": 0.08953906117007136,
  "final_projection_for_decoder": false,
  "fid": 152.94749450683594,
  "kid_mean": 0.14930739998817444,
  "kid_std": 0.0011890572495758533,
  "metric_samples": 5000.0,
  "feature_precision": 0.8965,
  "feature_recall": 0.0,
  "pr_samples": 2000.0,
  "pr_nearest_k": 5.0
}

--------------------------------------------------------------------------------
Sampling and evaluating: latent_ddpm
Computing FID/KID...
Computing ResNet feature precision/recall...
{
  "method": "latent_ddpm",
  "seed": 0,
  "final_mean_norm": 1.0,
  "final_std_norm": 3.997912401132453e-08,
  "mean_abs_final_norm_error": 2.2375584052269915e-08,
  "min_mean_path_norm": 1.0,
  "mean_abs_path_norm_error": 6.340772747993469,
  "mean_raw_radial_fraction": NaN,
  "final_projection_for_decoder": true,
  "fid": 218.6880645751953,
  "kid_mean": 0.19424043595790863,
  "kid_std": 0.002340256003662944,
  "metric_samples": 5000.0,
  "feature_precision": 0.947,
  "feature_recall": 0.0,
  "pr_samples": 2000.0,
  "pr_nearest_k": 5.0
}

Experiment complete.
Results: /content/drive/MyDrive/SRUL_CIFAR10/pilot/seed_0
Main files:
 - generation_metrics.csv
 - geometry_metrics.csv
 - reconstruction_metrics.json
 - figures/
 - samples/

In [7]:
!python /content/srul_cifar_next_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_CIFAR10/pilot" \
    --methods chord rfm srul \
    --train-samples 20000 \
    --test-samples 10000 \
    --ae-epochs 20 \
    --prior-epochs 100 \
    --latent-dim 128 \
    --base-channels 64 \
    --prior-width 512 \
    --prior-depth 4 \
    --time-dim 128 \
    --batch-size 256 \
    --num-workers 2 \
    --metric-samples 10000 \
    --pr-samples 5000 \
    --recon-metric-samples 2000 \
    --sample-steps 100 \
    --diffusion-steps 1000 \
    --sigma-enc 0.20 \
    --checkpoint-every 5 \
    --amp \
    --resume

================================================================================
SRUL CIFAR-10 experiment
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/pilot/seed_0
Methods: ['chord', 'rfm', 'srul']
================================================================================
[AE] resumed from epoch 20

--------------------------------------------------------------------------------
Training prior: chord
[chord] resumed from epoch 30
[chord] 031/100 loss=0.00986 path_norm=0.8118
[chord] 032/100 loss=0.00984 path_norm=0.8118
[chord] 033/100 loss=0.00987 path_norm=0.8118
[chord] 034/100 loss=0.00985 path_norm=0.8106
[chord] 035/100 loss=0.00983 path_norm=0.8110
[chord] 036/100 loss=0.00984 path_norm=0.8117
[chord] 037/100 loss=0.00984 path_norm=0.8113
[chord] 038/100 loss=0.00981 path_norm=0.8116
[chord] 039/100 loss=0.00982 path_norm=0.8104
[chord] 040/100 loss=0.00980 path_norm=0.8113
[chord] 041/100 loss=0.00978 path_norm=0.8121
[chord] 042/100 loss=0.00982 path_norm=0.8109
[chord] 043/100 loss=0.00979 path_norm=0.8107
[chord] 044/100 loss=0.00980 path_norm=0.8115
[chord] 045/100 loss=0.00980 path_norm=0.8110
[chord] 046/100 loss=0.00979 path_norm=0.8121
[chord] 047/100 loss=0.00977 path_norm=0.8119
[chord] 048/100 loss=0.00977 path_norm=0.8108
[chord] 049/100 loss=0.00976 path_norm=0.8113
[chord] 050/100 loss=0.00976 path_norm=0.8111
[chord] 051/100 loss=0.00975 path_norm=0.8121
[chord] 052/100 loss=0.00976 path_norm=0.8112
[chord] 053/100 loss=0.00976 path_norm=0.8106
[chord] 054/100 loss=0.00972 path_norm=0.8123
[chord] 055/100 loss=0.00972 path_norm=0.8126
[chord] 056/100 loss=0.00972 path_norm=0.8122
[chord] 057/100 loss=0.00973 path_norm=0.8130
[chord] 058/100 loss=0.00973 path_norm=0.8111
[chord] 059/100 loss=0.00973 path_norm=0.8116
[chord] 060/100 loss=0.00970 path_norm=0.8119
[chord] 061/100 loss=0.00971 path_norm=0.8111
[chord] 062/100 loss=0.00973 path_norm=0.8117
[chord] 063/100 loss=0.00971 path_norm=0.8117
[chord] 064/100 loss=0.00970 path_norm=0.8125
[chord] 065/100 loss=0.00970 path_norm=0.8120
[chord] 066/100 loss=0.00970 path_norm=0.8121
[chord] 067/100 loss=0.00969 path_norm=0.8116
[chord] 068/100 loss=0.00969 path_norm=0.8105
[chord] 069/100 loss=0.00968 path_norm=0.8115
[chord] 070/100 loss=0.00970 path_norm=0.8114
[chord] 071/100 loss=0.00967 path_norm=0.8112
[chord] 072/100 loss=0.00967 path_norm=0.8110
[chord] 073/100 loss=0.00968 path_norm=0.8107
[chord] 074/100 loss=0.00967 path_norm=0.8114
[chord] 075/100 loss=0.00966 path_norm=0.8127
[chord] 076/100 loss=0.00967 path_norm=0.8109
[chord] 077/100 loss=0.00964 path_norm=0.8116
[chord] 078/100 loss=0.00967 path_norm=0.8110
[chord] 079/100 loss=0.00965 path_norm=0.8107
[chord] 080/100 loss=0.00967 path_norm=0.8110
[chord] 081/100 loss=0.00964 path_norm=0.8113
[chord] 082/100 loss=0.00963 path_norm=0.8107
[chord] 083/100 loss=0.00966 path_norm=0.8108
[chord] 084/100 loss=0.00966 path_norm=0.8106
[chord] 085/100 loss=0.00963 path_norm=0.8114
[chord] 086/100 loss=0.00961 path_norm=0.8119
[chord] 087/100 loss=0.00963 path_norm=0.8108
[chord] 088/100 loss=0.00963 path_norm=0.8113
[chord] 089/100 loss=0.00961 path_norm=0.8105
[chord] 090/100 loss=0.00961 path_norm=0.8110
[chord] 091/100 loss=0.00962 path_norm=0.8096
[chord] 092/100 loss=0.00960 path_norm=0.8122
[chord] 093/100 loss=0.00959 path_norm=0.8115
[chord] 094/100 loss=0.00961 path_norm=0.8098
[chord] 095/100 loss=0.00961 path_norm=0.8106
[chord] 096/100 loss=0.00959 path_norm=0.8119
[chord] 097/100 loss=0.00959 path_norm=0.8115
[chord] 098/100 loss=0.00960 path_norm=0.8113
[chord] 099/100 loss=0.00958 path_norm=0.8115
[chord] 100/100 loss=0.00960 path_norm=0.8114

--------------------------------------------------------------------------------
Training prior: rfm
[rfm] resumed from epoch 30
[rfm] 031/100 loss=0.01514 path_norm=1.0000
[rfm] 032/100 loss=0.01515 path_norm=1.0000
[rfm] 033/100 loss=0.01516 path_norm=1.0000
[rfm] 034/100 loss=0.01512 path_norm=1.0000
[rfm] 035/100 loss=0.01513 path_norm=1.0000
[rfm] 036/100 loss=0.01512 path_norm=1.0000
[rfm] 037/100 loss=0.01511 path_norm=1.0000
[rfm] 038/100 loss=0.01510 path_norm=1.0000
[rfm] 039/100 loss=0.01507 path_norm=1.0000
[rfm] 040/100 loss=0.01509 path_norm=1.0000
[rfm] 041/100 loss=0.01506 path_norm=1.0000
[rfm] 042/100 loss=0.01510 path_norm=1.0000
[rfm] 043/100 loss=0.01510 path_norm=1.0000
[rfm] 044/100 loss=0.01511 path_norm=1.0000
[rfm] 045/100 loss=0.01510 path_norm=1.0000
[rfm] 046/100 loss=0.01509 path_norm=1.0000
[rfm] 047/100 loss=0.01511 path_norm=1.0000
[rfm] 048/100 loss=0.01505 path_norm=1.0000
[rfm] 049/100 loss=0.01508 path_norm=1.0000
[rfm] 050/100 loss=0.01506 path_norm=1.0000
[rfm] 051/100 loss=0.01508 path_norm=1.0000
[rfm] 052/100 loss=0.01499 path_norm=1.0000
[rfm] 053/100 loss=0.01505 path_norm=1.0000
[rfm] 054/100 loss=0.01509 path_norm=1.0000
[rfm] 055/100 loss=0.01505 path_norm=1.0000
[rfm] 056/100 loss=0.01510 path_norm=1.0000
[rfm] 057/100 loss=0.01504 path_norm=1.0000
[rfm] 058/100 loss=0.01501 path_norm=1.0000
[rfm] 059/100 loss=0.01504 path_norm=1.0000
[rfm] 060/100 loss=0.01505 path_norm=1.0000
[rfm] 061/100 loss=0.01504 path_norm=1.0000
[rfm] 062/100 loss=0.01500 path_norm=1.0000
[rfm] 063/100 loss=0.01503 path_norm=1.0000
[rfm] 064/100 loss=0.01501 path_norm=1.0000
[rfm] 065/100 loss=0.01501 path_norm=1.0000
[rfm] 066/100 loss=0.01495 path_norm=1.0000
[rfm] 067/100 loss=0.01496 path_norm=1.0000
[rfm] 068/100 loss=0.01499 path_norm=1.0000
[rfm] 069/100 loss=0.01501 path_norm=1.0000
[rfm] 070/100 loss=0.01501 path_norm=1.0000
[rfm] 071/100 loss=0.01497 path_norm=1.0000
[rfm] 072/100 loss=0.01498 path_norm=1.0000
[rfm] 073/100 loss=0.01500 path_norm=1.0000
[rfm] 074/100 loss=0.01496 path_norm=1.0000
[rfm] 075/100 loss=0.01497 path_norm=1.0000
[rfm] 076/100 loss=0.01498 path_norm=1.0000
[rfm] 077/100 loss=0.01498 path_norm=1.0000
[rfm] 078/100 loss=0.01492 path_norm=1.0000
[rfm] 079/100 loss=0.01500 path_norm=1.0000
[rfm] 080/100 loss=0.01497 path_norm=1.0000
[rfm] 081/100 loss=0.01500 path_norm=1.0000
[rfm] 082/100 loss=0.01499 path_norm=1.0000
[rfm] 083/100 loss=0.01497 path_norm=1.0000
[rfm] 084/100 loss=0.01494 path_norm=1.0000
[rfm] 085/100 loss=0.01497 path_norm=1.0000
[rfm] 086/100 loss=0.01497 path_norm=1.0000
[rfm] 087/100 loss=0.01495 path_norm=1.0000
[rfm] 088/100 loss=0.01497 path_norm=1.0000
[rfm] 089/100 loss=0.01500 path_norm=1.0000
[rfm] 090/100 loss=0.01493 path_norm=1.0000
[rfm] 091/100 loss=0.01497 path_norm=1.0000
[rfm] 092/100 loss=0.01500 path_norm=1.0000
[rfm] 093/100 loss=0.01492 path_norm=1.0000
[rfm] 094/100 loss=0.01493 path_norm=1.0000
[rfm] 095/100 loss=0.01494 path_norm=1.0000
[rfm] 096/100 loss=0.01498 path_norm=1.0000
[rfm] 097/100 loss=0.01495 path_norm=1.0000
[rfm] 098/100 loss=0.01487 path_norm=1.0000
[rfm] 099/100 loss=0.01491 path_norm=1.0000
[rfm] 100/100 loss=0.01491 path_norm=1.0000

--------------------------------------------------------------------------------
Training prior: srul
[srul] resumed from epoch 30
[srul] 031/100 loss=0.01168 path_norm=1.0000
[srul] 032/100 loss=0.01166 path_norm=1.0000
[srul] 033/100 loss=0.01169 path_norm=1.0000
[srul] 034/100 loss=0.01164 path_norm=1.0000
[srul] 035/100 loss=0.01172 path_norm=1.0000
[srul] 036/100 loss=0.01163 path_norm=1.0000
[srul] 037/100 loss=0.01169 path_norm=1.0000
[srul] 038/100 loss=0.01171 path_norm=1.0000
[srul] 039/100 loss=0.01171 path_norm=1.0000
[srul] 040/100 loss=0.01163 path_norm=1.0000
[srul] 041/100 loss=0.01166 path_norm=1.0000
[srul] 042/100 loss=0.01162 path_norm=1.0000
[srul] 043/100 loss=0.01166 path_norm=1.0000
[srul] 044/100 loss=0.01164 path_norm=1.0000
[srul] 045/100 loss=0.01166 path_norm=1.0000
[srul] 046/100 loss=0.01167 path_norm=1.0000
[srul] 047/100 loss=0.01162 path_norm=1.0000
[srul] 048/100 loss=0.01161 path_norm=1.0000
[srul] 049/100 loss=0.01161 path_norm=1.0000
[srul] 050/100 loss=0.01160 path_norm=1.0000
[srul] 051/100 loss=0.01165 path_norm=1.0000
[srul] 052/100 loss=0.01159 path_norm=1.0000
[srul] 053/100 loss=0.01166 path_norm=1.0000
[srul] 054/100 loss=0.01162 path_norm=1.0000
[srul] 055/100 loss=0.01153 path_norm=1.0000
[srul] 056/100 loss=0.01158 path_norm=1.0000
[srul] 057/100 loss=0.01163 path_norm=1.0000
[srul] 058/100 loss=0.01160 path_norm=1.0000
[srul] 059/100 loss=0.01161 path_norm=1.0000
[srul] 060/100 loss=0.01158 path_norm=1.0000
[srul] 061/100 loss=0.01155 path_norm=1.0000
[srul] 062/100 loss=0.01161 path_norm=1.0000
[srul] 063/100 loss=0.01154 path_norm=1.0000
[srul] 064/100 loss=0.01157 path_norm=1.0000
[srul] 065/100 loss=0.01153 path_norm=1.0000
[srul] 066/100 loss=0.01157 path_norm=1.0000
[srul] 067/100 loss=0.01154 path_norm=1.0000
[srul] 068/100 loss=0.01155 path_norm=1.0000
[srul] 069/100 loss=0.01164 path_norm=1.0000
[srul] 070/100 loss=0.01162 path_norm=1.0000
[srul] 071/100 loss=0.01159 path_norm=1.0000
[srul] 072/100 loss=0.01154 path_norm=1.0000
[srul] 073/100 loss=0.01154 path_norm=1.0000
[srul] 074/100 loss=0.01159 path_norm=1.0000
[srul] 075/100 loss=0.01155 path_norm=1.0000
[srul] 076/100 loss=0.01157 path_norm=1.0000
[srul] 077/100 loss=0.01155 path_norm=1.0000
[srul] 078/100 loss=0.01151 path_norm=1.0000
[srul] 079/100 loss=0.01149 path_norm=1.0000
[srul] 080/100 loss=0.01154 path_norm=1.0000
[srul] 081/100 loss=0.01154 path_norm=1.0000
[srul] 082/100 loss=0.01153 path_norm=1.0000
[srul] 083/100 loss=0.01153 path_norm=1.0000
[srul] 084/100 loss=0.01151 path_norm=1.0000
[srul] 085/100 loss=0.01152 path_norm=1.0000
[srul] 086/100 loss=0.01151 path_norm=1.0000
[srul] 087/100 loss=0.01154 path_norm=1.0000
[srul] 088/100 loss=0.01149 path_norm=1.0000
[srul] 089/100 loss=0.01149 path_norm=1.0000
[srul] 090/100 loss=0.01151 path_norm=1.0000
[srul] 091/100 loss=0.01153 path_norm=1.0000
[srul] 092/100 loss=0.01150 path_norm=1.0000
[srul] 093/100 loss=0.01154 path_norm=1.0000
[srul] 094/100 loss=0.01151 path_norm=1.0000
[srul] 095/100 loss=0.01149 path_norm=1.0000
[srul] 096/100 loss=0.01154 path_norm=1.0000
[srul] 097/100 loss=0.01150 path_norm=1.0000
[srul] 098/100 loss=0.01151 path_norm=1.0000
[srul] 099/100 loss=0.01152 path_norm=1.0000
[srul] 100/100 loss=0.01153 path_norm=1.0000
Extracting real ResNet-18 features for feature precision/recall...

--------------------------------------------------------------------------------
Sampling and evaluating: chord
Computing FID/KID...
/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Computing ResNet feature precision/recall...
{
  "method": "chord",
  "seed": 0,
  "final_mean_norm": 0.9897668957710266,
  "final_std_norm": 0.027601636946201324,
  "mean_abs_final_norm_error": 0.023497849702835083,
  "min_mean_path_norm": 0.7165043950080872,
  "mean_abs_path_norm_error": 0.18188242215921382,
  "mean_raw_radial_fraction": 0.4896223378716968,
  "final_projection_for_decoder": true,
  "fid": 149.5916748046875,
  "kid_mean": 0.1508364975452423,
  "kid_std": 0.0020800146739929914,
  "metric_samples": 10000.0,
  "feature_precision": 0.8088,
  "feature_recall": 0.0,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0
}

--------------------------------------------------------------------------------
Sampling and evaluating: rfm
Computing FID/KID...
Computing ResNet feature precision/recall...
{
  "method": "rfm",
  "seed": 0,
  "final_mean_norm": 1.0,
  "final_std_norm": 2.1091331348088715e-08,
  "mean_abs_final_norm_error": 5.412101877766418e-09,
  "min_mean_path_norm": 1.0,
  "mean_abs_path_norm_error": 0.0,
  "mean_raw_radial_fraction": 0.09324148256331682,
  "final_projection_for_decoder": false,
  "fid": 145.27845764160156,
  "kid_mean": 0.14519158005714417,
  "kid_std": 0.002914740238338709,
  "metric_samples": 10000.0,
  "feature_precision": 0.8158,
  "feature_recall": 0.0,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0
}

--------------------------------------------------------------------------------
Sampling and evaluating: srul
Computing FID/KID...
Computing ResNet feature precision/recall...
{
  "method": "srul",
  "seed": 0,
  "final_mean_norm": 1.0,
  "final_std_norm": 1.9984117471949503e-08,
  "mean_abs_final_norm_error": 4.994869406971247e-09,
  "min_mean_path_norm": 1.0,
  "mean_abs_path_norm_error": 0.0,
  "mean_raw_radial_fraction": 0.08625570345669985,
  "final_projection_for_decoder": false,
  "fid": 145.79998779296875,
  "kid_mean": 0.14759564399719238,
  "kid_std": 0.0020684220362454653,
  "metric_samples": 10000.0,
  "feature_precision": 0.7936,
  "feature_recall": 0.0,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0
}

Experiment complete.
Results: /content/drive/MyDrive/SRUL_CIFAR10/pilot/seed_0
Main files:
 - generation_metrics.csv
 - geometry_metrics.csv
 - reconstruction_metrics.json
 - figures/
 - samples/

In [8]:
import sys
import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

sys.path.append("/content")
import srul_cifar_next_experiment as exp

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Lambda(lambda x: x * 2.0 - 1.0),
])

test_set = datasets.CIFAR10(
    root="/content/data",
    train=False,
    download=True,
    transform=transform,
)

loader = DataLoader(test_set, batch_size=256, shuffle=False)

images = []
for x, _ in loader:
    images.append(x)
images = torch.cat(images, dim=0)[:4000]

# The feature extractor expects uint8 images in [0,255].
images_uint8 = (
    ((images + 1.0) * 127.5)
    .clamp(0, 255)
    .to(torch.uint8)
)

features = exp.extract_resnet_features(
    images_uint8,
    device=device,
    batch_size=128,
)

real_a = features[:2000]
real_b = features[2000:4000]

sanity = exp.feature_precision_recall(
    real_features=real_a,
    fake_features=real_b,
    device=device,
    nearest_k=5,
    chunk_size=256,
)

print("Real-vs-real sanity check:", sanity)

Real-vs-real sanity check: {'feature_precision': 0.8125, 'feature_recall': 0.818, 'pr_samples': 2000.0, 'pr_nearest_k': 5.0}

In [9]:
!python /content/srul_cifar_next_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_CIFAR10/quality_v1" \
    --methods chord rfm srul \
    --train-samples 0 \
    --test-samples 10000 \
    --ae-epochs 50 \
    --prior-epochs 120 \
    --latent-dim 64 \
    --base-channels 96 \
    --prior-width 768 \
    --prior-depth 6 \
    --time-dim 128 \
    --batch-size 128 \
    --num-workers 2 \
    --ae-lr 2e-4 \
    --prior-lr 2e-4 \
    --metric-samples 10000 \
    --pr-samples 5000 \
    --recon-metric-samples 5000 \
    --sample-steps 100 \
    --sigma-enc 0.20 \
    --time-sampling logit_normal \
    --checkpoint-every 5 \
    --compute-lpips \
    --amp \
    --resume

================================================================================
SRUL CIFAR-10 experiment
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/quality_v1/seed_0
Methods: ['chord', 'rfm', 'srul']
================================================================================
[AE] 001/50 loss=0.5032 clean=0.2500 noisy=0.2518 lat=0.0287
[AE] 002/50 loss=0.3556 clean=0.1751 noisy=0.1794 lat=0.0232
[AE] 003/50 loss=0.3119 clean=0.1521 noisy=0.1586 lat=0.0230
[AE] 004/50 loss=0.2937 clean=0.1423 noisy=0.1502 lat=0.0241
[AE] 005/50 loss=0.2794 clean=0.1345 noisy=0.1437 lat=0.0252
[AE] 006/50 loss=0.2686 clean=0.1287 noisy=0.1387 lat=0.0248
[AE] 007/50 loss=0.2614 clean=0.1246 noisy=0.1354 lat=0.0254
[AE] 008/50 loss=0.2559 clean=0.1217 noisy=0.1330 lat=0.0248
[AE] 009/50 loss=0.2533 clean=0.1202 noisy=0.1319 lat=0.0243
[AE] 010/50 loss=0.2515 clean=0.1192 noisy=0.1311 lat=0.0240
[AE] 011/50 loss=0.2489 clean=0.1179 noisy=0.1299 lat=0.0236
[AE] 012/50 loss=0.2485 clean=0.1176 noisy=0.1297 lat=0.0237
[AE] 013/50 loss=0.2474 clean=0.1170 noisy=0.1293 lat=0.0236
[AE] 014/50 loss=0.2462 clean=0.1163 noisy=0.1287 lat=0.0234
[AE] 015/50 loss=0.2448 clean=0.1155 noisy=0.1281 lat=0.0233
[AE] 016/50 loss=0.2443 clean=0.1153 noisy=0.1279 lat=0.0233
[AE] 017/50 loss=0.2436 clean=0.1149 noisy=0.1275 lat=0.0232
[AE] 018/50 loss=0.2427 clean=0.1144 noisy=0.1272 lat=0.0231
[AE] 019/50 loss=0.2419 clean=0.1139 noisy=0.1268 lat=0.0231
[AE] 020/50 loss=0.2414 clean=0.1136 noisy=0.1266 lat=0.0231
[AE] 021/50 loss=0.2412 clean=0.1135 noisy=0.1265 lat=0.0231
[AE] 022/50 loss=0.2406 clean=0.1132 noisy=0.1262 lat=0.0230
[AE] 023/50 loss=0.2397 clean=0.1127 noisy=0.1259 lat=0.0230
[AE] 024/50 loss=0.2391 clean=0.1124 noisy=0.1256 lat=0.0229
[AE] 025/50 loss=0.2385 clean=0.1120 noisy=0.1254 lat=0.0229
[AE] 026/50 loss=0.2385 clean=0.1120 noisy=0.1253 lat=0.0230
[AE] 027/50 loss=0.2377 clean=0.1116 noisy=0.1250 lat=0.0229
[AE] 028/50 loss=0.2372 clean=0.1113 noisy=0.1248 lat=0.0228
[AE] 029/50 loss=0.2369 clean=0.1111 noisy=0.1246 lat=0.0229
[AE] 030/50 loss=0.2364 clean=0.1108 noisy=0.1244 lat=0.0228
[AE] 031/50 loss=0.2360 clean=0.1106 noisy=0.1242 lat=0.0228
[AE] 032/50 loss=0.2356 clean=0.1104 noisy=0.1241 lat=0.0229
[AE] 033/50 loss=0.2349 clean=0.1100 noisy=0.1238 lat=0.0228
[AE] 034/50 loss=0.2347 clean=0.1099 noisy=0.1237 lat=0.0228
[AE] 035/50 loss=0.2341 clean=0.1095 noisy=0.1234 lat=0.0228
[AE] 036/50 loss=0.2340 clean=0.1095 noisy=0.1234 lat=0.0229
[AE] 037/50 loss=0.2335 clean=0.1092 noisy=0.1232 lat=0.0228
[AE] 038/50 loss=0.2329 clean=0.1089 noisy=0.1229 lat=0.0228
[AE] 039/50 loss=0.2326 clean=0.1086 noisy=0.1228 lat=0.0228
[AE] 040/50 loss=0.2321 clean=0.1084 noisy=0.1226 lat=0.0228
[AE] 041/50 loss=0.2318 clean=0.1082 noisy=0.1225 lat=0.0228
[AE] 042/50 loss=0.2313 clean=0.1079 noisy=0.1222 lat=0.0228
[AE] 043/50 loss=0.2309 clean=0.1077 noisy=0.1221 lat=0.0228
[AE] 044/50 loss=0.2305 clean=0.1075 noisy=0.1219 lat=0.0228
[AE] 045/50 loss=0.2301 clean=0.1073 noisy=0.1217 lat=0.0229
[AE] 046/50 loss=0.2298 clean=0.1071 noisy=0.1216 lat=0.0229
[AE] 047/50 loss=0.2292 clean=0.1067 noisy=0.1213 lat=0.0229
[AE] 048/50 loss=0.2289 clean=0.1066 noisy=0.1212 lat=0.0229
[AE] 049/50 loss=0.2286 clean=0.1064 noisy=0.1210 lat=0.0229
[AE] 050/50 loss=0.2280 clean=0.1061 noisy=0.1208 lat=0.0229
[warning] lpips is not installed; LPIPS evaluation skipped.

--------------------------------------------------------------------------------
Training prior: chord
[chord] 001/120 loss=0.02825 path_norm=0.7629
[chord] 002/120 loss=0.02683 path_norm=0.7626
[chord] 003/120 loss=0.02633 path_norm=0.7628
[chord] 004/120 loss=0.02606 path_norm=0.7630
[chord] 005/120 loss=0.02584 path_norm=0.7634
[chord] 006/120 loss=0.02572 path_norm=0.7628
[chord] 007/120 loss=0.02566 path_norm=0.7622
[chord] 008/120 loss=0.02558 path_norm=0.7624
[chord] 009/120 loss=0.02546 path_norm=0.7630
[chord] 010/120 loss=0.02538 path_norm=0.7631
[chord] 011/120 loss=0.02534 path_norm=0.7630
[chord] 012/120 loss=0.02528 path_norm=0.7631
[chord] 013/120 loss=0.02527 path_norm=0.7628
[chord] 014/120 loss=0.02519 path_norm=0.7630
[chord] 015/120 loss=0.02515 path_norm=0.7631
[chord] 016/120 loss=0.02516 path_norm=0.7627
[chord] 017/120 loss=0.02513 path_norm=0.7625
[chord] 018/120 loss=0.02507 path_norm=0.7629
[chord] 019/120 loss=0.02504 path_norm=0.7625
[chord] 020/120 loss=0.02504 path_norm=0.7626
[chord] 021/120 loss=0.02499 path_norm=0.7626
[chord] 022/120 loss=0.02493 path_norm=0.7633
[chord] 023/120 loss=0.02494 path_norm=0.7628
[chord] 024/120 loss=0.02494 path_norm=0.7625
[chord] 025/120 loss=0.02487 path_norm=0.7631
[chord] 026/120 loss=0.02485 path_norm=0.7627
[chord] 027/120 loss=0.02485 path_norm=0.7627
[chord] 028/120 loss=0.02483 path_norm=0.7626
[chord] 029/120 loss=0.02477 path_norm=0.7634
[chord] 030/120 loss=0.02479 path_norm=0.7630
[chord] 031/120 loss=0.02477 path_norm=0.7630
[chord] 032/120 loss=0.02474 path_norm=0.7635
[chord] 033/120 loss=0.02474 path_norm=0.7629
[chord] 034/120 loss=0.02473 path_norm=0.7625
[chord] 035/120 loss=0.02470 path_norm=0.7630
[chord] 036/120 loss=0.02468 path_norm=0.7627
[chord] 037/120 loss=0.02468 path_norm=0.7627
[chord] 038/120 loss=0.02465 path_norm=0.7632
[chord] 039/120 loss=0.02465 path_norm=0.7632
[chord] 040/120 loss=0.02460 path_norm=0.7635
[chord] 041/120 loss=0.02467 path_norm=0.7622
[chord] 042/120 loss=0.02463 path_norm=0.7626
[chord] 043/120 loss=0.02458 path_norm=0.7633
[chord] 044/120 loss=0.02459 path_norm=0.7628
[chord] 045/120 loss=0.02458 path_norm=0.7631
[chord] 046/120 loss=0.02457 path_norm=0.7630
[chord] 047/120 loss=0.02453 path_norm=0.7633
[chord] 048/120 loss=0.02457 path_norm=0.7625
[chord] 049/120 loss=0.02453 path_norm=0.7633
[chord] 050/120 loss=0.02453 path_norm=0.7629
[chord] 051/120 loss=0.02453 path_norm=0.7629
[chord] 052/120 loss=0.02450 path_norm=0.7632
[chord] 053/120 loss=0.02449 path_norm=0.7631
[chord] 054/120 loss=0.02449 path_norm=0.7630
[chord] 055/120 loss=0.02449 path_norm=0.7632
[chord] 056/120 loss=0.02449 path_norm=0.7629
[chord] 057/120 loss=0.02445 path_norm=0.7634
[chord] 058/120 loss=0.02449 path_norm=0.7625
[chord] 059/120 loss=0.02443 path_norm=0.7636
[chord] 060/120 loss=0.02446 path_norm=0.7633
[chord] 061/120 loss=0.02447 path_norm=0.7626
[chord] 062/120 loss=0.02449 path_norm=0.7625
[chord] 063/120 loss=0.02447 path_norm=0.7622
[chord] 064/120 loss=0.02443 path_norm=0.7634
[chord] 065/120 loss=0.02442 path_norm=0.7627
[chord] 066/120 loss=0.02442 path_norm=0.7627
[chord] 067/120 loss=0.02437 path_norm=0.7636
[chord] 068/120 loss=0.02439 path_norm=0.7631
[chord] 069/120 loss=0.02442 path_norm=0.7624
[chord] 070/120 loss=0.02441 path_norm=0.7626
[chord] 071/120 loss=0.02441 path_norm=0.7625
[chord] 072/120 loss=0.02439 path_norm=0.7630
[chord] 073/120 loss=0.02439 path_norm=0.7626
[chord] 074/120 loss=0.02439 path_norm=0.7628
[chord] 075/120 loss=0.02438 path_norm=0.7628
[chord] 076/120 loss=0.02439 path_norm=0.7627
[chord] 077/120 loss=0.02439 path_norm=0.7627
[chord] 078/120 loss=0.02438 path_norm=0.7626
[chord] 079/120 loss=0.02437 path_norm=0.7630
[chord] 080/120 loss=0.02436 path_norm=0.7628
[chord] 081/120 loss=0.02436 path_norm=0.7629
[chord] 082/120 loss=0.02435 path_norm=0.7629
[chord] 083/120 loss=0.02434 path_norm=0.7630
[chord] 084/120 loss=0.02436 path_norm=0.7624
[chord] 085/120 loss=0.02435 path_norm=0.7624
[chord] 086/120 loss=0.02430 path_norm=0.7629
[chord] 087/120 loss=0.02429 path_norm=0.7630
[chord] 088/120 loss=0.02427 path_norm=0.7632
[chord] 089/120 loss=0.02431 path_norm=0.7630
[chord] 090/120 loss=0.02432 path_norm=0.7628
[chord] 091/120 loss=0.02428 path_norm=0.7631
[chord] 092/120 loss=0.02430 path_norm=0.7630
[chord] 093/120 loss=0.02431 path_norm=0.7626
[chord] 094/120 loss=0.02427 path_norm=0.7632
[chord] 095/120 loss=0.02428 path_norm=0.7630
[chord] 096/120 loss=0.02429 path_norm=0.7627
[chord] 097/120 loss=0.02420 path_norm=0.7642
[chord] 098/120 loss=0.02427 path_norm=0.7630
[chord] 099/120 loss=0.02427 path_norm=0.7626
[chord] 100/120 loss=0.02428 path_norm=0.7629
[chord] 101/120 loss=0.02423 path_norm=0.7630
[chord] 102/120 loss=0.02423 path_norm=0.7635
[chord] 103/120 loss=0.02423 path_norm=0.7631
[chord] 104/120 loss=0.02428 path_norm=0.7625
[chord] 105/120 loss=0.02426 path_norm=0.7625
[chord] 106/120 loss=0.02422 path_norm=0.7630
[chord] 107/120 loss=0.02423 path_norm=0.7634
[chord] 108/120 loss=0.02424 path_norm=0.7629
[chord] 109/120 loss=0.02423 path_norm=0.7628
[chord] 110/120 loss=0.02423 path_norm=0.7630
[chord] 111/120 loss=0.02422 path_norm=0.7632
[chord] 112/120 loss=0.02420 path_norm=0.7629
[chord] 113/120 loss=0.02423 path_norm=0.7633
[chord] 114/120 loss=0.02424 path_norm=0.7630
[chord] 115/120 loss=0.02422 path_norm=0.7631
[chord] 116/120 loss=0.02418 path_norm=0.7632
[chord] 117/120 loss=0.02422 path_norm=0.7626
[chord] 118/120 loss=0.02423 path_norm=0.7629
[chord] 119/120 loss=0.02418 path_norm=0.7629
[chord] 120/120 loss=0.02419 path_norm=0.7629

--------------------------------------------------------------------------------
Training prior: rfm
[rfm] 001/120 loss=0.03660 path_norm=1.0000
[rfm] 002/120 loss=0.03615 path_norm=1.0000
[rfm] 003/120 loss=0.03591 path_norm=1.0000
[rfm] 004/120 loss=0.03587 path_norm=1.0000
[rfm] 005/120 loss=0.03582 path_norm=1.0000
[rfm] 006/120 loss=0.03574 path_norm=1.0000
[rfm] 007/120 loss=0.03576 path_norm=1.0000
[rfm] 008/120 loss=0.03576 path_norm=1.0000
[rfm] 009/120 loss=0.03573 path_norm=1.0000
[rfm] 010/120 loss=0.03561 path_norm=1.0000
[rfm] 011/120 loss=0.03556 path_norm=1.0000
[rfm] 012/120 loss=0.03558 path_norm=1.0000
[rfm] 013/120 loss=0.03556 path_norm=1.0000
[rfm] 014/120 loss=0.03552 path_norm=1.0000
[rfm] 015/120 loss=0.03552 path_norm=1.0000
[rfm] 016/120 loss=0.03543 path_norm=1.0000
[rfm] 017/120 loss=0.03542 path_norm=1.0000
[rfm] 018/120 loss=0.03542 path_norm=1.0000
[rfm] 019/120 loss=0.03538 path_norm=1.0000
[rfm] 020/120 loss=0.03530 path_norm=1.0000
[rfm] 021/120 loss=0.03531 path_norm=1.0000
[rfm] 022/120 loss=0.03531 path_norm=1.0000
[rfm] 023/120 loss=0.03533 path_norm=1.0000
[rfm] 024/120 loss=0.03524 path_norm=1.0000
[rfm] 025/120 loss=0.03517 path_norm=1.0000
[rfm] 026/120 loss=0.03528 path_norm=1.0000
[rfm] 027/120 loss=0.03521 path_norm=1.0000
[rfm] 028/120 loss=0.03519 path_norm=1.0000
[rfm] 029/120 loss=0.03521 path_norm=1.0000
[rfm] 030/120 loss=0.03518 path_norm=1.0000
[rfm] 031/120 loss=0.03514 path_norm=1.0000
[rfm] 032/120 loss=0.03520 path_norm=1.0000
[rfm] 033/120 loss=0.03518 path_norm=1.0000
[rfm] 034/120 loss=0.03512 path_norm=1.0000
[rfm] 035/120 loss=0.03509 path_norm=1.0000
[rfm] 036/120 loss=0.03514 path_norm=1.0000
[rfm] 037/120 loss=0.03508 path_norm=1.0000
[rfm] 038/120 loss=0.03503 path_norm=1.0000
[rfm] 039/120 loss=0.03507 path_norm=1.0000
[rfm] 040/120 loss=0.03506 path_norm=1.0000
[rfm] 041/120 loss=0.03501 path_norm=1.0000
[rfm] 042/120 loss=0.03505 path_norm=1.0000
[rfm] 043/120 loss=0.03496 path_norm=1.0000
[rfm] 044/120 loss=0.03498 path_norm=1.0000
[rfm] 045/120 loss=0.03500 path_norm=1.0000
[rfm] 046/120 loss=0.03499 path_norm=1.0000
[rfm] 047/120 loss=0.03495 path_norm=1.0000
[rfm] 048/120 loss=0.03495 path_norm=1.0000
[rfm] 049/120 loss=0.03498 path_norm=1.0000
[rfm] 050/120 loss=0.03491 path_norm=1.0000
[rfm] 051/120 loss=0.03489 path_norm=1.0000
[rfm] 052/120 loss=0.03491 path_norm=1.0000
[rfm] 053/120 loss=0.03488 path_norm=1.0000
[rfm] 054/120 loss=0.03488 path_norm=1.0000
[rfm] 055/120 loss=0.03493 path_norm=1.0000
[rfm] 056/120 loss=0.03488 path_norm=1.0000
[rfm] 057/120 loss=0.03483 path_norm=1.0000
[rfm] 058/120 loss=0.03481 path_norm=1.0000
[rfm] 059/120 loss=0.03479 path_norm=1.0000
[rfm] 060/120 loss=0.03485 path_norm=1.0000
[rfm] 061/120 loss=0.03484 path_norm=1.0000
[rfm] 062/120 loss=0.03481 path_norm=1.0000
[rfm] 063/120 loss=0.03483 path_norm=1.0000
[rfm] 064/120 loss=0.03476 path_norm=1.0000
[rfm] 065/120 loss=0.03479 path_norm=1.0000
[rfm] 066/120 loss=0.03479 path_norm=1.0000
[rfm] 067/120 loss=0.03476 path_norm=1.0000
[rfm] 068/120 loss=0.03479 path_norm=1.0000
[rfm] 069/120 loss=0.03477 path_norm=1.0000
[rfm] 070/120 loss=0.03472 path_norm=1.0000
[rfm] 071/120 loss=0.03475 path_norm=1.0000
[rfm] 072/120 loss=0.03469 path_norm=1.0000
[rfm] 073/120 loss=0.03472 path_norm=1.0000
[rfm] 074/120 loss=0.03472 path_norm=1.0000
[rfm] 075/120 loss=0.03466 path_norm=1.0000
[rfm] 076/120 loss=0.03468 path_norm=1.0000
[rfm] 077/120 loss=0.03464 path_norm=1.0000
[rfm] 078/120 loss=0.03472 path_norm=1.0000
[rfm] 079/120 loss=0.03471 path_norm=1.0000
[rfm] 080/120 loss=0.03465 path_norm=1.0000
[rfm] 081/120 loss=0.03474 path_norm=1.0000
[rfm] 082/120 loss=0.03464 path_norm=1.0000
[rfm] 083/120 loss=0.03465 path_norm=1.0000
[rfm] 084/120 loss=0.03465 path_norm=1.0000
[rfm] 085/120 loss=0.03470 path_norm=1.0000
[rfm] 086/120 loss=0.03461 path_norm=1.0000
[rfm] 087/120 loss=0.03468 path_norm=1.0000
[rfm] 088/120 loss=0.03462 path_norm=1.0000
[rfm] 089/120 loss=0.03461 path_norm=1.0000
[rfm] 090/120 loss=0.03465 path_norm=1.0000
[rfm] 091/120 loss=0.03464 path_norm=1.0000
[rfm] 092/120 loss=0.03464 path_norm=1.0000
[rfm] 093/120 loss=0.03459 path_norm=1.0000
[rfm] 094/120 loss=0.03464 path_norm=1.0000
[rfm] 095/120 loss=0.03459 path_norm=1.0000
[rfm] 096/120 loss=0.03461 path_norm=1.0000
[rfm] 097/120 loss=0.03462 path_norm=1.0000
[rfm] 098/120 loss=0.03465 path_norm=1.0000
[rfm] 099/120 loss=0.03460 path_norm=1.0000
[rfm] 100/120 loss=0.03457 path_norm=1.0000
[rfm] 101/120 loss=0.03457 path_norm=1.0000
[rfm] 102/120 loss=0.03459 path_norm=1.0000
[rfm] 103/120 loss=0.03452 path_norm=1.0000
[rfm] 104/120 loss=0.03455 path_norm=1.0000
[rfm] 105/120 loss=0.03455 path_norm=1.0000
[rfm] 106/120 loss=0.03454 path_norm=1.0000
[rfm] 107/120 loss=0.03460 path_norm=1.0000
[rfm] 108/120 loss=0.03456 path_norm=1.0000
[rfm] 109/120 loss=0.03461 path_norm=1.0000
[rfm] 110/120 loss=0.03450 path_norm=1.0000
[rfm] 111/120 loss=0.03449 path_norm=1.0000
[rfm] 112/120 loss=0.03459 path_norm=1.0000
[rfm] 113/120 loss=0.03449 path_norm=1.0000
[rfm] 114/120 loss=0.03450 path_norm=1.0000
[rfm] 115/120 loss=0.03452 path_norm=1.0000
[rfm] 116/120 loss=0.03445 path_norm=1.0000
[rfm] 117/120 loss=0.03449 path_norm=1.0000
[rfm] 118/120 loss=0.03451 path_norm=1.0000
[rfm] 119/120 loss=0.03454 path_norm=1.0000
[rfm] 120/120 loss=0.03454 path_norm=1.0000

--------------------------------------------------------------------------------
Training prior: srul
[srul] 001/120 loss=0.02873 path_norm=1.0000
[srul] 002/120 loss=0.02831 path_norm=1.0000
[srul] 003/120 loss=0.02822 path_norm=1.0000
[srul] 004/120 loss=0.02817 path_norm=1.0000
[srul] 005/120 loss=0.02810 path_norm=1.0000
[srul] 006/120 loss=0.02807 path_norm=1.0000
[srul] 007/120 loss=0.02804 path_norm=1.0000
[srul] 008/120 loss=0.02804 path_norm=1.0000
[srul] 009/120 loss=0.02799 path_norm=1.0000
[srul] 010/120 loss=0.02796 path_norm=1.0000
[srul] 011/120 loss=0.02801 path_norm=1.0000
[srul] 012/120 loss=0.02795 path_norm=1.0000
[srul] 013/120 loss=0.02787 path_norm=1.0000
[srul] 014/120 loss=0.02789 path_norm=1.0000
[srul] 015/120 loss=0.02780 path_norm=1.0000
[srul] 016/120 loss=0.02784 path_norm=1.0000
[srul] 017/120 loss=0.02777 path_norm=1.0000
[srul] 018/120 loss=0.02780 path_norm=1.0000
[srul] 019/120 loss=0.02782 path_norm=1.0000
[srul] 020/120 loss=0.02774 path_norm=1.0000
[srul] 021/120 loss=0.02773 path_norm=1.0000
[srul] 022/120 loss=0.02773 path_norm=1.0000
[srul] 023/120 loss=0.02806 path_norm=1.0000
[srul] 024/120 loss=0.02786 path_norm=1.0000
[srul] 025/120 loss=0.02790 path_norm=1.0000
[srul] 026/120 loss=0.02792 path_norm=1.0000
[srul] 027/120 loss=0.02796 path_norm=1.0000
[srul] 028/120 loss=0.02790 path_norm=1.0000
[srul] 029/120 loss=0.02787 path_norm=1.0000
[srul] 030/120 loss=0.02775 path_norm=1.0000
[srul] 031/120 loss=0.02773 path_norm=1.0000
[srul] 032/120 loss=0.02774 path_norm=1.0000
[srul] 033/120 loss=0.02780 path_norm=1.0000
[srul] 034/120 loss=0.02772 path_norm=1.0000
[srul] 035/120 loss=0.02770 path_norm=1.0000
[srul] 036/120 loss=0.02767 path_norm=1.0000
[srul] 037/120 loss=0.02767 path_norm=1.0000
[srul] 038/120 loss=0.02769 path_norm=1.0000
[srul] 039/120 loss=0.02763 path_norm=1.0000
[srul] 040/120 loss=0.02764 path_norm=1.0000
[srul] 041/120 loss=0.02766 path_norm=1.0000
[srul] 042/120 loss=0.02766 path_norm=1.0000
[srul] 043/120 loss=0.02765 path_norm=1.0000
[srul] 044/120 loss=0.02764 path_norm=1.0000
[srul] 045/120 loss=0.02758 path_norm=1.0000
[srul] 046/120 loss=0.02762 path_norm=1.0000
[srul] 047/120 loss=0.02757 path_norm=1.0000
[srul] 048/120 loss=0.02757 path_norm=1.0000
[srul] 049/120 loss=0.02755 path_norm=1.0000
[srul] 050/120 loss=0.02759 path_norm=1.0000
[srul] 051/120 loss=0.02759 path_norm=1.0000
[srul] 052/120 loss=0.02758 path_norm=1.0000
[srul] 053/120 loss=0.02752 path_norm=1.0000
[srul] 054/120 loss=0.02750 path_norm=1.0000
[srul] 055/120 loss=0.02749 path_norm=1.0000
[srul] 056/120 loss=0.02753 path_norm=1.0000
[srul] 057/120 loss=0.02749 path_norm=1.0000
[srul] 058/120 loss=0.02749 path_norm=1.0000
[srul] 059/120 loss=0.02755 path_norm=1.0000
[srul] 060/120 loss=0.02746 path_norm=1.0000
[srul] 061/120 loss=0.02746 path_norm=1.0000
[srul] 062/120 loss=0.02748 path_norm=1.0000
[srul] 063/120 loss=0.02750 path_norm=1.0000
[srul] 064/120 loss=0.02751 path_norm=1.0000
[srul] 065/120 loss=0.02743 path_norm=1.0000
[srul] 066/120 loss=0.02747 path_norm=1.0000
[srul] 067/120 loss=0.02741 path_norm=1.0000
[srul] 068/120 loss=0.02742 path_norm=1.0000
[srul] 069/120 loss=0.02741 path_norm=1.0000
[srul] 070/120 loss=0.02747 path_norm=1.0000
[srul] 071/120 loss=0.02737 path_norm=1.0000
[srul] 072/120 loss=0.02742 path_norm=1.0000
[srul] 073/120 loss=0.02740 path_norm=1.0000
[srul] 074/120 loss=0.02735 path_norm=1.0000
[srul] 075/120 loss=0.02741 path_norm=1.0000
[srul] 076/120 loss=0.02732 path_norm=1.0000
[srul] 077/120 loss=0.02744 path_norm=1.0000
[srul] 078/120 loss=0.02734 path_norm=1.0000
[srul] 079/120 loss=0.02731 path_norm=1.0000
[srul] 080/120 loss=0.02736 path_norm=1.0000
[srul] 081/120 loss=0.02733 path_norm=1.0000
[srul] 082/120 loss=0.02735 path_norm=1.0000
[srul] 083/120 loss=0.02731 path_norm=1.0000
[srul] 084/120 loss=0.02732 path_norm=1.0000
[srul] 085/120 loss=0.02732 path_norm=1.0000
[srul] 086/120 loss=0.02736 path_norm=1.0000
[srul] 087/120 loss=0.02733 path_norm=1.0000
[srul] 088/120 loss=0.02728 path_norm=1.0000
[srul] 089/120 loss=0.02734 path_norm=1.0000
[srul] 090/120 loss=0.02732 path_norm=1.0000
[srul] 091/120 loss=0.02735 path_norm=1.0000
[srul] 092/120 loss=0.02733 path_norm=1.0000
[srul] 093/120 loss=0.02727 path_norm=1.0000
[srul] 094/120 loss=0.02738 path_norm=1.0000
[srul] 095/120 loss=0.02732 path_norm=1.0000
[srul] 096/120 loss=0.02738 path_norm=1.0000
[srul] 097/120 loss=0.02729 path_norm=1.0000
[srul] 098/120 loss=0.02728 path_norm=1.0000
[srul] 099/120 loss=0.02730 path_norm=1.0000
[srul] 100/120 loss=0.02727 path_norm=1.0000
[srul] 101/120 loss=0.02727 path_norm=1.0000
[srul] 102/120 loss=0.02730 path_norm=1.0000
[srul] 103/120 loss=0.02727 path_norm=1.0000
[srul] 104/120 loss=0.02732 path_norm=1.0000
[srul] 105/120 loss=0.02722 path_norm=1.0000
[srul] 106/120 loss=0.02723 path_norm=1.0000
[srul] 107/120 loss=0.02722 path_norm=1.0000
[srul] 108/120 loss=0.02727 path_norm=1.0000
[srul] 109/120 loss=0.02722 path_norm=1.0000
[srul] 110/120 loss=0.02721 path_norm=1.0000
[srul] 111/120 loss=0.02722 path_norm=1.0000
[srul] 112/120 loss=0.02725 path_norm=1.0000
[srul] 113/120 loss=0.02722 path_norm=1.0000
[srul] 114/120 loss=0.02722 path_norm=1.0000
[srul] 115/120 loss=0.02724 path_norm=1.0000
[srul] 116/120 loss=0.02724 path_norm=1.0000
[srul] 117/120 loss=0.02719 path_norm=1.0000
[srul] 118/120 loss=0.02721 path_norm=1.0000
[srul] 119/120 loss=0.02721 path_norm=1.0000
[srul] 120/120 loss=0.02718 path_norm=1.0000
Extracting real ResNet-18 features for feature precision/recall...


In [10]:
import json
import sys
from pathlib import Path

import torch

sys.path.append("/content")
import srul_cifar_next_experiment as exp


# ------------------------------------------------------------------
# Load configuration, data, and trained autoencoder
# ------------------------------------------------------------------

RUN_DIR = Path(
    "/content/drive/MyDrive/SRUL_CIFAR10/quality_v1/seed_0"
)

with open(RUN_DIR / "config.json", "r") as f:
    cfg = json.load(f)

device = exp.get_device()
print("Device:", device)

train_set, test_set = exp.make_datasets(
    name="cifar10",
    root="/content/data",
    train_samples=None,
    test_samples=None,
    seed=0,
)

_, test_loader = exp.make_loaders(
    train_set=train_set,
    test_set=test_set,
    batch_size=256,
    num_workers=2,
    device=device,
)


def load_state_dict_safely(path):
    obj = torch.load(path, map_location=device)
    # Supports both a final state_dict and a resumable checkpoint.
    return obj["model"] if isinstance(obj, dict) and "model" in obj else obj


ae = exp.SphericalAutoencoder(
    latent_dim=cfg["latent_dim"],
    base_channels=cfg["base_channels"],
).to(device)

ae.load_state_dict(
    load_state_dict_safely(
        RUN_DIR / "checkpoints" / "autoencoder_final.pt"
    )
)
ae.eval()

print("Autoencoder loaded.")

Device: cuda
Autoencoder loaded.

In [11]:
# ------------------------------------------------------------------
# Collect real images and their reconstructions
# ------------------------------------------------------------------

max_samples = 5000
real_images = []
reconstructed_images = []
count = 0

with torch.no_grad():
    for images, _ in test_loader:
        images = images.to(device)

        z = ae.encode(images)
        recon = ae.decode(z)

        remaining = max_samples - count
        images = images[:remaining]
        recon = recon[:remaining]

        real_images.append(exp.to_uint8(images).cpu())
        reconstructed_images.append(exp.to_uint8(recon).cpu())

        count += images.size(0)
        if count >= max_samples:
            break

real_uint8 = torch.cat(real_images, dim=0)
recon_uint8 = torch.cat(reconstructed_images, dim=0)

print("Collected:", real_uint8.shape[0], "images")

Collected: 5000 images

In [12]:
# ------------------------------------------------------------------
# Image-feature comparison: real vs reconstruction
# ------------------------------------------------------------------

real_features = exp.extract_resnet_features(
    real_uint8,
    device=device,
    batch_size=128,
)

recon_features = exp.extract_resnet_features(
    recon_uint8,
    device=device,
    batch_size=128,
)

reconstruction_pr = exp.feature_precision_recall(
    real_features=real_features,
    fake_features=recon_features,
    device=device,
    nearest_k=5,
    chunk_size=256,
)

reconstruction_fid_kid = exp.compute_fid_kid(
    real_uint8=real_uint8,
    fake_uint8=recon_uint8,
    device=device,
    batch_size=128,
)

print("Real vs reconstruction precision/recall:")
print(reconstruction_pr)

print("\nReal vs reconstruction FID/KID:")
print(reconstruction_fid_kid)

/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)

Real vs reconstruction precision/recall:
{'feature_precision': 0.8568, 'feature_recall': 0.0112, 'pr_samples': 5000.0, 'pr_nearest_k': 5.0}

Real vs reconstruction FID/KID:
{'fid': 116.21340942382812, 'kid_mean': 0.09969387203454971, 'kid_std': 0.0024736851919442415, 'metric_samples': 5000.0}

In [13]:
# ------------------------------------------------------------------
# Load the trained prior networks
# ------------------------------------------------------------------

def load_prior(method):
    field = exp.LatentVectorField(
        latent_dim=cfg["latent_dim"],
        width=cfg["prior_width"],
        depth=cfg["prior_depth"],
        time_dim=cfg["time_dim"],
    ).to(device)

    field.load_state_dict(
        load_state_dict_safely(
            RUN_DIR / "checkpoints" / f"{method}_final.pt"
        )
    )
    field.eval()
    return field


priors = {
    method: load_prior(method)
    for method in ["chord", "rfm", "srul"]
}

print("Prior checkpoints loaded.")

Prior checkpoints loaded.

In [14]:
# ------------------------------------------------------------------
# Encode real test images
# ------------------------------------------------------------------

max_samples = 5000
real_latents = []
count = 0

with torch.no_grad():
    for images, _ in test_loader:
        images = images.to(device)

        z = ae.encode(images)

        remaining = max_samples - count
        z = z[:remaining]

        real_latents.append(z.cpu())
        count += z.size(0)

        if count >= max_samples:
            break

real_latents = torch.cat(real_latents, dim=0)

print("Real latent shape:", real_latents.shape)
print(
    "Real latent norm:",
    real_latents.norm(dim=1).mean().item()
)

Real latent shape: torch.Size([5000, 64])
Real latent norm: 1.0

In [15]:
# ------------------------------------------------------------------
# Sample final latents from each flow prior
# ------------------------------------------------------------------

@torch.no_grad()
def sample_final_latents(
    method,
    field,
    num_samples=5000,
    steps=100,
    batch_size=256,
):
    all_latents = []

    for start in range(0, num_samples, batch_size):
        batch = min(batch_size, num_samples - start)

        z = exp.sample_uniform_sphere(
            batch,
            ae.latent_dim,
            device,
        )

        for index in range(steps, 0, -1):
            t = torch.full(
                (batch,),
                index / steps,
                device=device,
            )

            raw_velocity = field(z, t)
            dt = -1.0 / steps

            if method == "chord":
                z = z + dt * raw_velocity
            elif method in {"rfm", "srul"}:
                tangent_velocity = exp.tangent_projection(
                    z,
                    raw_velocity,
                )
                z = exp.exp_map_sphere(
                    z,
                    dt * tangent_velocity,
                )
            else:
                raise ValueError(method)

        # The decoder receives normalized chord latents in the experiment.
        if method == "chord":
            z = exp.normalize_to_sphere(z)

        all_latents.append(z.cpu())

    return torch.cat(all_latents, dim=0)


generated_latents = {
    method: sample_final_latents(
        method,
        priors[method],
        num_samples=5000,
        steps=100,
    )
    for method in ["chord", "rfm", "srul"]
}

In [16]:
# ------------------------------------------------------------------
# Latent-space precision and recall
# ------------------------------------------------------------------

latent_results = {}

for method, fake_latents in generated_latents.items():
    result = exp.feature_precision_recall(
        real_features=real_latents,
        fake_features=fake_latents,
        device=device,
        nearest_k=5,
        chunk_size=256,
    )

    latent_results[method] = result
    print(method, result)

chord {'feature_precision': 0.9074, 'feature_recall': 0.929, 'pr_samples': 5000.0, 'pr_nearest_k': 5.0}
rfm {'feature_precision': 0.9126, 'feature_recall': 0.92, 'pr_samples': 5000.0, 'pr_nearest_k': 5.0}
srul {'feature_precision': 0.9084, 'feature_recall': 0.9256, 'pr_samples': 5000.0, 'pr_nearest_k': 5.0}

In [17]:
import torch

num_samples = 5000
batch_size = 256

# -------------------------------------------------------------
# Sample directly from the uniform sphere, without any prior
# -------------------------------------------------------------
uniform_latents = exp.sample_uniform_sphere(
    num_samples,
    ae.latent_dim,
    device,
).cpu()

uniform_latent_pr = exp.feature_precision_recall(
    real_features=real_latents,
    fake_features=uniform_latents,
    device=device,
    nearest_k=5,
    chunk_size=256,
)

print("Real latent vs uniform sphere:")
print(uniform_latent_pr)

Real latent vs uniform sphere:
{'feature_precision': 0.3604, 'feature_recall': 0.9948, 'pr_samples': 5000.0, 'pr_nearest_k': 5.0}

In [18]:
uniform_images = []

with torch.no_grad():
    for start in range(0, num_samples, batch_size):
        z = uniform_latents[start:start + batch_size].to(device)
        x_hat = ae.decode(z)
        uniform_images.append(exp.to_uint8(x_hat).cpu())

uniform_images = torch.cat(uniform_images, dim=0)

In [19]:
uniform_features = exp.extract_resnet_features(
    uniform_images,
    device=device,
    batch_size=128,
)

uniform_image_pr = exp.feature_precision_recall(
    real_features=real_features,
    fake_features=uniform_features,
    device=device,
    nearest_k=5,
    chunk_size=256,
)

uniform_fid_kid = exp.compute_fid_kid(
    real_uint8=real_uint8[:num_samples],
    fake_uint8=uniform_images,
    device=device,
    batch_size=128,
)

print("Real image vs decoded uniform sphere:")
print(uniform_image_pr)
print(uniform_fid_kid)

Real image vs decoded uniform sphere:
{'feature_precision': 0.8422, 'feature_recall': 0.0004, 'pr_samples': 5000.0, 'pr_nearest_k': 5.0}
{'fid': 144.81491088867188, 'kid_mean': 0.16420041024684906, 'kid_std': 0.0011710621183738112, 'metric_samples': 5000.0}

In [20]:
def normalize_tokens(h: torch.Tensor, eps: float = 1e-8) -> torch.Tensor:
    """
    h: [batch, channels, height, width]

    Every spatial token is normalized across its channel dimension.
    """
    norm = h.pow(2).sum(dim=1, keepdim=True).sqrt()
    return h / norm.clamp_min(eps)

In [21]:
def tangent_projection_tokens(
    z: torch.Tensor,
    u: torch.Tensor,
) -> torch.Tensor:
    """
    z, u: [batch, channels, height, width]
    """
    radial_coefficient = (u * z).sum(dim=1, keepdim=True)
    return u - radial_coefficient * z

In [22]:
def exp_map_tokens(
    z: torch.Tensor,
    v: torch.Tensor,
    eps: float = 1e-8,
) -> torch.Tensor:
    """
    Applies the sphere exponential map independently to each token.
    """
    v_norm = v.pow(2).sum(dim=1, keepdim=True).sqrt()
    direction = v / v_norm.clamp_min(eps)

    mapped = (
        torch.cos(v_norm) * z
        + torch.sin(v_norm) * direction
    )

    return normalize_tokens(mapped)

In [3]:
!pip install lpips

Requirement already satisfied: lpips in /usr/local/lib/python3.12/dist-packages (0.1.4)
Requirement already satisfied: torch>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from lpips) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from lpips) (0.26.0+cu128)
Requirement already satisfied: numpy>=1.14.3 in /usr/local/lib/python3.12/dist-packages (from lpips) (2.0.2)
Requirement already satisfied: scipy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from lpips) (1.16.3)
Requirement already satisfied: tqdm>=4.28.1 in /usr/local/lib/python3.12/dist-packages (from lpips) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.90)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision>=0.2.1->lpips) (11.3.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=0.4.0->lpips) (1.5.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=0.4.0->lpips) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=0.4.0->lpips) (3.0.3)

In [25]:
!python /content/srul_cifar_spatial_tokens_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1" \
    --dataset cifar10 \
    --train-samples 0 \
    --test-samples 10000 \
    --ae-epochs 60 \
    --base-channels 96 \
    --latent-channels 32 \
    --batch-size 128 \
    --num-workers 2 \
    --sigma-enc 0.15 \
    --lambda-clean 1.0 \
    --lambda-noisy 0.5 \
    --lambda-edge 0.15 \
    --lambda-latent 0.05 \
    --lambda-lpips 0.10 \
    --recon-metric-samples 5000 \
    --pr-samples 5000 \
    --metric-batch-size 128 \
    --checkpoint-every 5 \
    --compute-lpips \
    --amp \
    --resume \
    --ae-only

================================================================================
SRUL spatial product-of-spheres CIFAR-10 experiment
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/seed_0
Latent: 32 x 4 x 4
Methods: ['chord', 'rfm', 'srul']
================================================================================
/content/srul_cifar_spatial_tokens_experiment.py:771: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=config.amp and device.type == "cuda")
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth
100% 233M/233M [00:01<00:00, 236MB/s]
Loading model from: /usr/local/lib/python3.12/dist-packages/lpips/weights/v0.1/alex.pth
[AE] 001/60 loss=0.4017 clean=0.2157 noisy=0.2166 edge=0.2312 latent=0.0302 lpips=0.4146
[AE] 002/60 loss=0.2538 clean=0.1313 noisy=0.1332 edge=0.2085 latent=0.0127 lpips=0.2398
[AE] 003/60 loss=0.1996 clean=0.1022 noisy=0.1053 edge=0.1848 latent=0.0169 lpips=0.1617
[AE] 004/60 loss=0.1632 clean=0.0830 noisy=0.0872 edge=0.1653 latent=0.0162 lpips=0.1101
[AE] 005/60 loss=0.1470 clean=0.0745 noisy=0.0792 edge=0.1538 latent=0.0159 lpips=0.0901
[AE] 006/60 loss=0.1363 clean=0.0690 noisy=0.0742 edge=0.1441 latent=0.0157 lpips=0.0783
[AE] 007/60 loss=0.1282 clean=0.0647 noisy=0.0704 edge=0.1373 latent=0.0151 lpips=0.0697
[AE] 008/60 loss=0.1199 clean=0.0603 noisy=0.0666 edge=0.1297 latent=0.0166 lpips=0.0609
[AE] 009/60 loss=0.1136 clean=0.0570 noisy=0.0639 edge=0.1228 latent=0.0172 lpips=0.0532
[AE] 010/60 loss=0.1061 clean=0.0530 noisy=0.0604 edge=0.1165 latent=0.0168 lpips=0.0463
[AE] 011/60 loss=0.1021 clean=0.0509 noisy=0.0586 edge=0.1117 latent=0.0175 lpips=0.0423
[AE] 012/60 loss=0.0962 clean=0.0477 noisy=0.0560 edge=0.1066 latent=0.0164 lpips=0.0371
[AE] 013/60 loss=0.0938 clean=0.0464 noisy=0.0549 edge=0.1038 latent=0.0170 lpips=0.0352
[AE] 014/60 loss=0.0918 clean=0.0455 noisy=0.0540 edge=0.1013 latent=0.0165 lpips=0.0335
[AE] 015/60 loss=0.0888 clean=0.0437 noisy=0.0526 edge=0.0990 latent=0.0154 lpips=0.0315
[AE] 016/60 loss=0.0876 clean=0.0431 noisy=0.0520 edge=0.0979 latent=0.0152 lpips=0.0307
[AE] 017/60 loss=0.0868 clean=0.0427 noisy=0.0516 edge=0.0969 latent=0.0152 lpips=0.0304
[AE] 018/60 loss=0.0863 clean=0.0424 noisy=0.0514 edge=0.0961 latent=0.0150 lpips=0.0296
[AE] 019/60 loss=0.0857 clean=0.0421 noisy=0.0512 edge=0.0955 latent=0.0150 lpips=0.0292
[AE] 020/60 loss=0.0837 clean=0.0409 noisy=0.0501 edge=0.0944 latent=0.0145 lpips=0.0284
[AE] 021/60 loss=0.0831 clean=0.0406 noisy=0.0499 edge=0.0936 latent=0.0143 lpips=0.0276
[AE] 022/60 loss=0.0825 clean=0.0403 noisy=0.0496 edge=0.0931 latent=0.0143 lpips=0.0274
[AE] 023/60 loss=0.0817 clean=0.0398 noisy=0.0492 edge=0.0926 latent=0.0143 lpips=0.0269
[AE] 024/60 loss=0.0816 clean=0.0398 noisy=0.0492 edge=0.0922 latent=0.0144 lpips=0.0269
[AE] 025/60 loss=0.0806 clean=0.0392 noisy=0.0487 edge=0.0915 latent=0.0142 lpips=0.0262
[AE] 026/60 loss=0.0798 clean=0.0388 noisy=0.0483 edge=0.0908 latent=0.0139 lpips=0.0255
[AE] 027/60 loss=0.0803 clean=0.0392 noisy=0.0486 edge=0.0907 latent=0.0141 lpips=0.0256
[AE] 028/60 loss=0.0790 clean=0.0383 noisy=0.0479 edge=0.0902 latent=0.0140 lpips=0.0251
[AE] 029/60 loss=0.0788 clean=0.0382 noisy=0.0478 edge=0.0897 latent=0.0139 lpips=0.0246
[AE] 030/60 loss=0.0785 clean=0.0381 noisy=0.0477 edge=0.0894 latent=0.0139 lpips=0.0244
[AE] 031/60 loss=0.0774 clean=0.0374 noisy=0.0471 edge=0.0890 latent=0.0139 lpips=0.0241
[AE] 032/60 loss=0.0779 clean=0.0378 noisy=0.0474 edge=0.0885 latent=0.0137 lpips=0.0236
[AE] 033/60 loss=0.0776 clean=0.0376 noisy=0.0473 edge=0.0884 latent=0.0138 lpips=0.0236
[AE] 034/60 loss=0.0771 clean=0.0374 noisy=0.0471 edge=0.0881 latent=0.0138 lpips=0.0234
[AE] 035/60 loss=0.0764 clean=0.0369 noisy=0.0467 edge=0.0877 latent=0.0137 lpips=0.0230
[AE] 036/60 loss=0.0763 clean=0.0369 noisy=0.0467 edge=0.0874 latent=0.0137 lpips=0.0227
[AE] 037/60 loss=0.0758 clean=0.0366 noisy=0.0464 edge=0.0871 latent=0.0137 lpips=0.0226
[AE] 038/60 loss=0.0760 clean=0.0368 noisy=0.0466 edge=0.0870 latent=0.0138 lpips=0.0226
[AE] 039/60 loss=0.0756 clean=0.0365 noisy=0.0464 edge=0.0867 latent=0.0137 lpips=0.0221
[AE] 040/60 loss=0.0751 clean=0.0362 noisy=0.0461 edge=0.0863 latent=0.0136 lpips=0.0218
[AE] 041/60 loss=0.0739 clean=0.0354 noisy=0.0455 edge=0.0860 latent=0.0135 lpips=0.0214
[AE] 042/60 loss=0.0745 clean=0.0359 noisy=0.0458 edge=0.0858 latent=0.0137 lpips=0.0216
[AE] 043/60 loss=0.0748 clean=0.0361 noisy=0.0460 edge=0.0857 latent=0.0137 lpips=0.0213
[AE] 044/60 loss=0.0734 clean=0.0352 noisy=0.0453 edge=0.0853 latent=0.0135 lpips=0.0208
[AE] 045/60 loss=0.0742 clean=0.0358 noisy=0.0457 edge=0.0851 latent=0.0136 lpips=0.0209
[AE] 046/60 loss=0.0736 clean=0.0354 noisy=0.0455 edge=0.0849 latent=0.0136 lpips=0.0206
[AE] 047/60 loss=0.0733 clean=0.0352 noisy=0.0453 edge=0.0847 latent=0.0136 lpips=0.0205
[AE] 048/60 loss=0.0731 clean=0.0351 noisy=0.0452 edge=0.0845 latent=0.0136 lpips=0.0202
[AE] 049/60 loss=0.0728 clean=0.0350 noisy=0.0451 edge=0.0841 latent=0.0135 lpips=0.0197
[AE] 050/60 loss=0.0725 clean=0.0347 noisy=0.0449 edge=0.0841 latent=0.0135 lpips=0.0199
[AE] 051/60 loss=0.0723 clean=0.0346 noisy=0.0448 edge=0.0839 latent=0.0136 lpips=0.0198
[AE] 052/60 loss=0.0728 clean=0.0350 noisy=0.0451 edge=0.0836 latent=0.0135 lpips=0.0194
[AE] 053/60 loss=0.0718 clean=0.0343 noisy=0.0446 edge=0.0833 latent=0.0135 lpips=0.0191
[AE] 054/60 loss=0.0717 clean=0.0343 noisy=0.0446 edge=0.0833 latent=0.0136 lpips=0.0193
[AE] 055/60 loss=0.0716 clean=0.0343 noisy=0.0445 edge=0.0831 latent=0.0135 lpips=0.0191
[AE] 056/60 loss=0.0723 clean=0.0348 noisy=0.0449 edge=0.0829 latent=0.0136 lpips=0.0189
[AE] 057/60 loss=0.0715 clean=0.0343 noisy=0.0446 edge=0.0829 latent=0.0136 lpips=0.0188
[AE] 058/60 loss=0.0707 clean=0.0338 noisy=0.0442 edge=0.0825 latent=0.0135 lpips=0.0185
[AE] 059/60 loss=0.0711 clean=0.0341 noisy=0.0444 edge=0.0823 latent=0.0135 lpips=0.0184
[AE] 060/60 loss=0.0713 clean=0.0342 noisy=0.0445 edge=0.0822 latent=0.0136 lpips=0.0185
/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Reconstruction metrics:
{
  "clean_mse": 0.002895622979849577,
  "clean_psnr": 31.40317976769029,
  "noisy_mse": 0.0043134987354278564,
  "noisy_psnr": 29.672303162745184,
  "num_samples": 5000.0,
  "clean_ssim": 0.9376798868179321,
  "noisy_ssim": 0.9058936238288879,
  "feature_precision": 0.996,
  "feature_recall": 0.9888,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "reconstruction_fid": 17.314653396606445,
  "reconstruction_kid_mean": 0.012342882342636585,
  "reconstruction_kid_std": 0.0008962858119048178,
  "reconstruction_metric_samples": 5000.0
}
Uniform product-of-spheres diagnostic:
{
  "method": "uniform_product_sphere",
  "feature_precision": 0.001,
  "feature_recall": 0.9918,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "image_feature_precision": 0.6348,
  "image_feature_recall": 0.0,
  "image_pr_samples": 5000.0,
  "image_pr_nearest_k": 5.0,
  "fid": 191.3546142578125,
  "kid_mean": 0.22671189904212952,
  "kid_std": 0.0018138847080990672,
  "metric_samples": 5000.0
}
/content/srul_cifar_spatial_tokens_experiment.py:1346: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  axes[1].legend()
AE-only run complete. Inspect reconstruction recall/FID before priors.

In [26]:
import json
from pathlib import Path

run = Path(
    "/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/seed_0"
)

with open(run / "reconstruction_metrics.json") as f:
    reconstruction = json.load(f)

with open(run / "uniform_baseline.json") as f:
    uniform = json.load(f)

print("Reconstruction:")
print(json.dumps(reconstruction, indent=2))

print("\nUniform product-of-spheres baseline:")
print(json.dumps(uniform, indent=2))

Reconstruction:
{
  "clean_mse": 0.002895622979849577,
  "clean_psnr": 31.40317976769029,
  "noisy_mse": 0.0043134987354278564,
  "noisy_psnr": 29.672303162745184,
  "num_samples": 5000.0,
  "clean_ssim": 0.9376798868179321,
  "noisy_ssim": 0.9058936238288879,
  "feature_precision": 0.996,
  "feature_recall": 0.9888,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "reconstruction_fid": 17.314653396606445,
  "reconstruction_kid_mean": 0.012342882342636585,
  "reconstruction_kid_std": 0.0008962858119048178,
  "reconstruction_metric_samples": 5000.0
}

Uniform product-of-spheres baseline:
{
  "method": "uniform_product_sphere",
  "feature_precision": 0.001,
  "feature_recall": 0.9918,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "image_feature_precision": 0.6348,
  "image_feature_recall": 0.0,
  "image_pr_samples": 5000.0,
  "image_pr_nearest_k": 5.0,
  "fid": 191.3546142578125,
  "kid_mean": 0.22671189904212952,
  "kid_std": 0.0018138847080990672,
  "metric_samples": 5000.0
}

In [27]:
!python /content/srul_cifar_spatial_tokens_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1" \
    --dataset cifar10 \
    --train-samples 0 \
    --test-samples 10000 \
    --ae-epochs 60 \
    --prior-epochs 120 \
    --base-channels 96 \
    --latent-channels 32 \
    --prior-width 256 \
    --prior-depth 6 \
    --time-dim 128 \
    --batch-size 128 \
    --num-workers 2 \
    --sigma-enc 0.15 \
    --time-sampling logit_normal \
    --lambda-clean 1.0 \
    --lambda-noisy 0.5 \
    --lambda-edge 0.15 \
    --lambda-latent 0.05 \
    --lambda-lpips 0.10 \
    --methods chord rfm srul \
    --sample-steps 100 \
    --metric-samples 10000 \
    --pr-samples 5000 \
    --recon-metric-samples 5000 \
    --metric-batch-size 128 \
    --pr-chunk-size 256 \
    --pr-nearest-k 5 \
    --checkpoint-every 5 \
    --compute-lpips \
    --amp \
    --resume

================================================================================
SRUL spatial product-of-spheres CIFAR-10 experiment
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/seed_0
Latent: 32 x 4 x 4
Methods: ['chord', 'rfm', 'srul']
================================================================================
/content/srul_cifar_spatial_tokens_experiment.py:771: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=config.amp and device.type == "cuda")
[AE] resumed from epoch 60
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /usr/local/lib/python3.12/dist-packages/lpips/weights/v0.1/alex.pth
/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Reconstruction metrics:
{
  "clean_mse": 0.0028956234455108643,
  "clean_psnr": 31.403179069277158,
  "noisy_mse": 0.004319922998547554,
  "noisy_psnr": 29.66583985625072,
  "num_samples": 5000.0,
  "clean_ssim": 0.9376800656318665,
  "noisy_ssim": 0.9057362079620361,
  "feature_precision": 0.996,
  "feature_recall": 0.9888,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "reconstruction_fid": 17.31235694885254,
  "reconstruction_kid_mean": 0.012319231405854225,
  "reconstruction_kid_std": 0.0005541648715734482,
  "reconstruction_metric_samples": 5000.0
}
Uniform product-of-spheres diagnostic:
{
  "method": "uniform_product_sphere",
  "feature_precision": 0.0008,
  "feature_recall": 0.9908,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "image_feature_precision": 0.6522,
  "image_feature_recall": 0.0,
  "image_pr_samples": 5000.0,
  "image_pr_nearest_k": 5.0,
  "fid": 191.2034454345703,
  "kid_mean": 0.22891536355018616,
  "kid_std": 0.001717191538773477,
  "metric_samples": 5000.0
}

--------------------------------------------------------------------------------
Training prior: chord
/content/srul_cifar_spatial_tokens_experiment.py:868: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=config.amp and device.type == "cuda")
[chord] 001/120 loss=0.05234 path_norm=0.7620 radial=0.2037
[chord] 002/120 loss=0.04792 path_norm=0.7622 radial=0.3080
[chord] 003/120 loss=0.04664 path_norm=0.7623 radial=0.3385
[chord] 004/120 loss=0.04586 path_norm=0.7622 radial=0.3558
[chord] 005/120 loss=0.04531 path_norm=0.7616 radial=0.3634
[chord] 006/120 loss=0.04485 path_norm=0.7620 radial=0.3727
[chord] 007/120 loss=0.04456 path_norm=0.7616 radial=0.3747
[chord] 008/120 loss=0.04421 path_norm=0.7620 radial=0.3798
[chord] 009/120 loss=0.04397 path_norm=0.7622 radial=0.3825
[chord] 010/120 loss=0.04375 path_norm=0.7621 radial=0.3844
[chord] 011/120 loss=0.04358 path_norm=0.7621 radial=0.3848
[chord] 012/120 loss=0.04341 path_norm=0.7617 radial=0.3832
[chord] 013/120 loss=0.04326 path_norm=0.7619 radial=0.3825
[chord] 014/120 loss=0.04312 path_norm=0.7623 radial=0.3846
[chord] 015/120 loss=0.04300 path_norm=0.7619 radial=0.3815
[chord] 016/120 loss=0.04287 path_norm=0.7623 radial=0.3833
[chord] 017/120 loss=0.04274 path_norm=0.7623 radial=0.3827
[chord] 018/120 loss=0.04269 path_norm=0.7618 radial=0.3805
[chord] 019/120 loss=0.04259 path_norm=0.7616 radial=0.3790
[chord] 020/120 loss=0.04253 path_norm=0.7618 radial=0.3799
[chord] 021/120 loss=0.04241 path_norm=0.7624 radial=0.3824
[chord] 022/120 loss=0.04236 path_norm=0.7625 radial=0.3829
[chord] 023/120 loss=0.04229 path_norm=0.7621 radial=0.3809
[chord] 024/120 loss=0.04225 path_norm=0.7618 radial=0.3781
[chord] 025/120 loss=0.04219 path_norm=0.7620 radial=0.3799
[chord] 026/120 loss=0.04213 path_norm=0.7620 radial=0.3792
[chord] 027/120 loss=0.04209 path_norm=0.7615 radial=0.3769
[chord] 028/120 loss=0.04200 path_norm=0.7623 radial=0.3798
[chord] 029/120 loss=0.04198 path_norm=0.7621 radial=0.3785
[chord] 030/120 loss=0.04191 path_norm=0.7622 radial=0.3792
[chord] 031/120 loss=0.04187 path_norm=0.7620 radial=0.3777
[chord] 032/120 loss=0.04183 path_norm=0.7620 radial=0.3775
[chord] 033/120 loss=0.04177 path_norm=0.7618 radial=0.3759
[chord] 034/120 loss=0.04174 path_norm=0.7622 radial=0.3782
[chord] 035/120 loss=0.04173 path_norm=0.7622 radial=0.3777
[chord] 036/120 loss=0.04169 path_norm=0.7616 radial=0.3752
[chord] 037/120 loss=0.04163 path_norm=0.7624 radial=0.3772
[chord] 038/120 loss=0.04160 path_norm=0.7619 radial=0.3760
[chord] 039/120 loss=0.04158 path_norm=0.7621 radial=0.3771
[chord] 040/120 loss=0.04152 path_norm=0.7621 radial=0.3761
[chord] 041/120 loss=0.04149 path_norm=0.7622 radial=0.3773
[chord] 042/120 loss=0.04148 path_norm=0.7621 radial=0.3754
[chord] 043/120 loss=0.04141 path_norm=0.7618 radial=0.3743
[chord] 044/120 loss=0.04142 path_norm=0.7617 radial=0.3743
[chord] 045/120 loss=0.04138 path_norm=0.7619 radial=0.3734
[chord] 046/120 loss=0.04134 path_norm=0.7623 radial=0.3766
[chord] 047/120 loss=0.04130 path_norm=0.7624 radial=0.3762
[chord] 048/120 loss=0.04132 path_norm=0.7624 radial=0.3760
[chord] 049/120 loss=0.04132 path_norm=0.7618 radial=0.3733
[chord] 050/120 loss=0.04122 path_norm=0.7623 radial=0.3749
[chord] 051/120 loss=0.04125 path_norm=0.7620 radial=0.3731
[chord] 052/120 loss=0.04121 path_norm=0.7619 radial=0.3725
[chord] 053/120 loss=0.04120 path_norm=0.7616 radial=0.3724
[chord] 054/120 loss=0.04120 path_norm=0.7616 radial=0.3728
[chord] 055/120 loss=0.04111 path_norm=0.7622 radial=0.3739
[chord] 056/120 loss=0.04110 path_norm=0.7621 radial=0.3734
[chord] 057/120 loss=0.04110 path_norm=0.7621 radial=0.3737
[chord] 058/120 loss=0.04109 path_norm=0.7621 radial=0.3732
[chord] 059/120 loss=0.04101 path_norm=0.7623 radial=0.3739
[chord] 060/120 loss=0.04102 path_norm=0.7622 radial=0.3728
[chord] 061/120 loss=0.04098 path_norm=0.7621 radial=0.3719
[chord] 062/120 loss=0.04100 path_norm=0.7620 radial=0.3725
[chord] 063/120 loss=0.04094 path_norm=0.7623 radial=0.3733
[chord] 064/120 loss=0.04093 path_norm=0.7623 radial=0.3723
[chord] 065/120 loss=0.04094 path_norm=0.7620 radial=0.3730
[chord] 066/120 loss=0.04093 path_norm=0.7624 radial=0.3735
[chord] 067/120 loss=0.04091 path_norm=0.7621 radial=0.3715
[chord] 068/120 loss=0.04086 path_norm=0.7623 radial=0.3724
[chord] 069/120 loss=0.04086 path_norm=0.7618 radial=0.3709
[chord] 070/120 loss=0.04085 path_norm=0.7621 radial=0.3702
[chord] 071/120 loss=0.04083 path_norm=0.7623 radial=0.3723
[chord] 072/120 loss=0.04083 path_norm=0.7618 radial=0.3706
[chord] 073/120 loss=0.04081 path_norm=0.7622 radial=0.3712
[chord] 074/120 loss=0.04082 path_norm=0.7619 radial=0.3696
[chord] 075/120 loss=0.04078 path_norm=0.7619 radial=0.3704
[chord] 076/120 loss=0.04072 path_norm=0.7622 radial=0.3711
[chord] 077/120 loss=0.04076 path_norm=0.7618 radial=0.3695
[chord] 078/120 loss=0.04076 path_norm=0.7618 radial=0.3698
[chord] 079/120 loss=0.04071 path_norm=0.7621 radial=0.3697
[chord] 080/120 loss=0.04074 path_norm=0.7619 radial=0.3697
[chord] 081/120 loss=0.04068 path_norm=0.7619 radial=0.3691
[chord] 082/120 loss=0.04067 path_norm=0.7622 radial=0.3707
[chord] 083/120 loss=0.04068 path_norm=0.7616 radial=0.3676
[chord] 084/120 loss=0.04066 path_norm=0.7620 radial=0.3696
[chord] 085/120 loss=0.04067 path_norm=0.7621 radial=0.3701
[chord] 086/120 loss=0.04061 path_norm=0.7623 radial=0.3701
[chord] 087/120 loss=0.04063 path_norm=0.7618 radial=0.3684
[chord] 088/120 loss=0.04064 path_norm=0.7620 radial=0.3695
[chord] 089/120 loss=0.04058 path_norm=0.7621 radial=0.3692
[chord] 090/120 loss=0.04058 path_norm=0.7618 radial=0.3686
[chord] 091/120 loss=0.04054 path_norm=0.7624 radial=0.3706
[chord] 092/120 loss=0.04055 path_norm=0.7620 radial=0.3683
[chord] 093/120 loss=0.04051 path_norm=0.7624 radial=0.3689
[chord] 094/120 loss=0.04055 path_norm=0.7619 radial=0.3685
[chord] 095/120 loss=0.04055 path_norm=0.7617 radial=0.3673
[chord] 096/120 loss=0.04051 path_norm=0.7623 radial=0.3700
[chord] 097/120 loss=0.04053 path_norm=0.7621 radial=0.3692
[chord] 098/120 loss=0.04050 path_norm=0.7622 radial=0.3691
[chord] 099/120 loss=0.04047 path_norm=0.7620 radial=0.3686
[chord] 100/120 loss=0.04048 path_norm=0.7621 radial=0.3684
[chord] 101/120 loss=0.04046 path_norm=0.7619 radial=0.3669
[chord] 102/120 loss=0.04041 path_norm=0.7625 radial=0.3698
[chord] 103/120 loss=0.04043 path_norm=0.7617 radial=0.3662
[chord] 104/120 loss=0.04039 path_norm=0.7625 radial=0.3695
[chord] 105/120 loss=0.04041 path_norm=0.7622 radial=0.3681
[chord] 106/120 loss=0.04041 path_norm=0.7621 radial=0.3677
[chord] 107/120 loss=0.04037 path_norm=0.7622 radial=0.3685
[chord] 108/120 loss=0.04037 path_norm=0.7621 radial=0.3675
[chord] 109/120 loss=0.04038 path_norm=0.7621 radial=0.3682
[chord] 110/120 loss=0.04038 path_norm=0.7621 radial=0.3683
[chord] 111/120 loss=0.04033 path_norm=0.7624 radial=0.3673
[chord] 112/120 loss=0.04035 path_norm=0.7625 radial=0.3689
[chord] 113/120 loss=0.04034 path_norm=0.7622 radial=0.3678
[chord] 114/120 loss=0.04035 path_norm=0.7616 radial=0.3656
[chord] 115/120 loss=0.04030 path_norm=0.7621 radial=0.3669
[chord] 116/120 loss=0.04031 path_norm=0.7622 radial=0.3673
[chord] 117/120 loss=0.04032 path_norm=0.7619 radial=0.3657
[chord] 118/120 loss=0.04029 path_norm=0.7624 radial=0.3675
[chord] 119/120 loss=0.04028 path_norm=0.7623 radial=0.3677
[chord] 120/120 loss=0.04028 path_norm=0.7620 radial=0.3659

--------------------------------------------------------------------------------
Training prior: rfm
[rfm] 001/120 loss=0.06643 path_norm=1.0000 radial=0.2471
[rfm] 002/120 loss=0.06391 path_norm=1.0000 radial=0.2964
[rfm] 003/120 loss=0.06327 path_norm=1.0000 radial=0.3056
[rfm] 004/120 loss=0.06285 path_norm=1.0000 radial=0.3100
[rfm] 005/120 loss=0.06245 path_norm=1.0000 radial=0.3146
[rfm] 006/120 loss=0.06224 path_norm=1.0000 radial=0.3170
[rfm] 007/120 loss=0.06196 path_norm=1.0000 radial=0.3218
[rfm] 008/120 loss=0.06180 path_norm=1.0000 radial=0.3242
[rfm] 009/120 loss=0.06160 path_norm=1.0000 radial=0.3272
[rfm] 010/120 loss=0.06148 path_norm=1.0000 radial=0.3292
[rfm] 011/120 loss=0.06126 path_norm=1.0000 radial=0.3319
[rfm] 012/120 loss=0.06106 path_norm=1.0000 radial=0.3352
[rfm] 013/120 loss=0.06101 path_norm=1.0000 radial=0.3370
[rfm] 014/120 loss=0.06093 path_norm=1.0000 radial=0.3385
[rfm] 015/120 loss=0.06081 path_norm=1.0000 radial=0.3424
[rfm] 016/120 loss=0.06062 path_norm=1.0000 radial=0.3428
[rfm] 017/120 loss=0.06054 path_norm=1.0000 radial=0.3457
[rfm] 018/120 loss=0.06045 path_norm=1.0000 radial=0.3482
[rfm] 019/120 loss=0.06036 path_norm=1.0000 radial=0.3497
[rfm] 020/120 loss=0.06033 path_norm=1.0000 radial=0.3524
[rfm] 021/120 loss=0.06015 path_norm=1.0000 radial=0.3543
[rfm] 022/120 loss=0.06008 path_norm=1.0000 radial=0.3561
[rfm] 023/120 loss=0.06003 path_norm=1.0000 radial=0.3564
[rfm] 024/120 loss=0.06001 path_norm=1.0000 radial=0.3586
[rfm] 025/120 loss=0.05986 path_norm=1.0000 radial=0.3604
[rfm] 026/120 loss=0.05980 path_norm=1.0000 radial=0.3623
[rfm] 027/120 loss=0.05981 path_norm=1.0000 radial=0.3644
[rfm] 028/120 loss=0.05972 path_norm=1.0000 radial=0.3662
[rfm] 029/120 loss=0.05961 path_norm=1.0000 radial=0.3671
[rfm] 030/120 loss=0.05964 path_norm=1.0000 radial=0.3685
[rfm] 031/120 loss=0.05958 path_norm=1.0000 radial=0.3701
[rfm] 032/120 loss=0.05946 path_norm=1.0000 radial=0.3712
[rfm] 033/120 loss=0.05948 path_norm=1.0000 radial=0.3742
[rfm] 034/120 loss=0.05940 path_norm=1.0000 radial=0.3751
[rfm] 035/120 loss=0.05930 path_norm=1.0000 radial=0.3753
[rfm] 036/120 loss=0.05925 path_norm=1.0000 radial=0.3769
[rfm] 037/120 loss=0.05924 path_norm=1.0000 radial=0.3798
[rfm] 038/120 loss=0.05915 path_norm=1.0000 radial=0.3795
[rfm] 039/120 loss=0.05918 path_norm=1.0000 radial=0.3820
[rfm] 040/120 loss=0.05907 path_norm=1.0000 radial=0.3816
[rfm] 041/120 loss=0.05910 path_norm=1.0000 radial=0.3826
[rfm] 042/120 loss=0.05906 path_norm=1.0000 radial=0.3843
[rfm] 043/120 loss=0.05900 path_norm=1.0000 radial=0.3853
[rfm] 044/120 loss=0.05891 path_norm=1.0000 radial=0.3864
[rfm] 045/120 loss=0.05892 path_norm=1.0000 radial=0.3890
[rfm] 046/120 loss=0.05879 path_norm=1.0000 radial=0.3900
[rfm] 047/120 loss=0.05881 path_norm=1.0000 radial=0.3891
[rfm] 048/120 loss=0.05874 path_norm=1.0000 radial=0.3900
[rfm] 049/120 loss=0.05878 path_norm=1.0000 radial=0.3917
[rfm] 050/120 loss=0.05872 path_norm=1.0000 radial=0.3915
[rfm] 051/120 loss=0.05870 path_norm=1.0000 radial=0.3928
[rfm] 052/120 loss=0.05874 path_norm=1.0000 radial=0.3940
[rfm] 053/120 loss=0.05868 path_norm=1.0000 radial=0.3955
[rfm] 054/120 loss=0.05859 path_norm=1.0000 radial=0.3973
[rfm] 055/120 loss=0.05856 path_norm=1.0000 radial=0.3958
[rfm] 056/120 loss=0.05862 path_norm=1.0000 radial=0.3981
[rfm] 057/120 loss=0.05853 path_norm=1.0000 radial=0.3975
[rfm] 058/120 loss=0.05850 path_norm=1.0000 radial=0.3985
[rfm] 059/120 loss=0.05847 path_norm=1.0000 radial=0.3985
[rfm] 060/120 loss=0.05845 path_norm=1.0000 radial=0.3999
[rfm] 061/120 loss=0.05845 path_norm=1.0000 radial=0.4012
[rfm] 062/120 loss=0.05836 path_norm=1.0000 radial=0.4017
[rfm] 063/120 loss=0.05835 path_norm=1.0000 radial=0.4028
[rfm] 064/120 loss=0.05832 path_norm=1.0000 radial=0.4036
[rfm] 065/120 loss=0.05828 path_norm=1.0000 radial=0.4041
[rfm] 066/120 loss=0.05823 path_norm=1.0000 radial=0.4044
[rfm] 067/120 loss=0.05826 path_norm=1.0000 radial=0.4054
[rfm] 068/120 loss=0.05821 path_norm=1.0000 radial=0.4058
[rfm] 069/120 loss=0.05825 path_norm=1.0000 radial=0.4072
[rfm] 070/120 loss=0.05821 path_norm=1.0000 radial=0.4065
[rfm] 071/120 loss=0.05815 path_norm=1.0000 radial=0.4077
[rfm] 072/120 loss=0.05808 path_norm=1.0000 radial=0.4075
[rfm] 073/120 loss=0.05809 path_norm=1.0000 radial=0.4095
[rfm] 074/120 loss=0.05811 path_norm=1.0000 radial=0.4103
[rfm] 075/120 loss=0.05805 path_norm=1.0000 radial=0.4103
[rfm] 076/120 loss=0.05806 path_norm=1.0000 radial=0.4101
[rfm] 077/120 loss=0.05808 path_norm=1.0000 radial=0.4109
[rfm] 078/120 loss=0.05806 path_norm=1.0000 radial=0.4112
[rfm] 079/120 loss=0.05789 path_norm=1.0000 radial=0.4108
[rfm] 080/120 loss=0.05798 path_norm=1.0000 radial=0.4119
[rfm] 081/120 loss=0.05795 path_norm=1.0000 radial=0.4133
[rfm] 082/120 loss=0.05793 path_norm=1.0000 radial=0.4136
[rfm] 083/120 loss=0.05796 path_norm=1.0000 radial=0.4124
[rfm] 084/120 loss=0.05786 path_norm=1.0000 radial=0.4129
[rfm] 085/120 loss=0.05785 path_norm=1.0000 radial=0.4149
[rfm] 086/120 loss=0.05783 path_norm=1.0000 radial=0.4149
[rfm] 087/120 loss=0.05783 path_norm=1.0000 radial=0.4145
[rfm] 088/120 loss=0.05783 path_norm=1.0000 radial=0.4153
[rfm] 089/120 loss=0.05785 path_norm=1.0000 radial=0.4156
[rfm] 090/120 loss=0.05778 path_norm=1.0000 radial=0.4158
[rfm] 091/120 loss=0.05776 path_norm=1.0000 radial=0.4173
[rfm] 092/120 loss=0.05771 path_norm=1.0000 radial=0.4177
[rfm] 093/120 loss=0.05775 path_norm=1.0000 radial=0.4177
[rfm] 094/120 loss=0.05766 path_norm=1.0000 radial=0.4153
[rfm] 095/120 loss=0.05768 path_norm=1.0000 radial=0.4168
[rfm] 096/120 loss=0.05773 path_norm=1.0000 radial=0.4174
[rfm] 097/120 loss=0.05764 path_norm=1.0000 radial=0.4194
[rfm] 098/120 loss=0.05761 path_norm=1.0000 radial=0.4211
[rfm] 099/120 loss=0.05765 path_norm=1.0000 radial=0.4204
[rfm] 100/120 loss=0.05760 path_norm=1.0000 radial=0.4200
[rfm] 101/120 loss=0.05764 path_norm=1.0000 radial=0.4207
[rfm] 102/120 loss=0.05757 path_norm=1.0000 radial=0.4195
[rfm] 103/120 loss=0.05756 path_norm=1.0000 radial=0.4233
[rfm] 104/120 loss=0.05749 path_norm=1.0000 radial=0.4219
[rfm] 105/120 loss=0.05747 path_norm=1.0000 radial=0.4211
[rfm] 106/120 loss=0.05757 path_norm=1.0000 radial=0.4232
[rfm] 107/120 loss=0.05742 path_norm=1.0000 radial=0.4234
[rfm] 108/120 loss=0.05751 path_norm=1.0000 radial=0.4231
[rfm] 109/120 loss=0.05745 path_norm=1.0000 radial=0.4233
[rfm] 110/120 loss=0.05751 path_norm=1.0000 radial=0.4249
[rfm] 111/120 loss=0.05745 path_norm=1.0000 radial=0.4243
[rfm] 112/120 loss=0.05745 path_norm=1.0000 radial=0.4255
[rfm] 113/120 loss=0.05743 path_norm=1.0000 radial=0.4239
[rfm] 114/120 loss=0.05747 path_norm=1.0000 radial=0.4256
[rfm] 115/120 loss=0.05737 path_norm=1.0000 radial=0.4253
[rfm] 116/120 loss=0.05739 path_norm=1.0000 radial=0.4257
[rfm] 117/120 loss=0.05738 path_norm=1.0000 radial=0.4254
[rfm] 118/120 loss=0.05733 path_norm=1.0000 radial=0.4258
[rfm] 119/120 loss=0.05727 path_norm=1.0000 radial=0.4275
[rfm] 120/120 loss=0.05732 path_norm=1.0000 radial=0.4274

--------------------------------------------------------------------------------
Training prior: srul
[srul] 001/120 loss=0.05149 path_norm=1.0000 radial=0.2436
[srul] 002/120 loss=0.04967 path_norm=1.0000 radial=0.2926
[srul] 003/120 loss=0.04917 path_norm=1.0000 radial=0.3005
[srul] 004/120 loss=0.04881 path_norm=1.0000 radial=0.3069
[srul] 005/120 loss=0.04859 path_norm=1.0000 radial=0.3106
[srul] 006/120 loss=0.04832 path_norm=1.0000 radial=0.3136
[srul] 007/120 loss=0.04820 path_norm=1.0000 radial=0.3167
[srul] 008/120 loss=0.04794 path_norm=1.0000 radial=0.3212
[srul] 009/120 loss=0.04785 path_norm=1.0000 radial=0.3230
[srul] 010/120 loss=0.04775 path_norm=1.0000 radial=0.3244
[srul] 011/120 loss=0.04759 path_norm=1.0000 radial=0.3269
[srul] 012/120 loss=0.04749 path_norm=1.0000 radial=0.3302
[srul] 013/120 loss=0.04734 path_norm=1.0000 radial=0.3320
[srul] 014/120 loss=0.04740 path_norm=1.0000 radial=0.3332
[srul] 015/120 loss=0.04736 path_norm=1.0000 radial=0.3344
[srul] 016/120 loss=0.04721 path_norm=1.0000 radial=0.3371
[srul] 017/120 loss=0.04702 path_norm=1.0000 radial=0.3410
[srul] 018/120 loss=0.04699 path_norm=1.0000 radial=0.3426
[srul] 019/120 loss=0.04689 path_norm=1.0000 radial=0.3449
[srul] 020/120 loss=0.04691 path_norm=1.0000 radial=0.3455
[srul] 021/120 loss=0.04679 path_norm=1.0000 radial=0.3477
[srul] 022/120 loss=0.04677 path_norm=1.0000 radial=0.3486
[srul] 023/120 loss=0.04673 path_norm=1.0000 radial=0.3497
[srul] 024/120 loss=0.04659 path_norm=1.0000 radial=0.3524
[srul] 025/120 loss=0.04657 path_norm=1.0000 radial=0.3535
[srul] 026/120 loss=0.04660 path_norm=1.0000 radial=0.3537
[srul] 027/120 loss=0.04649 path_norm=1.0000 radial=0.3551
[srul] 028/120 loss=0.04650 path_norm=1.0000 radial=0.3566
[srul] 029/120 loss=0.04639 path_norm=1.0000 radial=0.3587
[srul] 030/120 loss=0.04643 path_norm=1.0000 radial=0.3591
[srul] 031/120 loss=0.04637 path_norm=1.0000 radial=0.3603
[srul] 032/120 loss=0.04629 path_norm=1.0000 radial=0.3618
[srul] 033/120 loss=0.04622 path_norm=1.0000 radial=0.3638
[srul] 034/120 loss=0.04623 path_norm=1.0000 radial=0.3643
[srul] 035/120 loss=0.04626 path_norm=1.0000 radial=0.3647
[srul] 036/120 loss=0.04614 path_norm=1.0000 radial=0.3665
[srul] 037/120 loss=0.04608 path_norm=1.0000 radial=0.3683
[srul] 038/120 loss=0.04607 path_norm=1.0000 radial=0.3687
[srul] 039/120 loss=0.04611 path_norm=1.0000 radial=0.3700
[srul] 040/120 loss=0.04597 path_norm=1.0000 radial=0.3713
[srul] 041/120 loss=0.04598 path_norm=1.0000 radial=0.3720
[srul] 042/120 loss=0.04603 path_norm=1.0000 radial=0.3726
[srul] 043/120 loss=0.04596 path_norm=1.0000 radial=0.3739

In [2]:
!pip install lpips

Collecting lpips
  Downloading lpips-0.1.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: torch>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from lpips) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from lpips) (0.26.0+cu128)
Requirement already satisfied: numpy>=1.14.3 in /usr/local/lib/python3.12/dist-packages (from lpips) (2.0.2)
Requirement already satisfied: scipy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from lpips) (1.16.3)
Requirement already satisfied: tqdm>=4.28.1 in /usr/local/lib/python3.12/dist-packages (from lpips) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=0.4.0->lpips) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=0.4.0->lpips) (12.8.90)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision>=0.2.1->lpips) (11.3.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=0.4.0->lpips) (1.5.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=0.4.0->lpips) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=0.4.0->lpips) (3.0.3)
Downloading lpips-0.1.4-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.8/53.8 kB 3.8 MB/s eta 0:00:00
Installing collected packages: lpips
Successfully installed lpips-0.1.4

In [4]:
!python /content/srul_cifar_spatial_tokens_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1" \
    --dataset cifar10 \
    --train-samples 0 \
    --test-samples 10000 \
    --seed 1 \
    --ae-epochs 60 \
    --prior-epochs 120 \
    --base-channels 96 \
    --latent-channels 32 \
    --prior-width 256 \
    --prior-depth 6 \
    --time-dim 128 \
    --batch-size 128 \
    --num-workers 2 \
    --ae-lr 2e-4 \
    --prior-lr 2e-4 \
    --sigma-enc 0.15 \
    --lambda-clean 1.0 \
    --lambda-noisy 0.5 \
    --lambda-edge 0.15 \
    --lambda-latent 0.05 \
    --lambda-lpips 0.10 \
    --time-sampling logit_normal \
    --methods chord rfm srul \
    --sample-steps 100 \
    --metric-samples 10000 \
    --pr-samples 5000 \
    --recon-metric-samples 5000 \
    --metric-batch-size 128 \
    --pr-chunk-size 256 \
    --pr-nearest-k 5 \
    --checkpoint-every 5 \
    --compute-lpips \
    --amp \
    --resume

================================================================================
SRUL spatial product-of-spheres CIFAR-10 experiment
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/seed_1
Latent: 32 x 4 x 4
Methods: ['chord', 'rfm', 'srul']
================================================================================
100% 170M/170M [39:00<00:00, 72.8kB/s]
/content/srul_cifar_spatial_tokens_experiment.py:771: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=config.amp and device.type == "cuda")
[AE] resumed from epoch 60
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth
100% 233M/233M [00:00<00:00, 312MB/s]
Loading model from: /usr/local/lib/python3.12/dist-packages/lpips/weights/v0.1/alex.pth
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100% 44.7M/44.7M [00:00<00:00, 260MB/s]
Downloading: "https://github.com/toshas/torch-fidelity/releases/download/v0.2.0/weights-inception-2015-12-05-6726825d.pth" to /root/.cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth
100% 91.2M/91.2M [00:00<00:00, 102MB/s]
/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Reconstruction metrics:
{
  "clean_mse": 0.0028423534240573645,
  "clean_psnr": 31.483819133118626,
  "noisy_mse": 0.004304546397179365,
  "noisy_psnr": 29.68132598042623,
  "num_samples": 5000.0,
  "clean_ssim": 0.943957507610321,
  "noisy_ssim": 0.9089902639389038,
  "feature_precision": 0.9938,
  "feature_recall": 0.982,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "reconstruction_fid": 18.80906867980957,
  "reconstruction_kid_mean": 0.015152263455092907,
  "reconstruction_kid_std": 0.0006410097703337669,
  "reconstruction_metric_samples": 5000.0
}
Uniform product-of-spheres diagnostic:
{
  "method": "uniform_product_sphere",
  "feature_precision": 0.001,
  "feature_recall": 0.9938,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "image_feature_precision": 0.7088,
  "image_feature_recall": 0.0,
  "image_pr_samples": 5000.0,
  "image_pr_nearest_k": 5.0,
  "fid": 202.322265625,
  "kid_mean": 0.23898939788341522,
  "kid_std": 0.002986690029501915,
  "metric_samples": 5000.0
}

--------------------------------------------------------------------------------
Training prior: chord
/content/srul_cifar_spatial_tokens_experiment.py:868: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=config.amp and device.type == "cuda")
[chord] 001/120 loss=0.05255 path_norm=0.7617 radial=0.1959
[chord] 002/120 loss=0.04791 path_norm=0.7621 radial=0.3037
[chord] 003/120 loss=0.04658 path_norm=0.7617 radial=0.3333
[chord] 004/120 loss=0.04579 path_norm=0.7619 radial=0.3513
[chord] 005/120 loss=0.04516 path_norm=0.7620 radial=0.3604
[chord] 006/120 loss=0.04474 path_norm=0.7619 radial=0.3657
[chord] 007/120 loss=0.04441 path_norm=0.7614 radial=0.3713
[chord] 008/120 loss=0.04408 path_norm=0.7621 radial=0.3763
[chord] 009/120 loss=0.04384 path_norm=0.7623 radial=0.3801
[chord] 010/120 loss=0.04362 path_norm=0.7621 radial=0.3795
[chord] 011/120 loss=0.04345 path_norm=0.7622 radial=0.3804
[chord] 012/120 loss=0.04325 path_norm=0.7624 radial=0.3805
[chord] 013/120 loss=0.04312 path_norm=0.7625 radial=0.3814
[chord] 014/120 loss=0.04299 path_norm=0.7619 radial=0.3785
[chord] 015/120 loss=0.04284 path_norm=0.7619 radial=0.3781
[chord] 016/120 loss=0.04271 path_norm=0.7623 radial=0.3801
[chord] 017/120 loss=0.04262 path_norm=0.7619 radial=0.3768
[chord] 018/120 loss=0.04253 path_norm=0.7620 radial=0.3771
[chord] 019/120 loss=0.04240 path_norm=0.7619 radial=0.3759
[chord] 020/120 loss=0.04231 path_norm=0.7624 radial=0.3792
[chord] 021/120 loss=0.04224 path_norm=0.7626 radial=0.3792
[chord] 022/120 loss=0.04216 path_norm=0.7621 radial=0.3769
[chord] 023/120 loss=0.04211 path_norm=0.7623 radial=0.3773
[chord] 024/120 loss=0.04203 path_norm=0.7621 radial=0.3767
[chord] 025/120 loss=0.04199 path_norm=0.7618 radial=0.3747
[chord] 026/120 loss=0.04195 path_norm=0.7620 radial=0.3757
[chord] 027/120 loss=0.04185 path_norm=0.7617 radial=0.3741
[chord] 028/120 loss=0.04179 path_norm=0.7623 radial=0.3759
[chord] 029/120 loss=0.04176 path_norm=0.7622 radial=0.3750
[chord] 030/120 loss=0.04174 path_norm=0.7618 radial=0.3735
[chord] 031/120 loss=0.04163 path_norm=0.7624 radial=0.3750
[chord] 032/120 loss=0.04166 path_norm=0.7614 radial=0.3713
[chord] 033/120 loss=0.04158 path_norm=0.7621 radial=0.3744
[chord] 034/120 loss=0.04158 path_norm=0.7618 radial=0.3716
[chord] 035/120 loss=0.04151 path_norm=0.7623 radial=0.3749
[chord] 036/120 loss=0.04145 path_norm=0.7622 radial=0.3739
[chord] 037/120 loss=0.04144 path_norm=0.7621 radial=0.3745
[chord] 038/120 loss=0.04142 path_norm=0.7615 radial=0.3705
[chord] 039/120 loss=0.04136 path_norm=0.7619 radial=0.3721
[chord] 040/120 loss=0.04135 path_norm=0.7616 radial=0.3695
[chord] 041/120 loss=0.04131 path_norm=0.7619 radial=0.3712
[chord] 042/120 loss=0.04129 path_norm=0.7617 radial=0.3710
[chord] 043/120 loss=0.04123 path_norm=0.7621 radial=0.3724
[chord] 044/120 loss=0.04123 path_norm=0.7616 radial=0.3700
[chord] 045/120 loss=0.04119 path_norm=0.7622 radial=0.3722
[chord] 046/120 loss=0.04114 path_norm=0.7622 radial=0.3713
[chord] 047/120 loss=0.04115 path_norm=0.7618 radial=0.3705
[chord] 048/120 loss=0.04112 path_norm=0.7618 radial=0.3701
[chord] 049/120 loss=0.04109 path_norm=0.7617 radial=0.3693
[chord] 050/120 loss=0.04103 path_norm=0.7623 radial=0.3716
[chord] 051/120 loss=0.04102 path_norm=0.7617 radial=0.3677
[chord] 052/120 loss=0.04102 path_norm=0.7621 radial=0.3706
[chord] 053/120 loss=0.04095 path_norm=0.7619 radial=0.3684
[chord] 054/120 loss=0.04095 path_norm=0.7620 radial=0.3690
[chord] 055/120 loss=0.04094 path_norm=0.7619 radial=0.3694
[chord] 056/120 loss=0.04089 path_norm=0.7624 radial=0.3702
[chord] 057/120 loss=0.04095 path_norm=0.7615 radial=0.3665
[chord] 058/120 loss=0.04087 path_norm=0.7618 radial=0.3685
[chord] 059/120 loss=0.04085 path_norm=0.7620 radial=0.3685
[chord] 060/120 loss=0.04086 path_norm=0.7619 radial=0.3688
[chord] 061/120 loss=0.04080 path_norm=0.7620 radial=0.3686
[chord] 062/120 loss=0.04080 path_norm=0.7621 radial=0.3688
[chord] 063/120 loss=0.04077 path_norm=0.7622 radial=0.3696
[chord] 064/120 loss=0.04076 path_norm=0.7620 radial=0.3688
[chord] 065/120 loss=0.04072 path_norm=0.7622 radial=0.3696
[chord] 066/120 loss=0.04074 path_norm=0.7618 radial=0.3684
[chord] 067/120 loss=0.04067 path_norm=0.7626 radial=0.3709
[chord] 068/120 loss=0.04068 path_norm=0.7622 radial=0.3683
[chord] 069/120 loss=0.04068 path_norm=0.7619 radial=0.3672
[chord] 070/120 loss=0.04064 path_norm=0.7618 radial=0.3658
[chord] 071/120 loss=0.04065 path_norm=0.7623 radial=0.3694
[chord] 072/120 loss=0.04063 path_norm=0.7622 radial=0.3685
[chord] 073/120 loss=0.04063 path_norm=0.7620 radial=0.3669
[chord] 074/120 loss=0.04059 path_norm=0.7621 radial=0.3667
[chord] 075/120 loss=0.04058 path_norm=0.7619 radial=0.3659
[chord] 076/120 loss=0.04059 path_norm=0.7617 radial=0.3667
[chord] 077/120 loss=0.04055 path_norm=0.7621 radial=0.3682
[chord] 078/120 loss=0.04054 path_norm=0.7621 radial=0.3668
[chord] 079/120 loss=0.04052 path_norm=0.7620 radial=0.3667
[chord] 080/120 loss=0.04050 path_norm=0.7623 radial=0.3684
[chord] 081/120 loss=0.04046 path_norm=0.7623 radial=0.3674
[chord] 082/120 loss=0.04044 path_norm=0.7621 radial=0.3666
[chord] 083/120 loss=0.04046 path_norm=0.7622 radial=0.3679
[chord] 084/120 loss=0.04043 path_norm=0.7621 radial=0.3657
[chord] 085/120 loss=0.04045 path_norm=0.7620 radial=0.3671
[chord] 086/120 loss=0.04039 path_norm=0.7621 radial=0.3656
[chord] 087/120 loss=0.04040 path_norm=0.7625 radial=0.3672
[chord] 088/120 loss=0.04040 path_norm=0.7619 radial=0.3653
[chord] 089/120 loss=0.04040 path_norm=0.7623 radial=0.3670
[chord] 090/120 loss=0.04036 path_norm=0.7621 radial=0.3648
[chord] 091/120 loss=0.04034 path_norm=0.7622 radial=0.3658
[chord] 092/120 loss=0.04031 path_norm=0.7623 radial=0.3663
[chord] 093/120 loss=0.04033 path_norm=0.7618 radial=0.3637
[chord] 094/120 loss=0.04035 path_norm=0.7620 radial=0.3656
[chord] 095/120 loss=0.04035 path_norm=0.7615 radial=0.3627
[chord] 096/120 loss=0.04031 path_norm=0.7627 radial=0.3688
[chord] 097/120 loss=0.04032 path_norm=0.7620 radial=0.3653
[chord] 098/120 loss=0.04029 path_norm=0.7619 radial=0.3638
[chord] 099/120 loss=0.04028 path_norm=0.7618 radial=0.3628
[chord] 100/120 loss=0.04027 path_norm=0.7617 radial=0.3625
[chord] 101/120 loss=0.04024 path_norm=0.7616 radial=0.3623
[chord] 102/120 loss=0.04026 path_norm=0.7620 radial=0.3651
[chord] 103/120 loss=0.04023 path_norm=0.7617 radial=0.3633
[chord] 104/120 loss=0.04021 path_norm=0.7624 radial=0.3658
[chord] 105/120 loss=0.04021 path_norm=0.7621 radial=0.3644
[chord] 106/120 loss=0.04020 path_norm=0.7618 radial=0.3633
[chord] 107/120 loss=0.04022 path_norm=0.7620 radial=0.3635
[chord] 108/120 loss=0.04016 path_norm=0.7622 radial=0.3647
[chord] 109/120 loss=0.04018 path_norm=0.7620 radial=0.3634
[chord] 110/120 loss=0.04015 path_norm=0.7621 radial=0.3640
[chord] 111/120 loss=0.04013 path_norm=0.7619 radial=0.3629
[chord] 112/120 loss=0.04017 path_norm=0.7620 radial=0.3638
[chord] 113/120 loss=0.04012 path_norm=0.7617 radial=0.3608
[chord] 114/120 loss=0.04011 path_norm=0.7622 radial=0.3640
[chord] 115/120 loss=0.04011 path_norm=0.7621 radial=0.3628
[chord] 116/120 loss=0.04009 path_norm=0.7625 radial=0.3652
[chord] 117/120 loss=0.04009 path_norm=0.7626 radial=0.3666
[chord] 118/120 loss=0.04011 path_norm=0.7618 radial=0.3607
[chord] 119/120 loss=0.04005 path_norm=0.7620 radial=0.3621
[chord] 120/120 loss=0.04007 path_norm=0.7622 radial=0.3632

--------------------------------------------------------------------------------
Training prior: rfm
[rfm] 001/120 loss=0.06645 path_norm=1.0000 radial=0.2448
[rfm] 002/120 loss=0.06384 path_norm=1.0000 radial=0.2949
[rfm] 003/120 loss=0.06309 path_norm=1.0000 radial=0.3065
[rfm] 004/120 loss=0.06263 path_norm=1.0000 radial=0.3133
[rfm] 005/120 loss=0.06218 path_norm=1.0000 radial=0.3169
[rfm] 006/120 loss=0.06198 path_norm=1.0000 radial=0.3237
[rfm] 007/120 loss=0.06171 path_norm=1.0000 radial=0.3302
[rfm] 008/120 loss=0.06145 path_norm=1.0000 radial=0.3327
[rfm] 009/120 loss=0.06128 path_norm=1.0000 radial=0.3361
[rfm] 010/120 loss=0.06113 path_norm=1.0000 radial=0.3413
[rfm] 011/120 loss=0.06089 path_norm=1.0000 radial=0.3450
[rfm] 012/120 loss=0.06081 path_norm=1.0000 radial=0.3503
[rfm] 013/120 loss=0.06062 path_norm=1.0000 radial=0.3533
[rfm] 014/120 loss=0.06049 path_norm=1.0000 radial=0.3560
[rfm] 015/120 loss=0.06038 path_norm=1.0000 radial=0.3591
[rfm] 016/120 loss=0.06027 path_norm=1.0000 radial=0.3617
[rfm] 017/120 loss=0.06009 path_norm=1.0000 radial=0.3642
[rfm] 018/120 loss=0.05997 path_norm=1.0000 radial=0.3681
[rfm] 019/120 loss=0.06002 path_norm=1.0000 radial=0.3707
[rfm] 020/120 loss=0.05986 path_norm=1.0000 radial=0.3753
[rfm] 021/120 loss=0.05981 path_norm=1.0000 radial=0.3766
[rfm] 022/120 loss=0.05970 path_norm=1.0000 radial=0.3790
[rfm] 023/120 loss=0.05959 path_norm=1.0000 radial=0.3792
[rfm] 024/120 loss=0.05952 path_norm=1.0000 radial=0.3827
[rfm] 025/120 loss=0.05948 path_norm=1.0000 radial=0.3836
[rfm] 026/120 loss=0.05940 path_norm=1.0000 radial=0.3861
[rfm] 027/120 loss=0.05934 path_norm=1.0000 radial=0.3878
[rfm] 028/120 loss=0.05927 path_norm=1.0000 radial=0.3906
[rfm] 029/120 loss=0.05918 path_norm=1.0000 radial=0.3916
[rfm] 030/120 loss=0.05915 path_norm=1.0000 radial=0.3934
[rfm] 031/120 loss=0.05909 path_norm=1.0000 radial=0.3930
[rfm] 032/120 loss=0.05907 path_norm=1.0000 radial=0.3970
[rfm] 033/120 loss=0.05898 path_norm=1.0000 radial=0.3971
[rfm] 034/120 loss=0.05897 path_norm=1.0000 radial=0.3990
[rfm] 035/120 loss=0.05889 path_norm=1.0000 radial=0.3996
[rfm] 036/120 loss=0.05884 path_norm=1.0000 radial=0.3998
[rfm] 037/120 loss=0.05882 path_norm=1.0000 radial=0.4020
[rfm] 038/120 loss=0.05868 path_norm=1.0000 radial=0.4010
[rfm] 039/120 loss=0.05874 path_norm=1.0000 radial=0.4033
[rfm] 040/120 loss=0.05865 path_norm=1.0000 radial=0.4048
[rfm] 041/120 loss=0.05864 path_norm=1.0000 radial=0.4053
[rfm] 042/120 loss=0.05859 path_norm=1.0000 radial=0.4077
[rfm] 043/120 loss=0.05849 path_norm=1.0000 radial=0.4091
[rfm] 044/120 loss=0.05856 path_norm=1.0000 radial=0.4090
[rfm] 045/120 loss=0.05848 path_norm=1.0000 radial=0.4097
[rfm] 046/120 loss=0.05841 path_norm=1.0000 radial=0.4105
[rfm] 047/120 loss=0.05840 path_norm=1.0000 radial=0.4113
[rfm] 048/120 loss=0.05843 path_norm=1.0000 radial=0.4130
[rfm] 049/120 loss=0.05826 path_norm=1.0000 radial=0.4133
[rfm] 050/120 loss=0.05827 path_norm=1.0000 radial=0.4131
[rfm] 051/120 loss=0.05832 path_norm=1.0000 radial=0.4142
[rfm] 052/120 loss=0.05833 path_norm=1.0000 radial=0.4154
[rfm] 053/120 loss=0.05831 path_norm=1.0000 radial=0.4166
[rfm] 054/120 loss=0.05814 path_norm=1.0000 radial=0.4155
[rfm] 055/120 loss=0.05815 path_norm=1.0000 radial=0.4161
[rfm] 056/120 loss=0.05808 path_norm=1.0000 radial=0.4185
[rfm] 057/120 loss=0.05809 path_norm=1.0000 radial=0.4180
[rfm] 058/120 loss=0.05808 path_norm=1.0000 radial=0.4182
[rfm] 059/120 loss=0.05803 path_norm=1.0000 radial=0.4190
[rfm] 060/120 loss=0.05797 path_norm=1.0000 radial=0.4219
[rfm] 061/120 loss=0.05803 path_norm=1.0000 radial=0.4212
[rfm] 062/120 loss=0.05799 path_norm=1.0000 radial=0.4217
[rfm] 063/120 loss=0.05799 path_norm=1.0000 radial=0.4230
[rfm] 064/120 loss=0.05794 path_norm=1.0000 radial=0.4212
[rfm] 065/120 loss=0.05783 path_norm=1.0000 radial=0.4244
[rfm] 066/120 loss=0.05786 path_norm=1.0000 radial=0.4225
[rfm] 067/120 loss=0.05784 path_norm=1.0000 radial=0.4232
[rfm] 068/120 loss=0.05779 path_norm=1.0000 radial=0.4247
[rfm] 069/120 loss=0.05777 path_norm=1.0000 radial=0.4254
[rfm] 070/120 loss=0.05773 path_norm=1.0000 radial=0.4230
[rfm] 071/120 loss=0.05769 path_norm=1.0000 radial=0.4263
[rfm] 072/120 loss=0.05772 path_norm=1.0000 radial=0.4265
[rfm] 073/120 loss=0.05772 path_norm=1.0000 radial=0.4276
[rfm] 074/120 loss=0.05766 path_norm=1.0000 radial=0.4279
[rfm] 075/120 loss=0.05768 path_norm=1.0000 radial=0.4276
[rfm] 076/120 loss=0.05759 path_norm=1.0000 radial=0.4283
[rfm] 077/120 loss=0.05768 path_norm=1.0000 radial=0.4294
[rfm] 078/120 loss=0.05761 path_norm=1.0000 radial=0.4287
[rfm] 079/120 loss=0.05758 path_norm=1.0000 radial=0.4289
[rfm] 080/120 loss=0.05762 path_norm=1.0000 radial=0.4301
[rfm] 081/120 loss=0.05749 path_norm=1.0000 radial=0.4306
[rfm] 082/120 loss=0.05748 path_norm=1.0000 radial=0.4316
[rfm] 083/120 loss=0.05751 path_norm=1.0000 radial=0.4302
[rfm] 084/120 loss=0.05747 path_norm=1.0000 radial=0.4321
[rfm] 085/120 loss=0.05746 path_norm=1.0000 radial=0.4317
[rfm] 086/120 loss=0.05744 path_norm=1.0000 radial=0.4343
[rfm] 087/120 loss=0.05740 path_norm=1.0000 radial=0.4333
[rfm] 088/120 loss=0.05745 path_norm=1.0000 radial=0.4328
[rfm] 089/120 loss=0.05738 path_norm=1.0000 radial=0.4339
[rfm] 090/120 loss=0.05736 path_norm=1.0000 radial=0.4337
[rfm] 091/120 loss=0.05740 path_norm=1.0000 radial=0.4337
[rfm] 092/120 loss=0.05729 path_norm=1.0000 radial=0.4352
[rfm] 093/120 loss=0.05733 path_norm=1.0000 radial=0.4364
[rfm] 094/120 loss=0.05723 path_norm=1.0000 radial=0.4345
[rfm] 095/120 loss=0.05728 path_norm=1.0000 radial=0.4378
[rfm] 096/120 loss=0.05730 path_norm=1.0000 radial=0.4361
[rfm] 097/120 loss=0.05724 path_norm=1.0000 radial=0.4349
[rfm] 098/120 loss=0.05720 path_norm=1.0000 radial=0.4370
[rfm] 099/120 loss=0.05719 path_norm=1.0000 radial=0.4381
[rfm] 100/120 loss=0.05722 path_norm=1.0000 radial=0.4385
[rfm] 101/120 loss=0.05716 path_norm=1.0000 radial=0.4372
[rfm] 102/120 loss=0.05721 path_norm=1.0000 radial=0.4381
[rfm] 103/120 loss=0.05720 path_norm=1.0000 radial=0.4382
[rfm] 104/120 loss=0.05708 path_norm=1.0000 radial=0.4400
[rfm] 105/120 loss=0.05706 path_norm=1.0000 radial=0.4404
[rfm] 106/120 loss=0.05707 path_norm=1.0000 radial=0.4399
[rfm] 107/120 loss=0.05705 path_norm=1.0000 radial=0.4398
[rfm] 108/120 loss=0.05701 path_norm=1.0000 radial=0.4394
[rfm] 109/120 loss=0.05711 path_norm=1.0000 radial=0.4389
[rfm] 110/120 loss=0.05702 path_norm=1.0000 radial=0.4405
[rfm] 111/120 loss=0.05704 path_norm=1.0000 radial=0.4409
[rfm] 112/120 loss=0.05705 path_norm=1.0000 radial=0.4414
[rfm] 113/120 loss=0.05697 path_norm=1.0000 radial=0.4417
[rfm] 114/120 loss=0.05701 path_norm=1.0000 radial=0.4410
[rfm] 115/120 loss=0.05696 path_norm=1.0000 radial=0.4424
[rfm] 116/120 loss=0.05692 path_norm=1.0000 radial=0.4443
[rfm] 117/120 loss=0.05687 path_norm=1.0000 radial=0.4415
[rfm] 118/120 loss=0.05692 path_norm=1.0000 radial=0.4433
[rfm] 119/120 loss=0.05690 path_norm=1.0000 radial=0.4420
[rfm] 120/120 loss=0.05688 path_norm=1.0000 radial=0.4422

--------------------------------------------------------------------------------
Training prior: srul
[srul] 001/120 loss=0.05178 path_norm=1.0000 radial=0.2390
[srul] 002/120 loss=0.04965 path_norm=1.0000 radial=0.2946
[srul] 003/120 loss=0.04904 path_norm=1.0000 radial=0.3062
[srul] 004/120 loss=0.04863 path_norm=1.0000 radial=0.3139
[srul] 005/120 loss=0.04833 path_norm=1.0000 radial=0.3199
[srul] 006/120 loss=0.04807 path_norm=1.0000 radial=0.3256
[srul] 007/120 loss=0.04793 path_norm=1.0000 radial=0.3292
[srul] 008/120 loss=0.04772 path_norm=1.0000 radial=0.3341
[srul] 009/120 loss=0.04758 path_norm=1.0000 radial=0.3396
[srul] 010/120 loss=0.04750 path_norm=1.0000 radial=0.3419
[srul] 011/120 loss=0.04733 path_norm=1.0000 radial=0.3463
[srul] 012/120 loss=0.04718 path_norm=1.0000 radial=0.3508
[srul] 013/120 loss=0.04716 path_norm=1.0000 radial=0.3515
[srul] 014/120 loss=0.04703 path_norm=1.0000 radial=0.3549
[srul] 015/120 loss=0.04693 path_norm=1.0000 radial=0.3580
[srul] 016/120 loss=0.04688 path_norm=1.0000 radial=0.3608
[srul] 017/120 loss=0.04675 path_norm=1.0000 radial=0.3656
[srul] 018/120 loss=0.04672 path_norm=1.0000 radial=0.3665
[srul] 019/120 loss=0.04665 path_norm=1.0000 radial=0.3683
[srul] 020/120 loss=0.04657 path_norm=1.0000 radial=0.3700
[srul] 021/120 loss=0.04648 path_norm=1.0000 radial=0.3740
[srul] 022/120 loss=0.04648 path_norm=1.0000 radial=0.3744
[srul] 023/120 loss=0.04639 path_norm=1.0000 radial=0.3774
[srul] 024/120 loss=0.04638 path_norm=1.0000 radial=0.3784
[srul] 025/120 loss=0.04633 path_norm=1.0000 radial=0.3807
[srul] 026/120 loss=0.04622 path_norm=1.0000 radial=0.3831
[srul] 027/120 loss=0.04610 path_norm=1.0000 radial=0.3842
[srul] 028/120 loss=0.04612 path_norm=1.0000 radial=0.3863
[srul] 029/120 loss=0.04607 path_norm=1.0000 radial=0.3874
[srul] 030/120 loss=0.04600 path_norm=1.0000 radial=0.3902
[srul] 031/120 loss=0.04604 path_norm=1.0000 radial=0.3904
[srul] 032/120 loss=0.04601 path_norm=1.0000 radial=0.3898
[srul] 033/120 loss=0.04598 path_norm=1.0000 radial=0.3917

In [5]:
!python /content/srul_cifar_spatial_tokens_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1" \
    --dataset cifar10 \
    --train-samples 0 \
    --test-samples 10000 \
    --seed 2 \
    --ae-epochs 60 \
    --prior-epochs 120 \
    --base-channels 96 \
    --latent-channels 32 \
    --prior-width 256 \
    --prior-depth 6 \
    --time-dim 128 \
    --batch-size 128 \
    --num-workers 2 \
    --ae-lr 2e-4 \
    --prior-lr 2e-4 \
    --sigma-enc 0.15 \
    --lambda-clean 1.0 \
    --lambda-noisy 0.5 \
    --lambda-edge 0.15 \
    --lambda-latent 0.05 \
    --lambda-lpips 0.10 \
    --time-sampling logit_normal \
    --methods chord rfm srul \
    --sample-steps 100 \
    --metric-samples 10000 \
    --pr-samples 5000 \
    --recon-metric-samples 5000 \
    --metric-batch-size 128 \
    --pr-chunk-size 256 \
    --pr-nearest-k 5 \
    --checkpoint-every 5 \
    --compute-lpips \
    --amp \
    --resume

================================================================================
SRUL spatial product-of-spheres CIFAR-10 experiment
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/seed_2
Latent: 32 x 4 x 4
Methods: ['chord', 'rfm', 'srul']
================================================================================
/content/srul_cifar_spatial_tokens_experiment.py:771: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=config.amp and device.type == "cuda")
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /usr/local/lib/python3.12/dist-packages/lpips/weights/v0.1/alex.pth
[AE] 001/60 loss=0.3851 clean=0.2049 noisy=0.2060 edge=0.2314 latent=0.0334 lpips=0.4083
[AE] 002/60 loss=0.2508 clean=0.1297 noisy=0.1317 edge=0.2086 latent=0.0138 lpips=0.2330
[AE] 003/60 loss=0.1968 clean=0.1007 noisy=0.1039 edge=0.1854 latent=0.0169 lpips=0.1543
[AE] 004/60 loss=0.1631 clean=0.0830 noisy=0.0871 edge=0.1652 latent=0.0165 lpips=0.1096
[AE] 005/60 loss=0.1484 clean=0.0754 noisy=0.0801 edge=0.1537 latent=0.0164 lpips=0.0905
[AE] 006/60 loss=0.1370 clean=0.0693 noisy=0.0746 edge=0.1448 latent=0.0159 lpips=0.0786
[AE] 007/60 loss=0.1287 clean=0.0650 noisy=0.0707 edge=0.1378 latent=0.0150 lpips=0.0698
[AE] 008/60 loss=0.1221 clean=0.0615 noisy=0.0677 edge=0.1317 latent=0.0162 lpips=0.0625
[AE] 009/60 loss=0.1152 clean=0.0580 noisy=0.0647 edge=0.1248 latent=0.0173 lpips=0.0539
[AE] 010/60 loss=0.1089 clean=0.0546 noisy=0.0618 edge=0.1187 latent=0.0177 lpips=0.0479
[AE] 011/60 loss=0.1036 clean=0.0518 noisy=0.0595 edge=0.1130 latent=0.0179 lpips=0.0417
[AE] 012/60 loss=0.0992 clean=0.0493 noisy=0.0575 edge=0.1089 latent=0.0179 lpips=0.0382
[AE] 013/60 loss=0.0956 clean=0.0475 noisy=0.0559 edge=0.1055 latent=0.0172 lpips=0.0348
[AE] 014/60 loss=0.0929 clean=0.0460 noisy=0.0547 edge=0.1030 latent=0.0169 lpips=0.0334
[AE] 015/60 loss=0.0907 clean=0.0447 noisy=0.0536 edge=0.1010 latent=0.0163 lpips=0.0321
[AE] 016/60 loss=0.0898 clean=0.0444 noisy=0.0532 edge=0.0998 latent=0.0160 lpips=0.0313
[AE] 017/60 loss=0.0875 clean=0.0430 noisy=0.0520 edge=0.0983 latent=0.0155 lpips=0.0302
[AE] 018/60 loss=0.0870 clean=0.0428 noisy=0.0518 edge=0.0974 latent=0.0154 lpips=0.0295
[AE] 019/60 loss=0.0866 clean=0.0426 noisy=0.0516 edge=0.0967 latent=0.0153 lpips=0.0290
[AE] 020/60 loss=0.0848 clean=0.0415 noisy=0.0507 edge=0.0956 latent=0.0148 lpips=0.0280
[AE] 021/60 loss=0.0841 clean=0.0412 noisy=0.0504 edge=0.0950 latent=0.0149 lpips=0.0278
[AE] 022/60 loss=0.0842 clean=0.0413 noisy=0.0504 edge=0.0946 latent=0.0150 lpips=0.0275
[AE] 023/60 loss=0.0826 clean=0.0403 noisy=0.0497 edge=0.0935 latent=0.0145 lpips=0.0265
[AE] 024/60 loss=0.0818 clean=0.0399 noisy=0.0493 edge=0.0929 latent=0.0145 lpips=0.0262
[AE] 025/60 loss=0.0819 clean=0.0400 noisy=0.0493 edge=0.0928 latent=0.0146 lpips=0.0262
[AE] 026/60 loss=0.0811 clean=0.0395 noisy=0.0489 edge=0.0921 latent=0.0145 lpips=0.0255
[AE] 027/60 loss=0.0805 clean=0.0391 noisy=0.0486 edge=0.0917 latent=0.0145 lpips=0.0254
[AE] 028/60 loss=0.0803 clean=0.0392 noisy=0.0486 edge=0.0910 latent=0.0142 lpips=0.0247
[AE] 029/60 loss=0.0795 clean=0.0386 noisy=0.0482 edge=0.0907 latent=0.0142 lpips=0.0245
[AE] 030/60 loss=0.0790 clean=0.0384 noisy=0.0480 edge=0.0903 latent=0.0142 lpips=0.0242
[AE] 031/60 loss=0.0784 clean=0.0380 noisy=0.0477 edge=0.0898 latent=0.0141 lpips=0.0238
[AE] 032/60 loss=0.0779 clean=0.0377 noisy=0.0474 edge=0.0893 latent=0.0140 lpips=0.0233
[AE] 033/60 loss=0.0776 clean=0.0375 noisy=0.0473 edge=0.0893 latent=0.0142 lpips=0.0235
[AE] 034/60 loss=0.0775 clean=0.0376 noisy=0.0473 edge=0.0888 latent=0.0140 lpips=0.0230
[AE] 035/60 loss=0.0771 clean=0.0373 noisy=0.0471 edge=0.0884 latent=0.0140 lpips=0.0227
[AE] 036/60 loss=0.0767 clean=0.0371 noisy=0.0469 edge=0.0882 latent=0.0140 lpips=0.0225
[AE] 037/60 loss=0.0765 clean=0.0370 noisy=0.0468 edge=0.0878 latent=0.0140 lpips=0.0222
[AE] 038/60 loss=0.0759 clean=0.0367 noisy=0.0466 edge=0.0875 latent=0.0139 lpips=0.0218
[AE] 039/60 loss=0.0752 clean=0.0362 noisy=0.0462 edge=0.0872 latent=0.0139 lpips=0.0216
[AE] 040/60 loss=0.0756 clean=0.0365 noisy=0.0464 edge=0.0867 latent=0.0137 lpips=0.0212
[AE] 041/60 loss=0.0754 clean=0.0364 noisy=0.0463 edge=0.0869 latent=0.0140 lpips=0.0215
[AE] 042/60 loss=0.0747 clean=0.0360 noisy=0.0460 edge=0.0864 latent=0.0138 lpips=0.0209
[AE] 043/60 loss=0.0750 clean=0.0362 noisy=0.0461 edge=0.0862 latent=0.0139 lpips=0.0209
[AE] 044/60 loss=0.0744 clean=0.0358 noisy=0.0458 edge=0.0859 latent=0.0138 lpips=0.0206
[AE] 045/60 loss=0.0737 clean=0.0354 noisy=0.0455 edge=0.0858 latent=0.0138 lpips=0.0205
[AE] 046/60 loss=0.0743 clean=0.0358 noisy=0.0458 edge=0.0856 latent=0.0139 lpips=0.0204
[AE] 047/60 loss=0.0741 clean=0.0357 noisy=0.0457 edge=0.0854 latent=0.0139 lpips=0.0203
[AE] 048/60 loss=0.0729 clean=0.0349 noisy=0.0452 edge=0.0849 latent=0.0137 lpips=0.0197
[AE] 049/60 loss=0.0740 clean=0.0357 noisy=0.0457 edge=0.0850 latent=0.0139 lpips=0.0199
[AE] 050/60 loss=0.0737 clean=0.0356 noisy=0.0456 edge=0.0847 latent=0.0138 lpips=0.0196
[AE] 051/60 loss=0.0731 clean=0.0351 noisy=0.0453 edge=0.0846 latent=0.0139 lpips=0.0196
[AE] 052/60 loss=0.0727 clean=0.0349 noisy=0.0451 edge=0.0842 latent=0.0138 lpips=0.0192
[AE] 053/60 loss=0.0727 clean=0.0349 noisy=0.0451 edge=0.0843 latent=0.0139 lpips=0.0193
[AE] 054/60 loss=0.0720 clean=0.0345 noisy=0.0448 edge=0.0838 latent=0.0137 lpips=0.0188
[AE] 055/60 loss=0.0727 clean=0.0350 noisy=0.0451 edge=0.0835 latent=0.0137 lpips=0.0186
[AE] 056/60 loss=0.0718 clean=0.0344 noisy=0.0447 edge=0.0836 latent=0.0138 lpips=0.0187
[AE] 057/60 loss=0.0719 clean=0.0345 noisy=0.0448 edge=0.0832 latent=0.0137 lpips=0.0184
[AE] 058/60 loss=0.0714 clean=0.0342 noisy=0.0445 edge=0.0832 latent=0.0138 lpips=0.0183
[AE] 059/60 loss=0.0713 clean=0.0342 noisy=0.0445 edge=0.0828 latent=0.0137 lpips=0.0180
[AE] 060/60 loss=0.0708 clean=0.0338 noisy=0.0443 edge=0.0827 latent=0.0138 lpips=0.0180
/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Reconstruction metrics:
{
  "clean_mse": 0.00279448926448822,
  "clean_psnr": 31.557575457898807,
  "noisy_mse": 0.004218475427478552,
  "noisy_psnr": 29.769044676326462,
  "num_samples": 5000.0,
  "clean_ssim": 0.9453810453414917,
  "noisy_ssim": 0.9101045727729797,
  "feature_precision": 0.9958,
  "feature_recall": 0.982,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "reconstruction_fid": 18.43449592590332,
  "reconstruction_kid_mean": 0.013809300027787685,
  "reconstruction_kid_std": 0.001104776980355382,
  "reconstruction_metric_samples": 5000.0
}
Uniform product-of-spheres diagnostic:
{
  "method": "uniform_product_sphere",
  "feature_precision": 0.0008,
  "feature_recall": 0.994,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "image_feature_precision": 0.6182,
  "image_feature_recall": 0.0,
  "image_pr_samples": 5000.0,
  "image_pr_nearest_k": 5.0,
  "fid": 191.03213500976562,
  "kid_mean": 0.22992096841335297,
  "kid_std": 0.0017470938619226217,
  "metric_samples": 5000.0
}

--------------------------------------------------------------------------------
Training prior: chord
/content/srul_cifar_spatial_tokens_experiment.py:868: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=config.amp and device.type == "cuda")
[chord] 001/120 loss=0.05292 path_norm=0.7619 radial=0.1964
[chord] 002/120 loss=0.04821 path_norm=0.7622 radial=0.3054
[chord] 003/120 loss=0.04686 path_norm=0.7623 radial=0.3411
[chord] 004/120 loss=0.04604 path_norm=0.7616 radial=0.3556
[chord] 005/120 loss=0.04542 path_norm=0.7624 radial=0.3714
[chord] 006/120 loss=0.04496 path_norm=0.7617 radial=0.3742
[chord] 007/120 loss=0.04465 path_norm=0.7617 radial=0.3792
[chord] 008/120 loss=0.04435 path_norm=0.7619 radial=0.3822
[chord] 009/120 loss=0.04405 path_norm=0.7622 radial=0.3859
[chord] 010/120 loss=0.04384 path_norm=0.7625 radial=0.3870
[chord] 011/120 loss=0.04366 path_norm=0.7623 radial=0.3864
[chord] 012/120 loss=0.04350 path_norm=0.7623 radial=0.3858
[chord] 013/120 loss=0.04334 path_norm=0.7618 radial=0.3838
[chord] 014/120 loss=0.04324 path_norm=0.7620 radial=0.3846
[chord] 015/120 loss=0.04307 path_norm=0.7619 radial=0.3837
[chord] 016/120 loss=0.04296 path_norm=0.7622 radial=0.3847
[chord] 017/120 loss=0.04289 path_norm=0.7619 radial=0.3830
[chord] 018/120 loss=0.04280 path_norm=0.7617 radial=0.3816
[chord] 019/120 loss=0.04269 path_norm=0.7617 radial=0.3821
[chord] 020/120 loss=0.04262 path_norm=0.7622 radial=0.3829
[chord] 021/120 loss=0.04252 path_norm=0.7620 radial=0.3810
[chord] 022/120 loss=0.04246 path_norm=0.7617 radial=0.3801
[chord] 023/120 loss=0.04240 path_norm=0.7622 radial=0.3830
[chord] 024/120 loss=0.04233 path_norm=0.7620 radial=0.3813
[chord] 025/120 loss=0.04228 path_norm=0.7620 radial=0.3810
[chord] 026/120 loss=0.04220 path_norm=0.7620 radial=0.3812
[chord] 027/120 loss=0.04218 path_norm=0.7615 radial=0.3773
[chord] 028/120 loss=0.04208 path_norm=0.7621 radial=0.3803
[chord] 029/120 loss=0.04207 path_norm=0.7620 radial=0.3794
[chord] 030/120 loss=0.04199 path_norm=0.7624 radial=0.3814
[chord] 031/120 loss=0.04198 path_norm=0.7614 radial=0.3762
[chord] 032/120 loss=0.04194 path_norm=0.7616 radial=0.3775
[chord] 033/120 loss=0.04190 path_norm=0.7618 radial=0.3775
[chord] 034/120 loss=0.04184 path_norm=0.7618 radial=0.3777
[chord] 035/120 loss=0.04179 path_norm=0.7622 radial=0.3792
[chord] 036/120 loss=0.04177 path_norm=0.7620 radial=0.3788
[chord] 037/120 loss=0.04177 path_norm=0.7620 radial=0.3774
[chord] 038/120 loss=0.04170 path_norm=0.7618 radial=0.3770
[chord] 039/120 loss=0.04164 path_norm=0.7620 radial=0.3776
[chord] 040/120 loss=0.04158 path_norm=0.7626 radial=0.3797
[chord] 041/120 loss=0.04161 path_norm=0.7622 radial=0.3786
[chord] 042/120 loss=0.04157 path_norm=0.7615 radial=0.3743
[chord] 043/120 loss=0.04155 path_norm=0.7615 radial=0.3740
[chord] 044/120 loss=0.04153 path_norm=0.7615 radial=0.3752
[chord] 045/120 loss=0.04150 path_norm=0.7617 radial=0.3749
[chord] 046/120 loss=0.04145 path_norm=0.7620 radial=0.3757
[chord] 047/120 loss=0.04144 path_norm=0.7619 radial=0.3756
[chord] 048/120 loss=0.04141 path_norm=0.7625 radial=0.3778
[chord] 049/120 loss=0.04138 path_norm=0.7620 radial=0.3755
[chord] 050/120 loss=0.04135 path_norm=0.7619 radial=0.3749
[chord] 051/120 loss=0.04131 path_norm=0.7622 radial=0.3760
[chord] 052/120 loss=0.04131 path_norm=0.7619 radial=0.3749
[chord] 053/120 loss=0.04131 path_norm=0.7618 radial=0.3740
[chord] 054/120 loss=0.04126 path_norm=0.7619 radial=0.3747
[chord] 055/120 loss=0.04127 path_norm=0.7622 radial=0.3757
[chord] 056/120 loss=0.04121 path_norm=0.7625 radial=0.3779
[chord] 057/120 loss=0.04120 path_norm=0.7620 radial=0.3744
[chord] 058/120 loss=0.04121 path_norm=0.7619 radial=0.3736
[chord] 059/120 loss=0.04115 path_norm=0.7619 radial=0.3730
[chord] 060/120 loss=0.04114 path_norm=0.7622 radial=0.3745
[chord] 061/120 loss=0.04110 path_norm=0.7623 radial=0.3737
[chord] 062/120 loss=0.04108 path_norm=0.7624 radial=0.3753
[chord] 063/120 loss=0.04107 path_norm=0.7624 radial=0.3758
[chord] 064/120 loss=0.04104 path_norm=0.7626 radial=0.3753
[chord] 065/120 loss=0.04104 path_norm=0.7622 radial=0.3742
[chord] 066/120 loss=0.04105 path_norm=0.7615 radial=0.3717
[chord] 067/120 loss=0.04103 path_norm=0.7624 radial=0.3754
[chord] 068/120 loss=0.04102 path_norm=0.7619 radial=0.3730
[chord] 069/120 loss=0.04099 path_norm=0.7621 radial=0.3729
[chord] 070/120 loss=0.04096 path_norm=0.7621 radial=0.3734
[chord] 071/120 loss=0.04095 path_norm=0.7620 radial=0.3718
[chord] 072/120 loss=0.04095 path_norm=0.7620 radial=0.3720
[chord] 073/120 loss=0.04093 path_norm=0.7619 radial=0.3716
[chord] 074/120 loss=0.04090 path_norm=0.7623 radial=0.3734
[chord] 075/120 loss=0.04085 path_norm=0.7626 radial=0.3749
[chord] 076/120 loss=0.04087 path_norm=0.7624 radial=0.3741
[chord] 077/120 loss=0.04089 path_norm=0.7623 radial=0.3737
[chord] 078/120 loss=0.04086 path_norm=0.7619 radial=0.3708
[chord] 079/120 loss=0.04085 path_norm=0.7620 radial=0.3717
[chord] 080/120 loss=0.04083 path_norm=0.7619 radial=0.3707
[chord] 081/120 loss=0.04082 path_norm=0.7621 radial=0.3724
[chord] 082/120 loss=0.04078 path_norm=0.7622 radial=0.3721
[chord] 083/120 loss=0.04077 path_norm=0.7623 radial=0.3721
[chord] 084/120 loss=0.04072 path_norm=0.7622 radial=0.3714
[chord] 085/120 loss=0.04076 path_norm=0.7619 radial=0.3707
[chord] 086/120 loss=0.04077 path_norm=0.7615 radial=0.3695
[chord] 087/120 loss=0.04076 path_norm=0.7616 radial=0.3702
[chord] 088/120 loss=0.04076 path_norm=0.7617 radial=0.3698
[chord] 089/120 loss=0.04069 path_norm=0.7621 radial=0.3709
[chord] 090/120 loss=0.04070 path_norm=0.7623 radial=0.3724
[chord] 091/120 loss=0.04069 path_norm=0.7620 radial=0.3711
[chord] 092/120 loss=0.04065 path_norm=0.7618 radial=0.3685
[chord] 093/120 loss=0.04067 path_norm=0.7621 radial=0.3705
[chord] 094/120 loss=0.04066 path_norm=0.7619 radial=0.3716
[chord] 095/120 loss=0.04064 path_norm=0.7622 radial=0.3717
[chord] 096/120 loss=0.04065 path_norm=0.7618 radial=0.3688
[chord] 097/120 loss=0.04058 path_norm=0.7624 radial=0.3703
[chord] 098/120 loss=0.04060 path_norm=0.7621 radial=0.3703
[chord] 099/120 loss=0.04061 path_norm=0.7621 radial=0.3709
[chord] 100/120 loss=0.04057 path_norm=0.7625 radial=0.3719
[chord] 101/120 loss=0.04056 path_norm=0.7623 radial=0.3708
[chord] 102/120 loss=0.04057 path_norm=0.7620 radial=0.3690
[chord] 103/120 loss=0.04055 path_norm=0.7620 radial=0.3697
[chord] 104/120 loss=0.04055 path_norm=0.7621 radial=0.3696
[chord] 105/120 loss=0.04051 path_norm=0.7622 radial=0.3701
[chord] 106/120 loss=0.04053 path_norm=0.7615 radial=0.3667
[chord] 107/120 loss=0.04053 path_norm=0.7616 radial=0.3670
[chord] 108/120 loss=0.04051 path_norm=0.7619 radial=0.3675
[chord] 109/120 loss=0.04048 path_norm=0.7621 radial=0.3688
[chord] 110/120 loss=0.04050 path_norm=0.7617 radial=0.3676
[chord] 111/120 loss=0.04048 path_norm=0.7618 radial=0.3678
[chord] 112/120 loss=0.04049 path_norm=0.7617 radial=0.3673
[chord] 113/120 loss=0.04046 path_norm=0.7616 radial=0.3661
[chord] 114/120 loss=0.04043 path_norm=0.7619 radial=0.3679
[chord] 115/120 loss=0.04044 path_norm=0.7618 radial=0.3671
[chord] 116/120 loss=0.04042 path_norm=0.7622 radial=0.3683
[chord] 117/120 loss=0.04041 path_norm=0.7621 radial=0.3679
[chord] 118/120 loss=0.04037 path_norm=0.7618 radial=0.3669
[chord] 119/120 loss=0.04040 path_norm=0.7623 radial=0.3692
[chord] 120/120 loss=0.04038 path_norm=0.7619 radial=0.3674

--------------------------------------------------------------------------------
Training prior: rfm
[rfm] 001/120 loss=0.06667 path_norm=1.0000 radial=0.2444
[rfm] 002/120 loss=0.06422 path_norm=1.0000 radial=0.2958
[rfm] 003/120 loss=0.06346 path_norm=1.0000 radial=0.3054
[rfm] 004/120 loss=0.06303 path_norm=1.0000 radial=0.3119
[rfm] 005/120 loss=0.06263 path_norm=1.0000 radial=0.3167
[rfm] 006/120 loss=0.06240 path_norm=1.0000 radial=0.3214
[rfm] 007/120 loss=0.06214 path_norm=1.0000 radial=0.3246
[rfm] 008/120 loss=0.06198 path_norm=1.0000 radial=0.3292
[rfm] 009/120 loss=0.06172 path_norm=1.0000 radial=0.3320
[rfm] 010/120 loss=0.06158 path_norm=1.0000 radial=0.3354
[rfm] 011/120 loss=0.06140 path_norm=1.0000 radial=0.3407
[rfm] 012/120 loss=0.06130 path_norm=1.0000 radial=0.3418
[rfm] 013/120 loss=0.06113 path_norm=1.0000 radial=0.3447
[rfm] 014/120 loss=0.06105 path_norm=1.0000 radial=0.3492
[rfm] 015/120 loss=0.06089 path_norm=1.0000 radial=0.3495
[rfm] 016/120 loss=0.06076 path_norm=1.0000 radial=0.3529
[rfm] 017/120 loss=0.06067 path_norm=1.0000 radial=0.3559
[rfm] 018/120 loss=0.06053 path_norm=1.0000 radial=0.3575
[rfm] 019/120 loss=0.06048 path_norm=1.0000 radial=0.3607
[rfm] 020/120 loss=0.06033 path_norm=1.0000 radial=0.3626
[rfm] 021/120 loss=0.06028 path_norm=1.0000 radial=0.3642
[rfm] 022/120 loss=0.06021 path_norm=1.0000 radial=0.3672
[rfm] 023/120 loss=0.06020 path_norm=1.0000 radial=0.3692
[rfm] 024/120 loss=0.06004 path_norm=1.0000 radial=0.3715
[rfm] 025/120 loss=0.06000 path_norm=1.0000 radial=0.3731
[rfm] 026/120 loss=0.05993 path_norm=1.0000 radial=0.3751
[rfm] 027/120 loss=0.05985 path_norm=1.0000 radial=0.3767
[rfm] 028/120 loss=0.05987 path_norm=1.0000 radial=0.3810
[rfm] 029/120 loss=0.05980 path_norm=1.0000 radial=0.3808
[rfm] 030/120 loss=0.05968 path_norm=1.0000 radial=0.3817
[rfm] 031/120 loss=0.05958 path_norm=1.0000 radial=0.3815
[rfm] 032/120 loss=0.05955 path_norm=1.0000 radial=0.3859
[rfm] 033/120 loss=0.05960 path_norm=1.0000 radial=0.3849
[rfm] 034/120 loss=0.05949 path_norm=1.0000 radial=0.3885
[rfm] 035/120 loss=0.05946 path_norm=1.0000 radial=0.3883
[rfm] 036/120 loss=0.05943 path_norm=1.0000 radial=0.3898
[rfm] 037/120 loss=0.05935 path_norm=1.0000 radial=0.3911
[rfm] 038/120 loss=0.05931 path_norm=1.0000 radial=0.3929
[rfm] 039/120 loss=0.05931 path_norm=1.0000 radial=0.3930
[rfm] 040/120 loss=0.05921 path_norm=1.0000 radial=0.3954
[rfm] 041/120 loss=0.05915 path_norm=1.0000 radial=0.3956
[rfm] 042/120 loss=0.05917 path_norm=1.0000 radial=0.3977
[rfm] 043/120 loss=0.05912 path_norm=1.0000 radial=0.3971
[rfm] 044/120 loss=0.05902 path_norm=1.0000 radial=0.3987
[rfm] 045/120 loss=0.05905 path_norm=1.0000 radial=0.3994
[rfm] 046/120 loss=0.05893 path_norm=1.0000 radial=0.3989
[rfm] 047/120 loss=0.05891 path_norm=1.0000 radial=0.4007
[rfm] 048/120 loss=0.05896 path_norm=1.0000 radial=0.4022
[rfm] 049/120 loss=0.05888 path_norm=1.0000 radial=0.4021
[rfm] 050/120 loss=0.05881 path_norm=1.0000 radial=0.4042
[rfm] 051/120 loss=0.05886 path_norm=1.0000 radial=0.4048
[rfm] 052/120 loss=0.05881 path_norm=1.0000 radial=0.4061
[rfm] 053/120 loss=0.05875 path_norm=1.0000 radial=0.4066
[rfm] 054/120 loss=0.05879 path_norm=1.0000 radial=0.4068
[rfm] 055/120 loss=0.05872 path_norm=1.0000 radial=0.4063
[rfm] 056/120 loss=0.05865 path_norm=1.0000 radial=0.4070
[rfm] 057/120 loss=0.05858 path_norm=1.0000 radial=0.4077
[rfm] 058/120 loss=0.05860 path_norm=1.0000 radial=0.4107
[rfm] 059/120 loss=0.05861 path_norm=1.0000 radial=0.4095
[rfm] 060/120 loss=0.05862 path_norm=1.0000 radial=0.4106
[rfm] 061/120 loss=0.05855 path_norm=1.0000 radial=0.4107
[rfm] 062/120 loss=0.05854 path_norm=1.0000 radial=0.4104
[rfm] 063/120 loss=0.05843 path_norm=1.0000 radial=0.4123
[rfm] 064/120 loss=0.05849 path_norm=1.0000 radial=0.4112
[rfm] 065/120 loss=0.05836 path_norm=1.0000 radial=0.4123
[rfm] 066/120 loss=0.05838 path_norm=1.0000 radial=0.4135
[rfm] 067/120 loss=0.05844 path_norm=1.0000 radial=0.4160
[rfm] 068/120 loss=0.05838 path_norm=1.0000 radial=0.4159
[rfm] 069/120 loss=0.05845 path_norm=1.0000 radial=0.4165
[rfm] 070/120 loss=0.05835 path_norm=1.0000 radial=0.4150
[rfm] 071/120 loss=0.05825 path_norm=1.0000 radial=0.4173
[rfm] 072/120 loss=0.05825 path_norm=1.0000 radial=0.4179
[rfm] 073/120 loss=0.05818 path_norm=1.0000 radial=0.4196
[rfm] 074/120 loss=0.05827 path_norm=1.0000 radial=0.4188

In [6]:
from pathlib import Path
import json

import pandas as pd
from IPython.display import display


ROOT = Path("/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1")
SEEDS = [0, 1, 2]

# ------------------------------------------------------------
# Collect generation and geometry metrics
# ------------------------------------------------------------

generation_frames = []

for seed in SEEDS:
    path = ROOT / f"seed_{seed}" / "generation_metrics.csv"

    if not path.exists():
        print(f"Missing: {path}")
        continue

    frame = pd.read_csv(path)
    frame["seed"] = seed
    generation_frames.append(frame)

if not generation_frames:
    raise RuntimeError("No completed generation_metrics.csv files were found.")

all_results = pd.concat(generation_frames, ignore_index=True)

metrics = [
    "fid",
    "kid_mean",
    "feature_precision",
    "feature_recall",
    "latent_feature_precision",
    "latent_feature_recall",
    "min_mean_path_norm",
    "mean_abs_path_norm_error",
    "mean_raw_radial_fraction",
]

available_metrics = [m for m in metrics if m in all_results.columns]

summary = (
    all_results
    .groupby("method")[available_metrics]
    .agg(["mean", "std"])
    .sort_values(("fid", "mean"))
)

print("All individual runs:")
display(
    all_results[
        ["method", "seed"] + available_metrics
    ].sort_values(["method", "seed"])
)

print("\nMean ± standard deviation across seeds:")
display(summary)

all_results.to_csv(
    ROOT / "all_seed_results.csv",
    index=False,
)

summary.to_csv(
    ROOT / "three_seed_summary.csv"
)

print("\nSaved:")
print(ROOT / "all_seed_results.csv")
print(ROOT / "three_seed_summary.csv")

All individual runs:

,method,seed,fid,kid_mean,feature_precision,feature_recall,latent_feature_precision,latent_feature_recall,min_mean_path_norm,mean_abs_path_norm_error,mean_raw_radial_fraction
0,chord,0,67.440224,0.073960,0.8402,0.0846,0.6194,0.7260,0.704737,0.188100,0.540500
3,chord,1,72.619171,0.079829,0.8284,0.0742,0.6422,0.8320,0.705290,0.187644,0.549154
6,chord,2,69.284355,0.072456,0.8314,0.0858,0.6936,0.6856,0.700424,0.191421,0.537788
1,rfm,0,63.836128,0.066741,0.8574,0.0912,0.7102,0.6402,1.000000,0.000000,0.403560
4,rfm,1,68.376640,0.075617,0.8068,0.0962,0.6912,0.7866,1.000000,0.000000,0.413156
7,rfm,2,68.485245,0.073002,0.8436,0.0918,0.7454,0.6572,1.000000,0.000000,0.422752
2,srul,0,66.252907,0.069697,0.8454,0.0828,0.6768,0.6996,1.000000,0.000000,0.395715
5,srul,1,69.757095,0.074896,0.8216,0.0976,0.6988,0.7926,1.000000,0.000000,0.425920
8,srul,2,70.414879,0.077564,0.8466,0.0848,0.6728,0.6996,1.000000,0.000000,0.404430

Mean ± standard deviation across seeds:

              fid            kid_mean           feature_precision            \
             mean       std      mean       std              mean       std
method
rfm     66.899338  2.653373  0.071786  0.004561          0.835933  0.026157
srul    68.808294  2.237336  0.074052  0.004001          0.837867  0.014100
chord   69.781250  2.624986  0.075415  0.003896          0.833333  0.006133

       feature_recall           latent_feature_precision            \
                 mean       std                     mean       std
method
rfm          0.093067  0.002730                 0.715600  0.027501
srul         0.088400  0.008030                 0.682800  0.014000
chord        0.081533  0.006379                 0.651733  0.038008

       latent_feature_recall           min_mean_path_norm            \
                        mean       std               mean       std
method
rfm                 0.694667  0.080069           1.000000  0.000000
srul                0.730600  0.053694           1.000000  0.000000
chord               0.747867  0.075610           0.703484  0.002664

       mean_abs_path_norm_error           mean_raw_radial_fraction
                           mean       std                     mean       std
method
rfm                    0.000000  0.000000                 0.413156  0.009596
srul                   0.000000  0.000000                 0.408689  0.015546
chord                  0.189055  0.002061                 0.542481  0.005936

Saved:
/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/all_seed_results.csv
/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/three_seed_summary.csv

In [7]:
def mean_std_text(group: pd.DataFrame, metric: str, digits: int = 2) -> str:
    mean = group[metric].mean()
    std = group[metric].std(ddof=1)
    return f"{mean:.{digits}f} ± {std:.{digits}f}"


rows = []

for method, group in all_results.groupby("method"):
    rows.append({
        "Method": method,
        "FID ↓": mean_std_text(group, "fid", 2),
        "KID ↓": mean_std_text(group, "kid_mean", 4),
        "Precision ↑": mean_std_text(group, "feature_precision", 4),
        "Recall ↑": mean_std_text(group, "feature_recall", 4),
        "Latent precision ↑": mean_std_text(
            group, "latent_feature_precision", 4
        ),
        "Latent recall ↑": mean_std_text(
            group, "latent_feature_recall", 4
        ),
    })

paper_table = pd.DataFrame(rows).sort_values("Method")
display(paper_table)

paper_table.to_csv(
    ROOT / "paper_result_table.csv",
    index=False,
)

,Method,FID ↓,KID ↓,Precision ↑,Recall ↑,Latent precision ↑,Latent recall ↑
0,chord,69.78 ± 2.62,0.0754 ± 0.0039,0.8333 ± 0.0061,0.0815 ± 0.0064,0.6517 ± 0.0380,0.7479 ± 0.0756
1,rfm,66.90 ± 2.65,0.0718 ± 0.0046,0.8359 ± 0.0262,0.0931 ± 0.0027,0.7156 ± 0.0275,0.6947 ± 0.0801
2,srul,68.81 ± 2.24,0.0741 ± 0.0040,0.8379 ± 0.0141,0.0884 ± 0.0080,0.6828 ± 0.0140,0.7306 ± 0.0537

In [8]:
!python /content/srul_cifar_conditional_spatial_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_CIFAR10/conditional_v1" \
    --ae-checkpoint "/content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/seed_0/checkpoints/autoencoder_final.pt" \
    --skip-ae-training \
    --dataset cifar10 \
    --train-samples 0 \
    --test-samples 10000 \
    --seed 0 \
    --base-channels 96 \
    --latent-channels 32 \
    --prior-epochs 120 \
    --prior-lr 2e-4 \
    --prior-width 256 \
    --prior-depth 6 \
    --time-dim 128 \
    --time-sampling logit_normal \
    --methods cond_rfm cond_srul \
    --label-drop-prob 0.10 \
    --jacobi-alpha 0.25 \
    --ema-decay 0.999 \
    --guidance-scales 1.0 1.5 2.0 \
    --sample-steps 100 \
    --metric-samples 10000 \
    --pr-samples 5000 \
    --recon-metric-samples 5000 \
    --batch-size 128 \
    --metric-batch-size 128 \
    --num-workers 2 \
    --checkpoint-every 5 \
    --amp \
    --resume

================================================================================
Class-conditional SRUL-v2 on spatial product-of-spheres latents
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_CIFAR10/conditional_v1/seed_0
Latent: 32 x 4 x 4
Methods: ['cond_rfm', 'cond_srul']
Guidance scales: [1.0, 1.5, 2.0]
Soft Jacobi alpha: 0.25
EMA decay: 0.999
Label-drop probability: 0.1
================================================================================
Loaded external spatial autoencoder: /content/drive/MyDrive/SRUL_CIFAR10/spatial_v1/seed_0/checkpoints/autoencoder_final.pt
/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Reconstruction metrics:
{
  "clean_mse": 0.002895622979849577,
  "clean_psnr": 31.40317976769029,
  "noisy_mse": 0.004319916479289532,
  "noisy_psnr": 29.66584641025625,
  "num_samples": 5000.0,
  "clean_ssim": 0.9376798868179321,
  "noisy_ssim": 0.9057363271713257,
  "feature_precision": 0.996,
  "feature_recall": 0.9888,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "reconstruction_fid": 17.31466293334961,
  "reconstruction_kid_mean": 0.010931253433227539,
  "reconstruction_kid_std": 0.0009147331002168357,
  "reconstruction_metric_samples": 5000.0
}

--------------------------------------------------------------------------------
Training conditional prior: cond_rfm
[cond_rfm] 001/120 loss=0.06648 path_norm=1.0000 radial=0.2444 drop=0.102 alpha=0.00
[cond_rfm] 002/120 loss=0.06393 path_norm=1.0000 radial=0.2938 drop=0.101 alpha=0.00
[cond_rfm] 003/120 loss=0.06311 path_norm=1.0000 radial=0.3009 drop=0.098 alpha=0.00
[cond_rfm] 004/120 loss=0.06266 path_norm=1.0000 radial=0.3061 drop=0.102 alpha=0.00
[cond_rfm] 005/120 loss=0.06228 path_norm=1.0000 radial=0.3109 drop=0.100 alpha=0.00
[cond_rfm] 006/120 loss=0.06194 path_norm=1.0000 radial=0.3142 drop=0.101 alpha=0.00
[cond_rfm] 007/120 loss=0.06177 path_norm=1.0000 radial=0.3162 drop=0.100 alpha=0.00
[cond_rfm] 008/120 loss=0.06162 path_norm=1.0000 radial=0.3203 drop=0.099 alpha=0.00
[cond_rfm] 009/120 loss=0.06137 path_norm=1.0000 radial=0.3219 drop=0.100 alpha=0.00
[cond_rfm] 010/120 loss=0.06125 path_norm=1.0000 radial=0.3258 drop=0.101 alpha=0.00
[cond_rfm] 011/120 loss=0.06105 path_norm=1.0000 radial=0.3284 drop=0.101 alpha=0.00
[cond_rfm] 012/120 loss=0.06091 path_norm=1.0000 radial=0.3307 drop=0.102 alpha=0.00
[cond_rfm] 013/120 loss=0.06075 path_norm=1.0000 radial=0.3345 drop=0.100 alpha=0.00
[cond_rfm] 014/120 loss=0.06062 path_norm=1.0000 radial=0.3367 drop=0.101 alpha=0.00
[cond_rfm] 015/120 loss=0.06048 path_norm=1.0000 radial=0.3384 drop=0.100 alpha=0.00
[cond_rfm] 016/120 loss=0.06038 path_norm=1.0000 radial=0.3403 drop=0.100 alpha=0.00
[cond_rfm] 017/120 loss=0.06030 path_norm=1.0000 radial=0.3424 drop=0.101 alpha=0.00
[cond_rfm] 018/120 loss=0.06013 path_norm=1.0000 radial=0.3441 drop=0.098 alpha=0.00
[cond_rfm] 019/120 loss=0.06010 path_norm=1.0000 radial=0.3467 drop=0.100 alpha=0.00
[cond_rfm] 020/120 loss=0.05996 path_norm=1.0000 radial=0.3478 drop=0.101 alpha=0.00
[cond_rfm] 021/120 loss=0.05990 path_norm=1.0000 radial=0.3520 drop=0.096 alpha=0.00
[cond_rfm] 022/120 loss=0.05985 path_norm=1.0000 radial=0.3529 drop=0.099 alpha=0.00
[cond_rfm] 023/120 loss=0.05973 path_norm=1.0000 radial=0.3540 drop=0.099 alpha=0.00
[cond_rfm] 024/120 loss=0.05963 path_norm=1.0000 radial=0.3553 drop=0.101 alpha=0.00
[cond_rfm] 025/120 loss=0.05954 path_norm=1.0000 radial=0.3583 drop=0.101 alpha=0.00
[cond_rfm] 026/120 loss=0.05952 path_norm=1.0000 radial=0.3608 drop=0.101 alpha=0.00
[cond_rfm] 027/120 loss=0.05935 path_norm=1.0000 radial=0.3623 drop=0.101 alpha=0.00
[cond_rfm] 028/120 loss=0.05935 path_norm=1.0000 radial=0.3628 drop=0.100 alpha=0.00
[cond_rfm] 029/120 loss=0.05941 path_norm=1.0000 radial=0.3647 drop=0.099 alpha=0.00
[cond_rfm] 030/120 loss=0.05918 path_norm=1.0000 radial=0.3669 drop=0.101 alpha=0.00
[cond_rfm] 031/120 loss=0.05919 path_norm=1.0000 radial=0.3686 drop=0.100 alpha=0.00
[cond_rfm] 032/120 loss=0.05909 path_norm=1.0000 radial=0.3689 drop=0.102 alpha=0.00
[cond_rfm] 033/120 loss=0.05900 path_norm=1.0000 radial=0.3721 drop=0.100 alpha=0.00
[cond_rfm] 034/120 loss=0.05893 path_norm=1.0000 radial=0.3721 drop=0.099 alpha=0.00
[cond_rfm] 035/120 loss=0.05897 path_norm=1.0000 radial=0.3758 drop=0.100 alpha=0.00
[cond_rfm] 036/120 loss=0.05895 path_norm=1.0000 radial=0.3768 drop=0.100 alpha=0.00
[cond_rfm] 037/120 loss=0.05886 path_norm=1.0000 radial=0.3781 drop=0.101 alpha=0.00
[cond_rfm] 038/120 loss=0.05872 path_norm=1.0000 radial=0.3784 drop=0.101 alpha=0.00
[cond_rfm] 039/120 loss=0.05875 path_norm=1.0000 radial=0.3803 drop=0.098 alpha=0.00
[cond_rfm] 040/120 loss=0.05868 path_norm=1.0000 radial=0.3818 drop=0.101 alpha=0.00
[cond_rfm] 041/120 loss=0.05874 path_norm=1.0000 radial=0.3818 drop=0.100 alpha=0.00
[cond_rfm] 042/120 loss=0.05864 path_norm=1.0000 radial=0.3830 drop=0.103 alpha=0.00
[cond_rfm] 043/120 loss=0.05857 path_norm=1.0000 radial=0.3840 drop=0.100 alpha=0.00
[cond_rfm] 044/120 loss=0.05855 path_norm=1.0000 radial=0.3848 drop=0.099 alpha=0.00
[cond_rfm] 045/120 loss=0.05850 path_norm=1.0000 radial=0.3855 drop=0.100 alpha=0.00
[cond_rfm] 046/120 loss=0.05846 path_norm=1.0000 radial=0.3871 drop=0.100 alpha=0.00
[cond_rfm] 047/120 loss=0.05847 path_norm=1.0000 radial=0.3881 drop=0.102 alpha=0.00
[cond_rfm] 048/120 loss=0.05842 path_norm=1.0000 radial=0.3893 drop=0.100 alpha=0.00
[cond_rfm] 049/120 loss=0.05836 path_norm=1.0000 radial=0.3882 drop=0.100 alpha=0.00
[cond_rfm] 050/120 loss=0.05836 path_norm=1.0000 radial=0.3913 drop=0.098 alpha=0.00
[cond_rfm] 051/120 loss=0.05830 path_norm=1.0000 radial=0.3915 drop=0.101 alpha=0.00
[cond_rfm] 052/120 loss=0.05828 path_norm=1.0000 radial=0.3943 drop=0.098 alpha=0.00
[cond_rfm] 053/120 loss=0.05828 path_norm=1.0000 radial=0.3941 drop=0.101 alpha=0.00
[cond_rfm] 054/120 loss=0.05817 path_norm=1.0000 radial=0.3938 drop=0.102 alpha=0.00
[cond_rfm] 055/120 loss=0.05814 path_norm=1.0000 radial=0.3957 drop=0.100 alpha=0.00
[cond_rfm] 056/120 loss=0.05807 path_norm=1.0000 radial=0.3950 drop=0.101 alpha=0.00
[cond_rfm] 057/120 loss=0.05811 path_norm=1.0000 radial=0.3966 drop=0.100 alpha=0.00
[cond_rfm] 058/120 loss=0.05796 path_norm=1.0000 radial=0.3965 drop=0.099 alpha=0.00
[cond_rfm] 059/120 loss=0.05801 path_norm=1.0000 radial=0.3982 drop=0.098 alpha=0.00
[cond_rfm] 060/120 loss=0.05796 path_norm=1.0000 radial=0.3982 drop=0.101 alpha=0.00
[cond_rfm] 061/120 loss=0.05792 path_norm=1.0000 radial=0.3983 drop=0.101 alpha=0.00
[cond_rfm] 062/120 loss=0.05792 path_norm=1.0000 radial=0.4017 drop=0.097 alpha=0.00
[cond_rfm] 063/120 loss=0.05793 path_norm=1.0000 radial=0.4007 drop=0.100 alpha=0.00
[cond_rfm] 064/120 loss=0.05788 path_norm=1.0000 radial=0.4018 drop=0.100 alpha=0.00
[cond_rfm] 065/120 loss=0.05785 path_norm=1.0000 radial=0.4025 drop=0.099 alpha=0.00
[cond_rfm] 066/120 loss=0.05779 path_norm=1.0000 radial=0.4017 drop=0.099 alpha=0.00
[cond_rfm] 067/120 loss=0.05778 path_norm=1.0000 radial=0.4036 drop=0.099 alpha=0.00
[cond_rfm] 068/120 loss=0.05778 path_norm=1.0000 radial=0.4048 drop=0.100 alpha=0.00
[cond_rfm] 069/120 loss=0.05772 path_norm=1.0000 radial=0.4037 drop=0.100 alpha=0.00
[cond_rfm] 070/120 loss=0.05775 path_norm=1.0000 radial=0.4062 drop=0.103 alpha=0.00
[cond_rfm] 071/120 loss=0.05769 path_norm=1.0000 radial=0.4047 drop=0.099 alpha=0.00
[cond_rfm] 072/120 loss=0.05771 path_norm=1.0000 radial=0.4085 drop=0.100 alpha=0.00
[cond_rfm] 073/120 loss=0.05767 path_norm=1.0000 radial=0.4076 drop=0.102 alpha=0.00
[cond_rfm] 074/120 loss=0.05760 path_norm=1.0000 radial=0.4079 drop=0.101 alpha=0.00
[cond_rfm] 075/120 loss=0.05762 path_norm=1.0000 radial=0.4097 drop=0.101 alpha=0.00
[cond_rfm] 076/120 loss=0.05760 path_norm=1.0000 radial=0.4082 drop=0.099 alpha=0.00
[cond_rfm] 077/120 loss=0.05751 path_norm=1.0000 radial=0.4094 drop=0.099 alpha=0.00
[cond_rfm] 078/120 loss=0.05755 path_norm=1.0000 radial=0.4120 drop=0.101 alpha=0.00
[cond_rfm] 079/120 loss=0.05754 path_norm=1.0000 radial=0.4094 drop=0.101 alpha=0.00
[cond_rfm] 080/120 loss=0.05750 path_norm=1.0000 radial=0.4125 drop=0.103 alpha=0.00
[cond_rfm] 081/120 loss=0.05747 path_norm=1.0000 radial=0.4115 drop=0.099 alpha=0.00
[cond_rfm] 082/120 loss=0.05743 path_norm=1.0000 radial=0.4123 drop=0.101 alpha=0.00
[cond_rfm] 083/120 loss=0.05743 path_norm=1.0000 radial=0.4114 drop=0.100 alpha=0.00
[cond_rfm] 084/120 loss=0.05742 path_norm=1.0000 radial=0.4120 drop=0.097 alpha=0.00
[cond_rfm] 085/120 loss=0.05735 path_norm=1.0000 radial=0.4126 drop=0.103 alpha=0.00
[cond_rfm] 086/120 loss=0.05734 path_norm=1.0000 radial=0.4137 drop=0.101 alpha=0.00
[cond_rfm] 087/120 loss=0.05731 path_norm=1.0000 radial=0.4151 drop=0.099 alpha=0.00
[cond_rfm] 088/120 loss=0.05726 path_norm=1.0000 radial=0.4151 drop=0.100 alpha=0.00
[cond_rfm] 089/120 loss=0.05728 path_norm=1.0000 radial=0.4145 drop=0.102 alpha=0.00
[cond_rfm] 090/120 loss=0.05728 path_norm=1.0000 radial=0.4158 drop=0.100 alpha=0.00
[cond_rfm] 091/120 loss=0.05719 path_norm=1.0000 radial=0.4155 drop=0.099 alpha=0.00
[cond_rfm] 092/120 loss=0.05722 path_norm=1.0000 radial=0.4155 drop=0.101 alpha=0.00
[cond_rfm] 093/120 loss=0.05724 path_norm=1.0000 radial=0.4162 drop=0.100 alpha=0.00
[cond_rfm] 094/120 loss=0.05716 path_norm=1.0000 radial=0.4172 drop=0.101 alpha=0.00
[cond_rfm] 095/120 loss=0.05717 path_norm=1.0000 radial=0.4173 drop=0.100 alpha=0.00
[cond_rfm] 096/120 loss=0.05721 path_norm=1.0000 radial=0.4167 drop=0.101 alpha=0.00
[cond_rfm] 097/120 loss=0.05716 path_norm=1.0000 radial=0.4181 drop=0.102 alpha=0.00
[cond_rfm] 098/120 loss=0.05709 path_norm=1.0000 radial=0.4181 drop=0.100 alpha=0.00
[cond_rfm] 099/120 loss=0.05704 path_norm=1.0000 radial=0.4174 drop=0.100 alpha=0.00
[cond_rfm] 100/120 loss=0.05705 path_norm=1.0000 radial=0.4187 drop=0.100 alpha=0.00
[cond_rfm] 101/120 loss=0.05708 path_norm=1.0000 radial=0.4202 drop=0.101 alpha=0.00
[cond_rfm] 102/120 loss=0.05705 path_norm=1.0000 radial=0.4184 drop=0.099 alpha=0.00
[cond_rfm] 103/120 loss=0.05698 path_norm=1.0000 radial=0.4190 drop=0.099 alpha=0.00
[cond_rfm] 104/120 loss=0.05697 path_norm=1.0000 radial=0.4208 drop=0.099 alpha=0.00
[cond_rfm] 105/120 loss=0.05698 path_norm=1.0000 radial=0.4209 drop=0.102 alpha=0.00
[cond_rfm] 106/120 loss=0.05695 path_norm=1.0000 radial=0.4212 drop=0.098 alpha=0.00
[cond_rfm] 107/120 loss=0.05695 path_norm=1.0000 radial=0.4228 drop=0.098 alpha=0.00
[cond_rfm] 108/120 loss=0.05701 path_norm=1.0000 radial=0.4226 drop=0.099 alpha=0.00
[cond_rfm] 109/120 loss=0.05692 path_norm=1.0000 radial=0.4219 drop=0.101 alpha=0.00
[cond_rfm] 110/120 loss=0.05689 path_norm=1.0000 radial=0.4221 drop=0.101 alpha=0.00
[cond_rfm] 111/120 loss=0.05691 path_norm=1.0000 radial=0.4224 drop=0.099 alpha=0.00
[cond_rfm] 112/120 loss=0.05689 path_norm=1.0000 radial=0.4240 drop=0.099 alpha=0.00
[cond_rfm] 113/120 loss=0.05681 path_norm=1.0000 radial=0.4234 drop=0.102 alpha=0.00
[cond_rfm] 114/120 loss=0.05678 path_norm=1.0000 radial=0.4225 drop=0.100 alpha=0.00
[cond_rfm] 115/120 loss=0.05681 path_norm=1.0000 radial=0.4245 drop=0.100 alpha=0.00
[cond_rfm] 116/120 loss=0.05678 path_norm=1.0000 radial=0.4231 drop=0.098 alpha=0.00
[cond_rfm] 117/120 loss=0.05676 path_norm=1.0000 radial=0.4230 drop=0.100 alpha=0.00
[cond_rfm] 118/120 loss=0.05673 path_norm=1.0000 radial=0.4246 drop=0.098 alpha=0.00
[cond_rfm] 119/120 loss=0.05672 path_norm=1.0000 radial=0.4257 drop=0.098 alpha=0.00
[cond_rfm] 120/120 loss=0.05673 path_norm=1.0000 radial=0.4255 drop=0.101 alpha=0.00
[cond_rfm] loaded EMA weights for evaluation.

--------------------------------------------------------------------------------
Training conditional prior: cond_srul
[cond_srul] 001/120 loss=0.06284 path_norm=1.0000 radial=0.2410 drop=0.099 alpha=0.25
[cond_srul] 002/120 loss=0.06030 path_norm=1.0000 radial=0.2937 drop=0.100 alpha=0.25
[cond_srul] 003/120 loss=0.05956 path_norm=1.0000 radial=0.3024 drop=0.096 alpha=0.25
[cond_srul] 004/120 loss=0.05910 path_norm=1.0000 radial=0.3077 drop=0.102 alpha=0.25
[cond_srul] 005/120 loss=0.05880 path_norm=1.0000 radial=0.3133 drop=0.100 alpha=0.25
[cond_srul] 006/120 loss=0.05846 path_norm=1.0000 radial=0.3171 drop=0.100 alpha=0.25
[cond_srul] 007/120 loss=0.05829 path_norm=1.0000 radial=0.3208 drop=0.099 alpha=0.25
[cond_srul] 008/120 loss=0.05812 path_norm=1.0000 radial=0.3229 drop=0.099 alpha=0.25
[cond_srul] 009/120 loss=0.05788 path_norm=1.0000 radial=0.3260 drop=0.099 alpha=0.25
[cond_srul] 010/120 loss=0.05771 path_norm=1.0000 radial=0.3296 drop=0.100 alpha=0.25
[cond_srul] 011/120 loss=0.05758 path_norm=1.0000 radial=0.3312 drop=0.100 alpha=0.25
[cond_srul] 012/120 loss=0.05746 path_norm=1.0000 radial=0.3341 drop=0.099 alpha=0.25
[cond_srul] 013/120 loss=0.05734 path_norm=1.0000 radial=0.3358 drop=0.096 alpha=0.25
[cond_srul] 014/120 loss=0.05717 path_norm=1.0000 radial=0.3389 drop=0.101 alpha=0.25
[cond_srul] 015/120 loss=0.05707 path_norm=1.0000 radial=0.3409 drop=0.102 alpha=0.25
[cond_srul] 016/120 loss=0.05696 path_norm=1.0000 radial=0.3430 drop=0.100 alpha=0.25
[cond_srul] 017/120 loss=0.05689 path_norm=1.0000 radial=0.3458 drop=0.102 alpha=0.25
[cond_srul] 018/120 loss=0.05677 path_norm=1.0000 radial=0.3489 drop=0.100 alpha=0.25
[cond_srul] 019/120 loss=0.05667 path_norm=1.0000 radial=0.3497 drop=0.101 alpha=0.25
[cond_srul] 020/120 loss=0.05659 path_norm=1.0000 radial=0.3517 drop=0.101 alpha=0.25
[cond_srul] 021/120 loss=0.05652 path_norm=1.0000 radial=0.3537 drop=0.099 alpha=0.25
[cond_srul] 022/120 loss=0.05647 path_norm=1.0000 radial=0.3554 drop=0.101 alpha=0.25
[cond_srul] 023/120 loss=0.05635 path_norm=1.0000 radial=0.3572 drop=0.099 alpha=0.25
[cond_srul] 024/120 loss=0.05629 path_norm=1.0000 radial=0.3601 drop=0.099 alpha=0.25
[cond_srul] 025/120 loss=0.05619 path_norm=1.0000 radial=0.3619 drop=0.099 alpha=0.25
[cond_srul] 026/120 loss=0.05622 path_norm=1.0000 radial=0.3625 drop=0.099 alpha=0.25
[cond_srul] 027/120 loss=0.05611 path_norm=1.0000 radial=0.3635 drop=0.099 alpha=0.25
[cond_srul] 028/120 loss=0.05603 path_norm=1.0000 radial=0.3657 drop=0.102 alpha=0.25
[cond_srul] 029/120 loss=0.05601 path_norm=1.0000 radial=0.3664 drop=0.099 alpha=0.25
[cond_srul] 030/120 loss=0.05595 path_norm=1.0000 radial=0.3685 drop=0.101 alpha=0.25
[cond_srul] 031/120 loss=0.05587 path_norm=1.0000 radial=0.3698 drop=0.101 alpha=0.25
[cond_srul] 032/120 loss=0.05582 path_norm=1.0000 radial=0.3706 drop=0.100 alpha=0.25
[cond_srul] 033/120 loss=0.05578 path_norm=1.0000 radial=0.3737 drop=0.100 alpha=0.25
[cond_srul] 034/120 loss=0.05573 path_norm=1.0000 radial=0.3743 drop=0.099 alpha=0.25
[cond_srul] 035/120 loss=0.05565 path_norm=1.0000 radial=0.3750 drop=0.102 alpha=0.25
[cond_srul] 036/120 loss=0.05565 path_norm=1.0000 radial=0.3770 drop=0.100 alpha=0.25
[cond_srul] 037/120 loss=0.05557 path_norm=1.0000 radial=0.3781 drop=0.099 alpha=0.25
[cond_srul] 038/120 loss=0.05559 path_norm=1.0000 radial=0.3789 drop=0.102 alpha=0.25
[cond_srul] 039/120 loss=0.05551 path_norm=1.0000 radial=0.3793 drop=0.098 alpha=0.25
[cond_srul] 040/120 loss=0.05543 path_norm=1.0000 radial=0.3795 drop=0.098 alpha=0.25
[cond_srul] 041/120 loss=0.05541 path_norm=1.0000 radial=0.3813 drop=0.099 alpha=0.25
[cond_srul] 042/120 loss=0.05546 path_norm=1.0000 radial=0.3811 drop=0.100 alpha=0.25
[cond_srul] 043/120 loss=0.05537 path_norm=1.0000 radial=0.3834 drop=0.100 alpha=0.25
[cond_srul] 044/120 loss=0.05534 path_norm=1.0000 radial=0.3837 drop=0.101 alpha=0.25
[cond_srul] 045/120 loss=0.05529 path_norm=1.0000 radial=0.3867 drop=0.098 alpha=0.25
[cond_srul] 046/120 loss=0.05529 path_norm=1.0000 radial=0.3872 drop=0.101 alpha=0.25
[cond_srul] 047/120 loss=0.05521 path_norm=1.0000 radial=0.3872 drop=0.100 alpha=0.25
[cond_srul] 048/120 loss=0.05512 path_norm=1.0000 radial=0.3874 drop=0.100 alpha=0.25
[cond_srul] 049/120 loss=0.05515 path_norm=1.0000 radial=0.3887 drop=0.102 alpha=0.25
[cond_srul] 050/120 loss=0.05513 path_norm=1.0000 radial=0.3894 drop=0.100 alpha=0.25
[cond_srul] 051/120 loss=0.05511 path_norm=1.0000 radial=0.3907 drop=0.099 alpha=0.25
[cond_srul] 052/120 loss=0.05506 path_norm=1.0000 radial=0.3904 drop=0.101 alpha=0.25
[cond_srul] 053/120 loss=0.05498 path_norm=1.0000 radial=0.3912 drop=0.098 alpha=0.25
[cond_srul] 054/120 loss=0.05496 path_norm=1.0000 radial=0.3935 drop=0.100 alpha=0.25
[cond_srul] 055/120 loss=0.05496 path_norm=1.0000 radial=0.3921 drop=0.102 alpha=0.25
[cond_srul] 056/120 loss=0.05495 path_norm=1.0000 radial=0.3961 drop=0.101 alpha=0.25
[cond_srul] 057/120 loss=0.05493 path_norm=1.0000 radial=0.3946 drop=0.098 alpha=0.25
[cond_srul] 058/120 loss=0.05489 path_norm=1.0000 radial=0.3952 drop=0.098 alpha=0.25
[cond_srul] 059/120 loss=0.05484 path_norm=1.0000 radial=0.3959 drop=0.100 alpha=0.25
[cond_srul] 060/120 loss=0.05482 path_norm=1.0000 radial=0.3965 drop=0.098 alpha=0.25
[cond_srul] 061/120 loss=0.05480 path_norm=1.0000 radial=0.3990 drop=0.102 alpha=0.25
[cond_srul] 062/120 loss=0.05480 path_norm=1.0000 radial=0.3984 drop=0.101 alpha=0.25
[cond_srul] 063/120 loss=0.05475 path_norm=1.0000 radial=0.3992 drop=0.102 alpha=0.25
[cond_srul] 064/120 loss=0.05472 path_norm=1.0000 radial=0.3981 drop=0.100 alpha=0.25
[cond_srul] 065/120 loss=0.05468 path_norm=1.0000 radial=0.3991 drop=0.102 alpha=0.25
[cond_srul] 066/120 loss=0.05467 path_norm=1.0000 radial=0.4015 drop=0.099 alpha=0.25
[cond_srul] 067/120 loss=0.05462 path_norm=1.0000 radial=0.4016 drop=0.102 alpha=0.25
[cond_srul] 068/120 loss=0.05467 path_norm=1.0000 radial=0.4003 drop=0.100 alpha=0.25
[cond_srul] 069/120 loss=0.05460 path_norm=1.0000 radial=0.4014 drop=0.099 alpha=0.25
[cond_srul] 070/120 loss=0.05454 path_norm=1.0000 radial=0.4028 drop=0.099 alpha=0.25
[cond_srul] 071/120 loss=0.05459 path_norm=1.0000 radial=0.4035 drop=0.102 alpha=0.25
[cond_srul] 072/120 loss=0.05448 path_norm=1.0000 radial=0.4036 drop=0.102 alpha=0.25
[cond_srul] 073/120 loss=0.05453 path_norm=1.0000 radial=0.4035 drop=0.102 alpha=0.25
[cond_srul] 074/120 loss=0.05445 path_norm=1.0000 radial=0.4058 drop=0.099 alpha=0.25
[cond_srul] 075/120 loss=0.05448 path_norm=1.0000 radial=0.4047 drop=0.099 alpha=0.25
[cond_srul] 076/120 loss=0.05446 path_norm=1.0000 radial=0.4055 drop=0.100 alpha=0.25
[cond_srul] 077/120 loss=0.05439 path_norm=1.0000 radial=0.4073 drop=0.098 alpha=0.25
[cond_srul] 078/120 loss=0.05437 path_norm=1.0000 radial=0.4077 drop=0.102 alpha=0.25
[cond_srul] 079/120 loss=0.05435 path_norm=1.0000 radial=0.4088 drop=0.100 alpha=0.25
[cond_srul] 080/120 loss=0.05437 path_norm=1.0000 radial=0.4092 drop=0.100 alpha=0.25
[cond_srul] 081/120 loss=0.05434 path_norm=1.0000 radial=0.4082 drop=0.098 alpha=0.25
[cond_srul] 082/120 loss=0.05436 path_norm=1.0000 radial=0.4086 drop=0.100 alpha=0.25
[cond_srul] 083/120 loss=0.05430 path_norm=1.0000 radial=0.4096 drop=0.098 alpha=0.25
[cond_srul] 084/120 loss=0.05427 path_norm=1.0000 radial=0.4099 drop=0.099 alpha=0.25
[cond_srul] 085/120 loss=0.05424 path_norm=1.0000 radial=0.4109 drop=0.101 alpha=0.25
[cond_srul] 086/120 loss=0.05428 path_norm=1.0000 radial=0.4106 drop=0.099 alpha=0.25
[cond_srul] 087/120 loss=0.05423 path_norm=1.0000 radial=0.4124 drop=0.100 alpha=0.25
[cond_srul] 088/120 loss=0.05420 path_norm=1.0000 radial=0.4120 drop=0.099 alpha=0.25
[cond_srul] 089/120 loss=0.05417 path_norm=1.0000 radial=0.4123 drop=0.099 alpha=0.25
[cond_srul] 090/120 loss=0.05418 path_norm=1.0000 radial=0.4112 drop=0.099 alpha=0.25
[cond_srul] 091/120 loss=0.05413 path_norm=1.0000 radial=0.4138 drop=0.100 alpha=0.25
[cond_srul] 092/120 loss=0.05418 path_norm=1.0000 radial=0.4111 drop=0.097 alpha=0.25
[cond_srul] 093/120 loss=0.05416 path_norm=1.0000 radial=0.4118 drop=0.102 alpha=0.25
[cond_srul] 094/120 loss=0.05406 path_norm=1.0000 radial=0.4128 drop=0.098 alpha=0.25

In [1]:
!pip install -q "torchmetrics[image]" torch-fidelity lpips medmnist

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.8/53.8 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 72.7 MB/s eta 0:00:00

In [5]:
!ls -lh /content/srul_pathmnist_conditional_experiment.py

-rw-r--r-- 1 root root 75K Aug  5 13:16 /content/srul_pathmnist_conditional_experiment.py

In [7]:
!mkdir -p /content/data

In [8]:
 !python /content/srul_pathmnist_conditional_experiment.py \
    --out-dir "/content/drive/MyDrive/SRUL_PathMNIST/conditional_v1" \
    --dataset pathmnist \
    --data-root "/content/data" \
    --train-samples 0 \
    --test-samples 7180 \
    --seed 0 \
    --ae-epochs 50 \
    --prior-epochs 80 \
    --base-channels 96 \
    --latent-channels 32 \
    --prior-width 256 \
    --prior-depth 6 \
    --time-dim 128 \
    --batch-size 128 \
    --metric-batch-size 128 \
    --num-workers 2 \
    --ae-lr 2e-4 \
    --prior-lr 2e-4 \
    --sigma-enc 0.15 \
    --lambda-clean 1.0 \
    --lambda-noisy 0.5 \
    --lambda-edge 0.15 \
    --lambda-latent 0.05 \
    --lambda-lpips 0.10 \
    --time-sampling logit_normal \
    --methods cond_rfm cond_srul \
    --label-drop-prob 0.10 \
    --jacobi-alpha 0.25 \
    --ema-decay 0.999 \
    --guidance-scales 1.0 2.0 \
    --sample-steps 100 \
    --metric-samples 7180 \
    --pr-samples 5000 \
    --recon-metric-samples 5000 \
    --pr-chunk-size 256 \
    --pr-nearest-k 5 \
    --checkpoint-every 5 \
    --compute-lpips \
    --amp \
    --resume

================================================================================
Class-conditional SRUL-v2 on spatial product-of-spheres latents
Device: cuda
Run directory: /content/drive/MyDrive/SRUL_PathMNIST/conditional_v1/seed_0
Latent: 32 x 4 x 4
Methods: ['cond_rfm', 'cond_srul']
Guidance scales: [1.0, 2.0]
Soft Jacobi alpha: 0.25
EMA decay: 0.999
Label-drop probability: 0.1
================================================================================
100% 206M/206M [00:31<00:00, 6.43MB/s]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth
100% 233M/233M [00:01<00:00, 236MB/s]
Loading model from: /usr/local/lib/python3.12/dist-packages/lpips/weights/v0.1/alex.pth
[AE] 001/50 loss=0.2052 clean=0.1100 noisy=0.1103 edge=0.1324 latent=0.0213 lpips=0.1916
[AE] 002/50 loss=0.1399 clean=0.0749 noisy=0.0757 edge=0.1199 latent=0.0089 lpips=0.0870
[AE] 003/50 loss=0.1036 clean=0.0544 noisy=0.0558 edge=0.1020 latent=0.0138 lpips=0.0535
[AE] 004/50 loss=0.0838 clean=0.0437 noisy=0.0455 edge=0.0880 latent=0.0128 lpips=0.0358
[AE] 005/50 loss=0.0731 clean=0.0378 noisy=0.0400 edge=0.0790 latent=0.0134 lpips=0.0277
[AE] 006/50 loss=0.0674 clean=0.0347 noisy=0.0371 edge=0.0743 latent=0.0134 lpips=0.0235
[AE] 007/50 loss=0.0626 clean=0.0322 noisy=0.0348 edge=0.0690 latent=0.0134 lpips=0.0200
[AE] 008/50 loss=0.0587 clean=0.0301 noisy=0.0329 edge=0.0656 latent=0.0129 lpips=0.0171
[AE] 009/50 loss=0.0563 clean=0.0287 noisy=0.0318 edge=0.0632 latent=0.0142 lpips=0.0150
[AE] 010/50 loss=0.0513 clean=0.0260 noisy=0.0295 edge=0.0571 latent=0.0147 lpips=0.0121
[AE] 011/50 loss=0.0477 clean=0.0241 noisy=0.0279 edge=0.0527 latent=0.0147 lpips=0.0102
[AE] 012/50 loss=0.0447 clean=0.0224 noisy=0.0266 edge=0.0492 latent=0.0146 lpips=0.0089
[AE] 013/50 loss=0.0427 clean=0.0213 noisy=0.0257 edge=0.0468 latent=0.0146 lpips=0.0079
[AE] 014/50 loss=0.0423 clean=0.0211 noisy=0.0256 edge=0.0462 latent=0.0151 lpips=0.0075
[AE] 015/50 loss=0.0403 clean=0.0199 noisy=0.0246 edge=0.0450 latent=0.0136 lpips=0.0069
[AE] 016/50 loss=0.0408 clean=0.0202 noisy=0.0248 edge=0.0449 latent=0.0144 lpips=0.0071
[AE] 017/50 loss=0.0396 clean=0.0195 noisy=0.0242 edge=0.0442 latent=0.0134 lpips=0.0067
[AE] 018/50 loss=0.0400 clean=0.0198 noisy=0.0244 edge=0.0442 latent=0.0139 lpips=0.0068
[AE] 019/50 loss=0.0390 clean=0.0192 noisy=0.0239 edge=0.0437 latent=0.0132 lpips=0.0065
[AE] 020/50 loss=0.0393 clean=0.0194 noisy=0.0241 edge=0.0437 latent=0.0135 lpips=0.0066
[AE] 021/50 loss=0.0388 clean=0.0191 noisy=0.0238 edge=0.0434 latent=0.0133 lpips=0.0065
[AE] 022/50 loss=0.0383 clean=0.0188 noisy=0.0236 edge=0.0431 latent=0.0130 lpips=0.0062
[AE] 023/50 loss=0.0382 clean=0.0187 noisy=0.0235 edge=0.0430 latent=0.0131 lpips=0.0062
[AE] 024/50 loss=0.0378 clean=0.0185 noisy=0.0233 edge=0.0427 latent=0.0128 lpips=0.0061
[AE] 025/50 loss=0.0378 clean=0.0185 noisy=0.0233 edge=0.0427 latent=0.0129 lpips=0.0061
[AE] 026/50 loss=0.0373 clean=0.0182 noisy=0.0231 edge=0.0424 latent=0.0128 lpips=0.0060
[AE] 027/50 loss=0.0373 clean=0.0182 noisy=0.0230 edge=0.0423 latent=0.0128 lpips=0.0059
[AE] 028/50 loss=0.0371 clean=0.0181 noisy=0.0230 edge=0.0421 latent=0.0128 lpips=0.0059
[AE] 029/50 loss=0.0369 clean=0.0180 noisy=0.0228 edge=0.0419 latent=0.0126 lpips=0.0058
[AE] 030/50 loss=0.0370 clean=0.0180 noisy=0.0229 edge=0.0419 latent=0.0129 lpips=0.0058
[AE] 031/50 loss=0.0366 clean=0.0178 noisy=0.0227 edge=0.0416 latent=0.0127 lpips=0.0057
[AE] 032/50 loss=0.0366 clean=0.0178 noisy=0.0227 edge=0.0415 latent=0.0127 lpips=0.0057
[AE] 033/50 loss=0.0366 clean=0.0178 noisy=0.0227 edge=0.0415 latent=0.0128 lpips=0.0057
[AE] 034/50 loss=0.0362 clean=0.0176 noisy=0.0225 edge=0.0413 latent=0.0126 lpips=0.0056
[AE] 035/50 loss=0.0362 clean=0.0176 noisy=0.0225 edge=0.0412 latent=0.0126 lpips=0.0055
[AE] 036/50 loss=0.0361 clean=0.0175 noisy=0.0224 edge=0.0410 latent=0.0126 lpips=0.0055
[AE] 037/50 loss=0.0360 clean=0.0175 noisy=0.0224 edge=0.0409 latent=0.0126 lpips=0.0054
[AE] 038/50 loss=0.0358 clean=0.0174 noisy=0.0223 edge=0.0408 latent=0.0126 lpips=0.0054
[AE] 039/50 loss=0.0358 clean=0.0174 noisy=0.0223 edge=0.0407 latent=0.0126 lpips=0.0054
[AE] 040/50 loss=0.0355 clean=0.0172 noisy=0.0222 edge=0.0406 latent=0.0125 lpips=0.0053
[AE] 041/50 loss=0.0354 clean=0.0172 noisy=0.0221 edge=0.0405 latent=0.0124 lpips=0.0053
[AE] 042/50 loss=0.0355 clean=0.0172 noisy=0.0222 edge=0.0405 latent=0.0125 lpips=0.0053
[AE] 043/50 loss=0.0354 clean=0.0171 noisy=0.0221 edge=0.0404 latent=0.0126 lpips=0.0053
[AE] 044/50 loss=0.0350 clean=0.0169 noisy=0.0219 edge=0.0403 latent=0.0124 lpips=0.0052
[AE] 045/50 loss=0.0352 clean=0.0171 noisy=0.0220 edge=0.0402 latent=0.0125 lpips=0.0052
[AE] 046/50 loss=0.0352 clean=0.0170 noisy=0.0220 edge=0.0401 latent=0.0125 lpips=0.0052
[AE] 047/50 loss=0.0350 clean=0.0169 noisy=0.0219 edge=0.0401 latent=0.0124 lpips=0.0051
[AE] 048/50 loss=0.0349 clean=0.0169 noisy=0.0219 edge=0.0400 latent=0.0124 lpips=0.0051
[AE] 049/50 loss=0.0348 clean=0.0168 noisy=0.0218 edge=0.0399 latent=0.0124 lpips=0.0050
[AE] 050/50 loss=0.0349 clean=0.0169 noisy=0.0219 edge=0.0399 latent=0.0125 lpips=0.0051
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100% 44.7M/44.7M [00:00<00:00, 233MB/s]
Downloading: "https://github.com/toshas/torch-fidelity/releases/download/v0.2.0/weights-inception-2015-12-05-6726825d.pth" to /root/.cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth
100% 91.2M/91.2M [00:00<00:00, 203MB/s]
/usr/local/lib/python3.12/dist-packages/torchmetrics/utilities/prints.py:43: UserWarning: Metric `Kernel Inception Distance` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Reconstruction metrics:
{
  "clean_mse": 0.0009533544653095305,
  "clean_psnr": 36.22805586276338,
  "noisy_mse": 0.001374238869175315,
  "noisy_psnr": 34.6399776330003,
  "num_samples": 5000.0,
  "clean_ssim": 0.9590287208557129,
  "noisy_ssim": 0.9443680644035339,
  "feature_precision": 0.9934,
  "feature_recall": 0.9746,
  "pr_samples": 5000.0,
  "pr_nearest_k": 5.0,
  "reconstruction_fid": 7.132111072540283,
  "reconstruction_kid_mean": 0.003886318299919367,
  "reconstruction_kid_std": 0.00023259292356669903,
  "reconstruction_metric_samples": 5000.0
}

--------------------------------------------------------------------------------
Training conditional prior: cond_rfm
[cond_rfm] 001/80 loss=0.06655 path_norm=1.0000 radial=0.2206 drop=0.100 alpha=0.00
[cond_rfm] 002/80 loss=0.06435 path_norm=1.0000 radial=0.2531 drop=0.100 alpha=0.00
[cond_rfm] 003/80 loss=0.06381 path_norm=1.0000 radial=0.2568 drop=0.101 alpha=0.00
[cond_rfm] 004/80 loss=0.06349 path_norm=1.0000 radial=0.2601 drop=0.098 alpha=0.00
[cond_rfm] 005/80 loss=0.06320 path_norm=1.0000 radial=0.2634 drop=0.101 alpha=0.00
[cond_rfm] 006/80 loss=0.06301 path_norm=1.0000 radial=0.2662 drop=0.101 alpha=0.00
[cond_rfm] 007/80 loss=0.06272 path_norm=1.0000 radial=0.2695 drop=0.099 alpha=0.00
[cond_rfm] 008/80 loss=0.06261 path_norm=1.0000 radial=0.2758 drop=0.098 alpha=0.00
[cond_rfm] 009/80 loss=0.06245 path_norm=1.0000 radial=0.2787 drop=0.102 alpha=0.00
[cond_rfm] 010/80 loss=0.06230 path_norm=1.0000 radial=0.2832 drop=0.101 alpha=0.00
[cond_rfm] 011/80 loss=0.06223 path_norm=1.0000 radial=0.2876 drop=0.100 alpha=0.00
[cond_rfm] 012/80 loss=0.06211 path_norm=1.0000 radial=0.2929 drop=0.099 alpha=0.00
[cond_rfm] 013/80 loss=0.06203 path_norm=1.0000 radial=0.2970 drop=0.100 alpha=0.00
[cond_rfm] 014/80 loss=0.06193 path_norm=1.0000 radial=0.3006 drop=0.099 alpha=0.00
[cond_rfm] 015/80 loss=0.06189 path_norm=1.0000 radial=0.3051 drop=0.100 alpha=0.00
[cond_rfm] 016/80 loss=0.06181 path_norm=1.0000 radial=0.3100 drop=0.099 alpha=0.00
[cond_rfm] 017/80 loss=0.06173 path_norm=1.0000 radial=0.3128 drop=0.099 alpha=0.00
[cond_rfm] 018/80 loss=0.06166 path_norm=1.0000 radial=0.3164 drop=0.100 alpha=0.00
[cond_rfm] 019/80 loss=0.06156 path_norm=1.0000 radial=0.3186 drop=0.099 alpha=0.00
[cond_rfm] 020/80 loss=0.06155 path_norm=1.0000 radial=0.3213 drop=0.098 alpha=0.00
[cond_rfm] 021/80 loss=0.06146 path_norm=1.0000 radial=0.3238 drop=0.098 alpha=0.00
[cond_rfm] 022/80 loss=0.06143 path_norm=1.0000 radial=0.3259 drop=0.101 alpha=0.00
[cond_rfm] 023/80 loss=0.06139 path_norm=1.0000 radial=0.3277 drop=0.101 alpha=0.00
[cond_rfm] 024/80 loss=0.06130 path_norm=1.0000 radial=0.3300 drop=0.101 alpha=0.00
[cond_rfm] 025/80 loss=0.06131 path_norm=1.0000 radial=0.3324 drop=0.099 alpha=0.00
[cond_rfm] 026/80 loss=0.06127 path_norm=1.0000 radial=0.3333 drop=0.100 alpha=0.00
[cond_rfm] 027/80 loss=0.06120 path_norm=1.0000 radial=0.3352 drop=0.100 alpha=0.00
[cond_rfm] 028/80 loss=0.06115 path_norm=1.0000 radial=0.3365 drop=0.101 alpha=0.00
[cond_rfm] 029/80 loss=0.06109 path_norm=1.0000 radial=0.3356 drop=0.100 alpha=0.00
[cond_rfm] 030/80 loss=0.06112 path_norm=1.0000 radial=0.3380 drop=0.099 alpha=0.00
[cond_rfm] 031/80 loss=0.06104 path_norm=1.0000 radial=0.3392 drop=0.101 alpha=0.00
[cond_rfm] 032/80 loss=0.06101 path_norm=1.0000 radial=0.3407 drop=0.101 alpha=0.00
[cond_rfm] 033/80 loss=0.06103 path_norm=1.0000 radial=0.3419 drop=0.101 alpha=0.00
[cond_rfm] 034/80 loss=0.06097 path_norm=1.0000 radial=0.3428 drop=0.099 alpha=0.00
[cond_rfm] 035/80 loss=0.06094 path_norm=1.0000 radial=0.3434 drop=0.101 alpha=0.00
[cond_rfm] 036/80 loss=0.06091 path_norm=1.0000 radial=0.3438 drop=0.100 alpha=0.00
[cond_rfm] 037/80 loss=0.06094 path_norm=1.0000 radial=0.3442 drop=0.099 alpha=0.00
[cond_rfm] 038/80 loss=0.06085 path_norm=1.0000 radial=0.3451 drop=0.099 alpha=0.00
[cond_rfm] 039/80 loss=0.06080 path_norm=1.0000 radial=0.3454 drop=0.100 alpha=0.00
[cond_rfm] 040/80 loss=0.06082 path_norm=1.0000 radial=0.3460 drop=0.101 alpha=0.00
[cond_rfm] 041/80 loss=0.06080 path_norm=1.0000 radial=0.3479 drop=0.101 alpha=0.00
[cond_rfm] 042/80 loss=0.06079 path_norm=1.0000 radial=0.3495 drop=0.101 alpha=0.00
[cond_rfm] 043/80 loss=0.06073 path_norm=1.0000 radial=0.3486 drop=0.101 alpha=0.00
[cond_rfm] 044/80 loss=0.06072 path_norm=1.0000 radial=0.3500 drop=0.101 alpha=0.00
[cond_rfm] 045/80 loss=0.06068 path_norm=1.0000 radial=0.3502 drop=0.101 alpha=0.00
[cond_rfm] 046/80 loss=0.06069 path_norm=1.0000 radial=0.3513 drop=0.100 alpha=0.00
[cond_rfm] 047/80 loss=0.06066 path_norm=1.0000 radial=0.3516 drop=0.101 alpha=0.00
[cond_rfm] 048/80 loss=0.06062 path_norm=1.0000 radial=0.3526 drop=0.101 alpha=0.00
[cond_rfm] 049/80 loss=0.06062 path_norm=1.0000 radial=0.3539 drop=0.100 alpha=0.00
[cond_rfm] 050/80 loss=0.06061 path_norm=1.0000 radial=0.3545 drop=0.101 alpha=0.00
[cond_rfm] 051/80 loss=0.06058 path_norm=1.0000 radial=0.3544 drop=0.099 alpha=0.00
[cond_rfm] 052/80 loss=0.06056 path_norm=1.0000 radial=0.3545 drop=0.099 alpha=0.00
[cond_rfm] 053/80 loss=0.06056 path_norm=1.0000 radial=0.3559 drop=0.099 alpha=0.00
[cond_rfm] 054/80 loss=0.06050 path_norm=1.0000 radial=0.3550 drop=0.101 alpha=0.00
[cond_rfm] 055/80 loss=0.06048 path_norm=1.0000 radial=0.3561 drop=0.100 alpha=0.00
[cond_rfm] 056/80 loss=0.06047 path_norm=1.0000 radial=0.3567 drop=0.099 alpha=0.00
[cond_rfm] 057/80 loss=0.06048 path_norm=1.0000 radial=0.3570 drop=0.099 alpha=0.00
[cond_rfm] 058/80 loss=0.06048 path_norm=1.0000 radial=0.3588 drop=0.100 alpha=0.00
[cond_rfm] 059/80 loss=0.06046 path_norm=1.0000 radial=0.3582 drop=0.100 alpha=0.00
[cond_rfm] 060/80 loss=0.06041 path_norm=1.0000 radial=0.3586 drop=0.100 alpha=0.00
[cond_rfm] 061/80 loss=0.06044 path_norm=1.0000 radial=0.3600 drop=0.100 alpha=0.00
[cond_rfm] 062/80 loss=0.06041 path_norm=1.0000 radial=0.3597 drop=0.100 alpha=0.00
[cond_rfm] 063/80 loss=0.06036 path_norm=1.0000 radial=0.3601 drop=0.100 alpha=0.00
[cond_rfm] 064/80 loss=0.06038 path_norm=1.0000 radial=0.3612 drop=0.098 alpha=0.00
[cond_rfm] 065/80 loss=0.06037 path_norm=1.0000 radial=0.3615 drop=0.100 alpha=0.00
[cond_rfm] 066/80 loss=0.06038 path_norm=1.0000 radial=0.3629 drop=0.099 alpha=0.00
[cond_rfm] 067/80 loss=0.06032 path_norm=1.0000 radial=0.3625 drop=0.100 alpha=0.00
[cond_rfm] 068/80 loss=0.06033 path_norm=1.0000 radial=0.3625 drop=0.098 alpha=0.00
[cond_rfm] 069/80 loss=0.06035 path_norm=1.0000 radial=0.3642 drop=0.100 alpha=0.00
[cond_rfm] 070/80 loss=0.06029 path_norm=1.0000 radial=0.3644 drop=0.101 alpha=0.00
[cond_rfm] 071/80 loss=0.06025 path_norm=1.0000 radial=0.3639 drop=0.101 alpha=0.00
[cond_rfm] 072/80 loss=0.06030 path_norm=1.0000 radial=0.3647 drop=0.102 alpha=0.00
[cond_rfm] 073/80 loss=0.06027 path_norm=1.0000 radial=0.3656 drop=0.099 alpha=0.00
[cond_rfm] 074/80 loss=0.06026 path_norm=1.0000 radial=0.3669 drop=0.100 alpha=0.00
[cond_rfm] 075/80 loss=0.06031 path_norm=1.0000 radial=0.3670 drop=0.101 alpha=0.00
[cond_rfm] 076/80 loss=0.06023 path_norm=1.0000 radial=0.3682 drop=0.101 alpha=0.00
[cond_rfm] 077/80 loss=0.06019 path_norm=1.0000 radial=0.3680 drop=0.099 alpha=0.00
[cond_rfm] 078/80 loss=0.06021 path_norm=1.0000 radial=0.3685 drop=0.098 alpha=0.00
[cond_rfm] 079/80 loss=0.06018 path_norm=1.0000 radial=0.3686 drop=0.101 alpha=0.00
[cond_rfm] 080/80 loss=0.06015 path_norm=1.0000 radial=0.3682 drop=0.100 alpha=0.00
[cond_rfm] loaded EMA weights for evaluation.

--------------------------------------------------------------------------------
Training conditional prior: cond_srul
[cond_srul] 001/80 loss=0.06274 path_norm=1.0000 radial=0.2199 drop=0.101 alpha=0.25
[cond_srul] 002/80 loss=0.06079 path_norm=1.0000 radial=0.2503 drop=0.100 alpha=0.25
[cond_srul] 003/80 loss=0.06030 path_norm=1.0000 radial=0.2535 drop=0.099 alpha=0.25
[cond_srul] 004/80 loss=0.05993 path_norm=1.0000 radial=0.2560 drop=0.101 alpha=0.25
[cond_srul] 005/80 loss=0.05969 path_norm=1.0000 radial=0.2580 drop=0.099 alpha=0.25
[cond_srul] 006/80 loss=0.05943 path_norm=1.0000 radial=0.2619 drop=0.102 alpha=0.25
[cond_srul] 007/80 loss=0.05928 path_norm=1.0000 radial=0.2658 drop=0.100 alpha=0.25
[cond_srul] 008/80 loss=0.05910 path_norm=1.0000 radial=0.2704 drop=0.101 alpha=0.25
[cond_srul] 009/80 loss=0.05894 path_norm=1.0000 radial=0.2746 drop=0.100 alpha=0.25
[cond_srul] 010/80 loss=0.05881 path_norm=1.0000 radial=0.2794 drop=0.099 alpha=0.25
[cond_srul] 011/80 loss=0.05874 path_norm=1.0000 radial=0.2854 drop=0.099 alpha=0.25
[cond_srul] 012/80 loss=0.05866 path_norm=1.0000 radial=0.2888 drop=0.100 alpha=0.25
[cond_srul] 013/80 loss=0.05855 path_norm=1.0000 radial=0.2934 drop=0.099 alpha=0.25
[cond_srul] 014/80 loss=0.05850 path_norm=1.0000 radial=0.2979 drop=0.099 alpha=0.25
[cond_srul] 015/80 loss=0.05840 path_norm=1.0000 radial=0.3018 drop=0.100 alpha=0.25
[cond_srul] 016/80 loss=0.05834 path_norm=1.0000 radial=0.3050 drop=0.100 alpha=0.25
[cond_srul] 017/80 loss=0.05824 path_norm=1.0000 radial=0.3078 drop=0.103 alpha=0.25
[cond_srul] 018/80 loss=0.05820 path_norm=1.0000 radial=0.3113 drop=0.101 alpha=0.25
[cond_srul] 019/80 loss=0.05815 path_norm=1.0000 radial=0.3141 drop=0.102 alpha=0.25
[cond_srul] 020/80 loss=0.05807 path_norm=1.0000 radial=0.3158 drop=0.102 alpha=0.25
[cond_srul] 021/80 loss=0.05804 path_norm=1.0000 radial=0.3189 drop=0.101 alpha=0.25
[cond_srul] 022/80 loss=0.05798 path_norm=1.0000 radial=0.3199 drop=0.101 alpha=0.25
[cond_srul] 023/80 loss=0.05793 path_norm=1.0000 radial=0.3229 drop=0.099 alpha=0.25
[cond_srul] 024/80 loss=0.05791 path_norm=1.0000 radial=0.3254 drop=0.100 alpha=0.25
[cond_srul] 025/80 loss=0.05784 path_norm=1.0000 radial=0.3252 drop=0.101 alpha=0.25
[cond_srul] 026/80 loss=0.05785 path_norm=1.0000 radial=0.3265 drop=0.100 alpha=0.25
[cond_srul] 027/80 loss=0.05779 path_norm=1.0000 radial=0.3282 drop=0.099 alpha=0.25
[cond_srul] 028/80 loss=0.05774 path_norm=1.0000 radial=0.3285 drop=0.101 alpha=0.25
[cond_srul] 029/80 loss=0.05773 path_norm=1.0000 radial=0.3308 drop=0.101 alpha=0.25
[cond_srul] 030/80 loss=0.05768 path_norm=1.0000 radial=0.3308 drop=0.099 alpha=0.25
[cond_srul] 031/80 loss=0.05769 path_norm=1.0000 radial=0.3327 drop=0.100 alpha=0.25
[cond_srul] 032/80 loss=0.05763 path_norm=1.0000 radial=0.3321 drop=0.101 alpha=0.25
[cond_srul] 033/80 loss=0.05760 path_norm=1.0000 radial=0.3331 drop=0.100 alpha=0.25
[cond_srul] 034/80 loss=0.05754 path_norm=1.0000 radial=0.3337 drop=0.101 alpha=0.25
[cond_srul] 035/80 loss=0.05753 path_norm=1.0000 radial=0.3359 drop=0.099 alpha=0.25
[cond_srul] 036/80 loss=0.05752 path_norm=1.0000 radial=0.3366 drop=0.099 alpha=0.25
[cond_srul] 037/80 loss=0.05750 path_norm=1.0000 radial=0.3381 drop=0.099 alpha=0.25
[cond_srul] 038/80 loss=0.05747 path_norm=1.0000 radial=0.3381 drop=0.100 alpha=0.25
[cond_srul] 039/80 loss=0.05744 path_norm=1.0000 radial=0.3394 drop=0.100 alpha=0.25
[cond_srul] 040/80 loss=0.05739 path_norm=1.0000 radial=0.3392 drop=0.100 alpha=0.25
[cond_srul] 041/80 loss=0.05739 path_norm=1.0000 radial=0.3398 drop=0.101 alpha=0.25
[cond_srul] 042/80 loss=0.05739 path_norm=1.0000 radial=0.3411 drop=0.099 alpha=0.25
[cond_srul] 043/80 loss=0.05731 path_norm=1.0000 radial=0.3416 drop=0.101 alpha=0.25
[cond_srul] 044/80 loss=0.05731 path_norm=1.0000 radial=0.3418 drop=0.100 alpha=0.25
[cond_srul] 045/80 loss=0.05729 path_norm=1.0000 radial=0.3440 drop=0.102 alpha=0.25
[cond_srul] 046/80 loss=0.05728 path_norm=1.0000 radial=0.3432 drop=0.100 alpha=0.25
[cond_srul] 047/80 loss=0.05731 path_norm=1.0000 radial=0.3442 drop=0.099 alpha=0.25
[cond_srul] 048/80 loss=0.05722 path_norm=1.0000 radial=0.3445 drop=0.099 alpha=0.25
[cond_srul] 049/80 loss=0.05721 path_norm=1.0000 radial=0.3462 drop=0.100 alpha=0.25
[cond_srul] 050/80 loss=0.05723 path_norm=1.0000 radial=0.3463 drop=0.100 alpha=0.25
[cond_srul] 051/80 loss=0.05720 path_norm=1.0000 radial=0.3461 drop=0.102 alpha=0.25
[cond_srul] 052/80 loss=0.05717 path_norm=1.0000 radial=0.3468 drop=0.099 alpha=0.25
[cond_srul] 053/80 loss=0.05716 path_norm=1.0000 radial=0.3471 drop=0.100 alpha=0.25
[cond_srul] 054/80 loss=0.05717 path_norm=1.0000 radial=0.3473 drop=0.099 alpha=0.25
[cond_srul] 055/80 loss=0.05714 path_norm=1.0000 radial=0.3482 drop=0.099 alpha=0.25
[cond_srul] 056/80 loss=0.05710 path_norm=1.0000 radial=0.3500 drop=0.099 alpha=0.25
[cond_srul] 057/80 loss=0.05712 path_norm=1.0000 radial=0.3498 drop=0.100 alpha=0.25
[cond_srul] 058/80 loss=0.05708 path_norm=1.0000 radial=0.3503 drop=0.101 alpha=0.25
[cond_srul] 059/80 loss=0.05711 path_norm=1.0000 radial=0.3505 drop=0.101 alpha=0.25
[cond_srul] 060/80 loss=0.05706 path_norm=1.0000 radial=0.3513 drop=0.100 alpha=0.25
[cond_srul] 061/80 loss=0.05709 path_norm=1.0000 radial=0.3518 drop=0.100 alpha=0.25
[cond_srul] 062/80 loss=0.05707 path_norm=1.0000 radial=0.3503 drop=0.100 alpha=0.25
[cond_srul] 063/80 loss=0.05701 path_norm=1.0000 radial=0.3528 drop=0.099 alpha=0.25
[cond_srul] 064/80 loss=0.05701 path_norm=1.0000 radial=0.3525 drop=0.099 alpha=0.25
[cond_srul] 065/80 loss=0.05695 path_norm=1.0000 radial=0.3536 drop=0.100 alpha=0.25
[cond_srul] 066/80 loss=0.05696 path_norm=1.0000 radial=0.3533 drop=0.098 alpha=0.25
[cond_srul] 067/80 loss=0.05695 path_norm=1.0000 radial=0.3541 drop=0.101 alpha=0.25
[cond_srul] 068/80 loss=0.05695 path_norm=1.0000 radial=0.3548 drop=0.100 alpha=0.25